# PV-UAD E2 → E3-TDH + **trainable TransReID initialization** — Kaggle multisession

In [1]:
# ============================================================
# 0. SETTINGS — one stateful E2 -> E3 pipeline; normally change nothing
# ============================================================

import time as _time
NOTEBOOK_SESSION_STARTED_UNIX = _time.time()

PIPELINE_NAME = "PVUAD_E2_E3_TRANSREID_INIT_TRAINABLE"
PIPELINE_TAG = "e2_e3_transreid_init_trainable768_b24_v1"
DATASET_VARIANT = "1000"

WHUMARS1000_INPUT = "/kaggle/input/datasets/cpkimhianh/whu-mars-s3clip"
WHUMARS2337_INPUT = "/kaggle/input/datasets/cpkimhianh/whu-mars-2337"

SOURCE_DIR_OVERRIDE = None

# Official MSMT17 full TransReID checkpoint. Leave both as None unless you want
# to point to a manually attached .pth file. PRETRAIN_PATH_OVERRIDE is kept as
# a backward-compatible alias.
TRANSREID_CHECKPOINT_OVERRIDE = None
PRETRAIN_PATH_OVERRIDE = None
RUN_TRANSREID_INIT_SMOKE_TEST = True

# The target UAD architecture intentionally stays identical to the strong
# 768-D baseline. We transplant the person-ReID-trained Transformer weights
# from TransReID, then TRAIN those weights on WHU-MARS. Source SIE, JPM local
# branches and source classifier/BNNeck are not copied. The trained JPM GLOBAL
# branch b1 is mapped into target block 11 + final norm, because in official JPM
# training that is the actual global final Transformer branch.
TRANSREID_TARGET_STRIDE = [16, 16]
TRANSREID_TARGET_EMBED_DIM = 768
USE_SOURCE_SIE = False
USE_SOURCE_JPM_LOCAL_BRANCHES = False

# Optional emergency overrides. Normally leave all three as None.
E2_RESUME_PATH_OVERRIDE = None
E2_COMPLETED_DIR_OVERRIDE = None
E3_RESUME_PATH_OVERRIDE = None

AUTO_RESUME = True
# Never bootstrap this experiment from the old ImageNet-init or frozen-3840D
# E2 checkpoints. Only checkpoints from this exact pipeline tag are eligible.
ALLOW_LEGACY_E2_BOOTSTRAP = False
RUN_TRAINING = True
RUN_FINAL_FLIP_TTA = True
RUN_METADATA_PAIRING_CHECK = True

# Keep the stage boundary explicit: even if E2 finishes early, end the current
# Kaggle version cleanly. E3 begins only after that saved output is attached to
# a new Save & Run All session.
ALWAYS_START_E3_IN_NEW_SESSION = True

# Keep the exact strong UAD recipe. The ONLY intended E2 change is the
# initialization: ImageNet ViT -> pretrained TransReID ViT backbone weights.
E2_EPOCHS = 60
E2_GLOBAL_BATCH = 24
E2_BASE_LR = 0.008

E3_EPOCHS = 25
E3_GLOBAL_BATCH = 24
E3_BASE_LR = 1e-4
E3_HEAD_LR_MULTIPLIER = 5.0

TIR_GLOBAL_WEIGHT = 0.10
TIR_LOCAL_WEIGHT = 0.03
TIR_LOCAL_KEEP_RATIO = 0.50
FEATURE_PRESERVE_WEIGHT = 0.05
SCENARIO_HARD_WEIGHT = 0.15
SCENARIO_HARD_TOPK = 5
SCENARIO_HARD_MARGIN = 0.05
SCENARIO_HARD_TAU = 0.05
SCENARIO_HARD_START_EPOCH = 3

# One Kaggle session lasts at most 12 h. Training receives the same shared
# deadline even if E2 finishes and E3 starts in the same session.
SESSION_HARD_STOP_HOURS = 10.5
SESSION_STOP_RESERVE_MINUTES = 15
CHECKPOINT_EVERY_MINUTES = 30
TIME_CHECK_EVERY_STEPS = 10
MIN_EVAL_REMAINING_MINUTES = 35

# Do not start a new stage/evaluation too close to the session boundary.
MIN_E3_START_REMAINING_MINUTES = 75
MIN_TTA_START_REMAINING_MINUTES = 50

NUM_GPUS = 2
NUM_WORKERS = 4
RANDOM_SEED = 1234

if DATASET_VARIANT != "1000":
    raise ValueError(
        "This score-oriented pipeline is locked to WHU-MARS-1000. "
        "Adapt to 2337 only after the winning recipe is frozen."
    )
if E2_GLOBAL_BATCH != 24 or abs(E2_BASE_LR - 0.008) > 1e-12:
    raise ValueError("E2 must stay at global batch 24 / LR 0.008.")
if E3_GLOBAL_BATCH != 24 or abs(E3_BASE_LR - 1e-4) > 1e-12:
    raise ValueError("E3 must stay at global batch 24 / LR 1e-4.")
if TRANSREID_TARGET_STRIDE != [16, 16]:
    raise ValueError(
        "Default experiment keeps UAD stride [16,16] so initialization is the "
        "only E2 variable. Test stride-12 only as a later ablation."
    )
if TRANSREID_TARGET_EMBED_DIM != 768:
    raise ValueError("This pipeline must keep the original UAD 768-D feature space.")
if USE_SOURCE_SIE or USE_SOURCE_JPM_LOCAL_BRANCHES:
    raise ValueError(
        "Source SIE/JPM local branches are intentionally disabled in this clean "
        "initialization experiment. The trained JPM global b1 branch is still "
        "used to initialize the target final Transformer block."
    )

SESSION_DEADLINE_UNIX = (
    NOTEBOOK_SESSION_STARTED_UNIX + 3600.0 * SESSION_HARD_STOP_HOURS
)
print(
    PIPELINE_NAME,
    {
        "E2_epochs": E2_EPOCHS,
        "E3_epochs": E3_EPOCHS,
        "deadline_hours": SESSION_HARD_STOP_HOURS,
        "init": "MSMT17 TransReID -> trainable UAD ViT",
        "feature_dim": TRANSREID_TARGET_EMBED_DIM,
        "target_stride": TRANSREID_TARGET_STRIDE,
    },
)

PVUAD_E2_E3_TRANSREID_INIT_TRAINABLE {'E2_epochs': 60, 'E3_epochs': 25, 'deadline_hours': 10.5, 'init': 'MSMT17 TransReID -> trainable UAD ViT', 'feature_dim': 768, 'target_stride': [16, 16]}

## 1. Kiểm tra môi trường

In [2]:
import base64
import csv
import hashlib
import importlib.util
import io
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tarfile
import urllib.request
import zipfile
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd
import torch

if not torch.cuda.is_available():
    raise RuntimeError("Enable a Kaggle GPU accelerator and restart the session.")
if torch.cuda.device_count() < NUM_GPUS:
    raise RuntimeError(
        f"This run expects {NUM_GPUS} GPUs, but Kaggle exposes {torch.cuda.device_count()}. "
        "Choose GPU T4 x2 in Notebook options."
    )

for package, pip_name in [("yacs", "yacs==0.1.8"), ("timm", "timm>=0.9,<2"), ("gdown", "gdown>=5,<6")]:
    if importlib.util.find_spec(package) is None:
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "-q", pip_name],
            check=True,
        )

gpu_rows = []
for index in range(NUM_GPUS):
    props = torch.cuda.get_device_properties(index)
    gpu_rows.append({
        "index": index,
        "name": props.name,
        "memory_GiB": round(props.total_memory / 2**30, 2),
    })
display(pd.DataFrame(gpu_rows))
print("Python:", sys.version.split()[0])
print("PyTorch:", torch.__version__)
print("CUDA runtime:", torch.version.cuda)

   index      name  memory_GiB
0      0  Tesla T4       14.56
1      1  Tesla T4       14.56

Python: 3.12.13
PyTorch: 2.10.0+cu128
CUDA runtime: 12.8

## 2. Tìm và khóa WHU-MARS-1000

Tự tìm `train/query/test`, xác nhận đúng 30,711 / 2,135 / 31,203 ảnh cho mỗi modality, rồi dùng symlink để không copy dataset.

In [3]:
IMAGE_SPLITS = {"train", "query", "test", "gallery"}
MODALITIES = ("RGB", "IR", "Thermal")

def find_dataset_roots(base_path, max_depth=6):
    base = Path(base_path)
    if not base.exists():
        return []
    candidates = []
    for root, dirs, _files in os.walk(base):
        root_path = Path(root)
        depth = len(root_path.relative_to(base).parts)
        names = {name.lower(): name for name in dirs}
        if {"train", "query", "test"}.issubset(names):
            candidate = root_path
            if all((candidate / "train" / modality).is_dir() for modality in MODALITIES):
                candidates.append(candidate)
            dirs[:] = []
            continue
        if depth >= max_depth or root_path.name.lower() in IMAGE_SPLITS:
            dirs[:] = []
    return sorted(set(candidates), key=lambda path: (len(path.parts), str(path)))

requested_input = WHUMARS1000_INPUT if DATASET_VARIANT == "1000" else WHUMARS2337_INPUT
candidate_inputs = [
    requested_input,
    "/kaggle/input/whu-mars" if DATASET_VARIANT == "1000" else "/kaggle/input/whu-mars-2337",
    "/kaggle/input",
]
roots = []
for base in candidate_inputs:
    roots.extend(find_dataset_roots(base))
    if roots and base != "/kaggle/input":
        break
roots = sorted(set(roots), key=lambda path: (len(path.parts), str(path)))
if not roots:
    raise FileNotFoundError(
        f"Cannot find train/query/test under {requested_input}. Add both WHU datasets as Kaggle inputs."
    )
if len(roots) > 1:
    exact = [path for path in roots if "2337" not in str(path).lower()]
    if DATASET_VARIANT == "1000" and len(exact) == 1:
        DATA_ROOT = exact[0]
    else:
        raise RuntimeError(f"Ambiguous dataset roots: {[str(path) for path in roots]}")
else:
    DATA_ROOT = roots[0]

def jpg_count(path):
    return sum(1 for item in Path(path).iterdir() if item.is_file() and item.suffix.lower() == ".jpg")

coverage_rows = []
for split in ("train", "query", "test"):
    for modality in MODALITIES:
        coverage_rows.append({
            "split": split,
            "modality": modality,
            "images": jpg_count(DATA_ROOT / split / modality),
        })
coverage = pd.DataFrame(coverage_rows)
display(coverage.pivot(index="split", columns="modality", values="images"))

expected_1000 = {
    ("train", "RGB"): 30711, ("train", "IR"): 30711, ("train", "Thermal"): 30711,
    ("query", "RGB"): 2135, ("query", "IR"): 2135, ("query", "Thermal"): 2135,
    ("test", "RGB"): 31203, ("test", "IR"): 31203, ("test", "Thermal"): 31203,
}
observed = {(row.split, row.modality): int(row.images) for row in coverage.itertuples()}
if observed != expected_1000:
    raise RuntimeError(
        "WHU-MARS-1000 count mismatch. Refusing to train on a wrong/incomplete extraction.\n"
        f"Observed: {observed}"
    )

# The paper's 185,742-image total counts train + test. The 6,405 query
# files are a protocol copy/subset and therefore are not added again.

DATA_LINK_PARENT = Path("/kaggle/working/pvuad_data")
DATA_LINK_PARENT.mkdir(parents=True, exist_ok=True)
DATA_LINK = DATA_LINK_PARENT / "WHU-MARS"
if DATA_LINK.is_symlink():
    DATA_LINK.unlink()
elif DATA_LINK.exists():
    raise RuntimeError(
        f"Expected {DATA_LINK} to be a symlink, but it is a real file/folder. "
        "Use a fresh Kaggle session or inspect it manually."
    )
DATA_LINK.symlink_to(DATA_ROOT, target_is_directory=True)
print("Resolved dataset:", DATA_ROOT)
print("UAD data link   :", DATA_LINK)

modality     IR    RGB  Thermal
split
query      2135   2135     2135
test      31203  31203    31203
train     30711  30711    30711

Resolved dataset: /kaggle/input/datasets/cpkimhianh/whu-mars-s3clip
UAD data link   : /kaggle/working/pvuad_data/WHU-MARS

## 3. Pin source UAD + transplant **trainable TransReID backbone initialization**

1. kiểm tra đúng full MSMT17 TransReID checkpoint;
2. lấy các weight `base.*` tương thích với ViT backbone của UAD;
3. resize positional embedding **21×10 → 16×8** vì source TransReID dùng stride 12 còn target UAD mạnh cũ giữ stride 16;
4. **không** copy SIE camera, JPM local branches, BNNeck/classifier của MSMT17; riêng trained global branch `b1` được map vào block 11 + final norm của UAD;
5. tất cả weight đã transplant vẫn `requires_grad=True` và được E2/E3 update trên WHU-MARS.

Smoke test sẽ dừng notebook trước khi train nếu weight transplant sai, output không còn 768-D, hoặc gradient không đi vào attention/patch embedding.

In [4]:
PINNED_UAD_COMMIT = "3e2a07314119402586c76096e87d40420894ad30"
OFFICIAL_REPO_URL = "https://github.com/msm8976/WHU-MARS.git"
WORK_REPO = Path("/kaggle/working/WHU_MARS_official_pinned")
UAD_DIR = WORK_REPO / "CVPR26_UAD"

if WORK_REPO.exists():
    resolved = WORK_REPO.resolve()
    if not str(resolved).startswith("/kaggle/working/"):
        raise RuntimeError(f"Unsafe generated-source path: {resolved}")
    shutil.rmtree(WORK_REPO)

def attached_source_candidates(base="/kaggle/input"):
    candidates = []
    base = Path(base)
    if not base.exists():
        return candidates
    for root, dirs, _files in os.walk(base):
        root_path = Path(root)
        if root_path.name.lower() in IMAGE_SPLITS:
            dirs[:] = []
            continue
        if root_path.name != "CVPR26_UAD" or not (root_path / "train.py").is_file():
            continue
        repo_root = root_path.parent
        declared_commit = None
        manifest_path = root_path / "PVUAD_patch_manifest.json"
        if manifest_path.is_file():
            try:
                declared_commit = json.loads(
                    manifest_path.read_text(encoding="utf-8")
                ).get("base_commit")
            except Exception:
                declared_commit = None
        if (repo_root / ".git").is_dir():
            try:
                declared_commit = subprocess.check_output(
                    ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
                    text=True,
                ).strip()
            except Exception:
                pass
        if declared_commit != PINNED_UAD_COMMIT:
            # Never auto-select an unverified source tree. With no pinned
            # prior output, fall back to cloning the exact official commit.
            dirs[:] = []
            continue
        score = (
            2,
            1 if manifest_path.is_file() else 0,
            1 if "notebooks" in str(repo_root).lower() else 0,
        )
        candidates.append((score, repo_root, declared_commit))
        dirs[:] = []
    return sorted(candidates, key=lambda item: (item[0], str(item[1])), reverse=True)

source = Path(SOURCE_DIR_OVERRIDE) if SOURCE_DIR_OVERRIDE else None
if source is None:
    attached_sources = attached_source_candidates()
    if attached_sources:
        print("Attached UAD source candidates:")
        display(pd.DataFrame([
            {
                "path": str(path),
                "base_commit": commit,
                "selected": index == 0,
            }
            for index, (_score, path, commit) in enumerate(attached_sources)
        ]))
        source = attached_sources[0][1]

if source is not None:
    if (source / "CVPR26_UAD" / "train.py").is_file():
        shutil.copytree(source, WORK_REPO)
    elif source.name == "CVPR26_UAD" and (source / "train.py").is_file():
        WORK_REPO.mkdir(parents=True)
        shutil.copytree(source, UAD_DIR)
    else:
        raise FileNotFoundError(
            f"Attached/override source is not a WHU-MARS source tree: {source}"
        )
    print("Reusing attached UAD source:", source)
else:
    clone_command = [
        "git", "clone", "--no-checkout", "--filter=blob:none",
        OFFICIAL_REPO_URL, str(WORK_REPO),
    ]
    try:
        subprocess.run(clone_command, check=True)
        subprocess.run(
            ["git", "-C", str(WORK_REPO), "checkout", "--detach", PINNED_UAD_COMMIT],
            check=True,
        )
    except subprocess.CalledProcessError as error:
        raise RuntimeError(
            "Cannot clone the pinned official UAD source. Enable Kaggle Internet or attach "
            "the previous notebook output/source and set SOURCE_DIR_OVERRIDE."
        ) from error

if not (UAD_DIR / "train.py").is_file():
    raise FileNotFoundError(f"Missing UAD train.py under {UAD_DIR}")
if (WORK_REPO / ".git").is_dir():
    head = subprocess.check_output(
        ["git", "-C", str(WORK_REPO), "rev-parse", "HEAD"], text=True
    ).strip()
    if head != PINNED_UAD_COMMIT:
        raise RuntimeError(f"Source commit mismatch: expected {PINNED_UAD_COMMIT}, got {head}")

OVERLAY_ARCHIVE_B64 = "H4sIAAH/n2oC/+y9a3saSZIwOp/5FTX4mVdgIwT40m5m6GdlCdtsy5JWwu6d1erUlKAkVQsomip0WR+f337ikvfKQsht976zKz3dBqoyIyMjIyMjIiMjm1vNrX85jG7fx9E4Xvzpu/y1+K/ss9Vqv9Tf8Xm71Wm3/xTc/ukP+FtmebSA5v/0v/Ov/TyY5sk07rWarcqfHv/+t/2N0tl5crE1js+j5STPmvO77zP/X714gZ/tH162zE/463Re/dBx5n/nVaf1p6D1R87/NEpWlrvv/T/p3/kinQZ30ShrMicEyXSeLvJg5/xiPx3HQZQFO/uVypNg81v+AbyddHYdz/IknQXRWbrMg+EiSmbJ7CLYCoZxlgfZPB4l58komEeLaBrn8SL7Dmj8chnP4ut4EUSAx+JiOQWcghH8OIuDOMkv4c0yi8fBeboIcokhfKffgCb8bARQDECN0sUizubpbIxlZoBzcJNMJghpnmb55nlyC4DO7oIoCIdH24N9AhJpsKqjje9EcBxfmOnQGtL9m7dRCXeCHrBLrf4d0P9wsNvf++Zww50mAdZ4f8xwKEbLcYTDPJovraFXFZq7/U+DnT7Uq2LZKtQc7Aaz5fQMOCY9D94dfnTLhlCgF2y0NqDsPnIHFDuLRldn6SzWZfe3PyDUDWhxlkHT03iBFfYinBL5IhmX1NvbPh6Gx8OjwS5Wb0OVwyi/DPI0mC9iQh+YbwpTeuKvf3jUJ6YMD7eH7xGBjQpRIw4G0+gi3o/zIiAATrwUTZL/ihVMpBvMmSCLJ+fBqgowbYKby3QS81to7mCOjJl1g40EG53F+UbQCDYQEn0B1o3z5Sze8OC98/6AB0TXxR4MBA4wF4Ecb/b349FVI0hVQ2ezGTzZQKQ3ZqkBeL+/8zNCEwVMUJM0y6Ajo8kSRmMEEgPGHJ+ZcO/iTAFtBntYgzAwigeXIF3Hyfl5vECpg3WnQBfgOpqqy0VE01RhNHgb/jIYvg93+vvD/hHihggb73fDvYPj43D490OiQ5ae59PodqNY4pf+4N37IfIJaH3qLTDP4V5/uKrI4c6287plvn53uBt+OPgA+H38QO86BnofYKAGOzaKwNDzCY6UO1BT0EaSzQuYfuPxnPjDJO5wsYw3gB/eRpPMZIbdAUwClq29gF4WACNRAtFsYdDK4O4fhB+2j96tADuJzoC/s2ma5pcmxHSG8NLz8w1rHPe23/T3jj8cHPBcg1IFiNFidB6N4rVx3Dk4BrB/J8ZgHAHkUEsRmI95bouwo4NDOd1bzbbz4uBjYXi3h8OQ3h1tD/vuSyD7/vHbg6MP/SM1vPupNVdZPIXHg//AtyftV42g/eoU8fzXww8gr8TypyvgY9kbDeX94O0w3CcOe2k+/vj27V4/fHd08PEQXnVs+Qvt7vX331FnX+hXR/1w+wgwf4cYIWkRm+NB34cNPA53DrDgc7Pj9Bik9tG2B1d492nQ/8Uck6Loev8LUnRwIGbbd1g9B/uHH4ffY/UkwHr1PEa5DusLinYSw8F4ucAF1VxAqU4TuUDN1ZPOS2SGzuvTlUBA4XIB9I+Hbv2jaDYGrXa+SM+is2SS5He0hjOoy3SR/Fc6y6NJcD5J5hrc4dHBG+Lpl+UgFvw4XkSZ1RfgIqv6p2iyjDNc7kD5U/ojIzCD2YjrnxLuovnBv/f3wg/9bSJHq/ni9csGQHuB/YKP1qvT3wP3eLjLYDudHxFep/OCP14qsEjxeTQm5TWDETBAbO/uDvbfIXd+F+bcjfIIhNP3YM/d7eH2cX94rDl0LwFFSjDXmBsmXT2z9LwGGj6g72S4MINEnoMulYUjKD9JL8BINmGTyoYt1DZ+ef9xExaK4w1s6QjWAljeF/EoTxd3oOnAMi+bzILsMl1Oxmoca8BZwTi9mU3SaAy/k3MY0BxwWs7Gdau1I1g0wt3BETXYbG4hRGrvYDGGFkjVigTHTuCJ6B3Age9xNIIlcA6vNWaNIG5eNLnrW3+TtX/aetr8dX5hNQ1ia3tvMByI3h69e4ML0eAI/x1C94D/AJPvxSJ7SJnF9+KSvYPtXVo7BZ/sK1UeCRzgsJAIulzE0TizazVhMQp/OTj6uX+ElHmNMiyagobBdqIJwKl4vP0BVC7S5Q5//rBhtZvMsjyagQaAMFCvPovy0aWn5cH+8XB7n3Tf9qtvTf3gCfYmnVx/c9IDZOjL8cHeJ4vuwjJS2rAu1Dw4HA4+gNQ/CoWVVN0eR9OqRTVQeIN4no4u48yo+WH738P+4cHO+2OSYi2o8gbmYTCJowXZ3qBrx0b5N8Dw4R6i9TzefMF+AuEMwNKTaHGBSrxZm4bpfATv7iyk90Bx7Idvdxic1B7fRjj3EGEF5CyJTJTfDLZBoTsK327vDA+OhE13f7Xjfh9FfbvzHNH+kKJDYzk1SWHq5z9iGegMiDiUiYZabBFPqL6t5nOUoFavodrxu11ckggjkqts42T4zjB3DIhswTBFeMV8E02Q18fBTZxcXOb3V3WNkFbrJalurORS2wLUOB5FdwYErhXu9ne2/67r+t+HOApWAwRNdb2Mf95tf/iwLdRqWSfL4/mqOsfD/iEJ1hetRvBDCyfDTbSYBst5cE7DbuK4ffTh46HmDcAPG1IVaAZkxQpqDiDNQb29TMdEKa4mzQywMsAERemTbzQ2JmB0R4uNIjAw6N4fILNVuUi1Yo7TwfFgvx8avPOy+PZ4Z3uP9GnSKwhpw4eSRdfki7kE+3ueJrPc4oP3YJ8fHgz2h+Fh/2hAeLRxXifANKQDkexOYLED2isfGyzf5tw8eGfWbnmQuIbVcKx0KlGv/2l7z2nWkNuojoH2AL9YYoMZdplkAfx3MQF9ctIAIxQX+BvQRqPrOHiN3qIsQA1g8OEY4YZvtoc772kav27wog1FyJ1IjkZQX2HGtl8V29I4uqBevahYPddWePUMRGH1uywcqJ5/e7jYD6H4F1ZrlyKu7YD1mh4yC/sbPc9kfi/iTdD2r0gXdI1vw/YmcKD+gwn5M+vIUsJL95vlAVNVlOiqVml1SQDT8zjKlwuSK+ynchV9xK4BT+A7edmicxSQUHbmOrWoCPufqJDGFd1a4dv+NrYt3+nlTaIAvDpLyZxAlzU3yK0D397FGXzmWCj+bZnADEEtGXAdpbA6xjjpSHFRbWJz4f7BEa455BiDFlvUoxnqNXk6D6+CGOAsaaJBTxCZmyQTHvR0NrmT72Vx0M1xw4qgTLcPVVvDg8Pw5xAnKMgcqU9gISFNSO8HBKdRLugn3PhNBYK8SB+IQlUsGkLZ5mx+VzUINYomo+WE0AGAiFuQjWhYpAQt+mkIOGJmegO++ZQ7/LT5cXsX6QMiGbgqvs3jWYaM8T1a64NeCEsbTBmcamIXkdj+Ehn5PBklQBpE6CwGYZeky0Uz+Dm6uJjEbF9B6XgWnU1wykCdaTBaTpGwyXUMg17rt4PNn4L+izrKTISZ4XiOYC6h0KKdGjDSx0tQkyNYJhOYFGcT4iIaz8NP2LQQE/J3s//vKLtRDcIh7req+hVo0uQKqp4ns2hSDay/J8AP8XUVV+jWFiwXbEnVcZqJ8hrQbv9TiG4e0yek3+D6MdiVyqj16vgQTKxQqHGdVueV/frfPvaP/k7C63Cwi34n0gx1mcPtwVF/l5xOobYuHBSO/76/E4qS2x/fFQugE21/N0S1GZqgjYsXJh3YnT+KpsFgF1Yu4HvQ1NNNHJNxNxi1m83RS5OoR4OdoWwQrRflbFNlPr09PDrY2S6iQj0Bs/PdPg6YqfMZLQz2P20fDbbhPRDFX+QYNEcocxDu7FmaY1sXwQkaalBv9vr7uwKMLrQHWO6FOwf7xyAm+vs7fy+iXChiaaomsPfbR7vhu8PdIgz5pqQ36jXIu59ZBym+M5Qv73tg9qMh64TKudN/vjncfU8a4SZujecBbrps5ktUn5oBqn5c7am5lRMFs/gGRA0suwlaHH9F/0f/+OOHPjuYF/EUVsGMpNLiWixnMHcTVPEXy3kOj/rPg8VyRmoQFAN9Fz1dtLOqbMGtDJTB8RIM660jWGzjW9CLJ3d6pjffglY5/LjvmXUacXK+Sr93teorAqw4PEDtyFds2N8G5fOoHM77/vYuWm4fPu4NBzCbaQYKx+4hiCjo69G7N1v7gyOUbUP4wFUGFjqWW8E70hIDoOzFjPajYaGNJjfRHXxcR8kEpeVfWVyCPgsrESxhqL9nQDDaOhrHsPpusvkDjT2/fY4OLBDQU/xXrnWiN4OjEBe8wd4euqD3i5TDEu/2Dt4AS5vTpmWXYJ43+fy5r8DP/f6hcnYDRxtQUEv4SJ7U/nH/6FPfnTRg3IFJGC2SdDO6QZFzGS3GKP3zNL+bx4FQ14KrOJ5nQZbcKk/Y1nUC3KlK4kKI+iHSKUdHGbLcFLg8Y5Cz+ILWH1kggRdgUuCyn18C046XIPZHuPazstn0CJnyiW0XMSn6sqyQmOOl74153ioHsv3xnhK2OHjuKfYGtFxng4+4GgM2NjGMzHWvK4US7JxFdIHDk6AUwBgT4MwsxpiHHFd6CkTh6Y7a45gGIt2kyAkYuVGckeeF1T57xgNbvd0bHIbDoWf5gIch7zweh28HINGF5yjPoxAM4EWCoS/ZddUQyqbgsmf28TawJe2098GI+rszJvjyDZsltLipN772RdshWIbohGUcNAof92FU9wdvGZyFQ//4GOZpuAtSZg+N6I/7g3/Xm3FyxcVdOjGPPgz2Pw77rGyYhQwTmrpjFHxuFRyCrhRSaVFQuipMIQCVSe2GZj9sD/bBGDLhvbSxg5lukyPD8U1nIYx9vsyav2bprFpQIMTAwML6dvBOUvk7KLUfkmwkranvoqIL01B7NkgEgYUCc2KSXrAvzjEbDz4ODz9Kzz8wxLeJ/2o+xv8+xv8+xv/+L4//zbZYzt5NJ99p/pfH/7Ze/MDvzPjfTufFY/zvH/FHRky3EgROHJ0Zgme+RaUI3v16G14neYj2fjhvvwphvDZft+LR+Y/jcXOeX2IdN94Lqt0sCJodANUV8VH03Ahw63J8WxCgjtB1IiLhqYzJ6rIeEAQqzLIb1DZaG3V45AYlARiFdzJDMEZMUleHJEGP7Ui3Lm+xBIEZ4tblCDeKkkAa6pCWrhmRIl+ALuc8x6CRLhn2QSBiSORPEXTRRR0LfqnokC5GcVBoCP9zqt4eD3eLLyty874rCHncteMUoGERUIAvtq7INbd1ky7QltqaXy+jcShCDIJABwBAS/79f9Ekb08TUdgJ1RU73ICFsWXdDV6IJ2L7HB9UeI8CK9s7vgDj+N0u8ZbazwUCdZBCYseWxqn1GpnJ9PF3cfsjCKyNK4Amt7bUGwkTR8DYuO0KqyIICttOoqzaSILfiI6xQySG0NxW7AZBG/eV7ae02diVb+z9327QoWbUXKJNm2fzUfTsYj4G64W4SzSsZoRDA2A9ZjSxW6G7JZl8gwZIbhHonQR4qpz4IrgVZ5fytQPZKxVaQwgH5V+Fsv0WT7Ptdzh+5Cbd4MlKHhSNg+EX7ZJblB9pf2iX3aH8uOAHhTo0bQruT92C4/bUL1x3J7Nl0W2pCCu8lRqC10sp57LHOylfebySXXJKBoHPGymrFTyMGpMy52OXbf8gkK4JXcXxNcpGLB+j4GLHt9hlT5Dx3HAiiCrSJ2dwm8cXJ3ivzAcnXhd9b+JF0efWJZdbELgOLo1GwbGleuM6tLrszzJfaEdWl/1YPEM8DixF+IJzyOBMj1Ooyz4h9yUPRvG5HhBPY8PtjyVvrPF6br62nD1d9vXQaBr+FoOYHj8LLtq2m2WD5I9yr4jBc9wqonfSnaImnQe8x4tCTRjuE9mGz21CNKGZXnSXdNlbYol8y03SZS8JMoXPPSK4v9wt0mWvCMlG0x3SxQMPBW/IhhZIlhtEUKei3QNQv7k1SaVSv1F5tP8f7f9H+//xz/cn45G3UJ38Psd/77H/YbK/fO7a/y9etB/t/z/s/O/hYE+e+6XDfg3+eJtMYGHhjZl0MbpsLvNkkjUpnFkUl6H74mcKHIS+7SiDr/OKgtJEcxAs44/7O9tD0KUHH8AaOFZBAJVxfB5gXHVIPodaMr0IEU4djYkgqFarP8fxnErQDhKdd1jOAJsgW45GcTxuUkEKs8OQkOg6TcbB4KC/WOD5iNlouVjw2dvLOLq+gzeB2FNqAnCqe5Hm0PqF2kDCZyIIH7rSjG9Bw8hczPBvEWGckmirVv38JRincUYVqVK1iT6LKNd161T35hIIQ8VE0xpkvrjTPwgRQozI2Uzn8UzDwmPb1/Ei52j8ulVLd0koUPwX347ieS4xthuaL5JZXqsWKHdzGc8U/Tc+f9loBr9gZBa8S5vBLqgneXCTLkADC/4VZlQwgs5NmmVdV61FWUYPFnG+XMywm8AMowk8pvBswV219OzXeJRrbqBPit/msilyDwy4EGaqGH1B3rqIc2YtLBEms/O0hmdKG1TDGEv1ZZ6MswbGt8C/+SIaXWV4fOa0If5X5WbLKZIY37Yq6ikGN1zhsREE37yK77Ja3aazrPesN4HRxGInV6c2cRBI2EBMCBH8IEygnwIyVLGhSsyDZ4AsfDktvMUe0VuCWHwv+oolRGOnFk2gnzgg+FVjS0D5BX6tVxxo/Ip/1C3SCZBIAxskvhRg8aUNFl/ijr5860IW3CQbaChqNxTchgaiuYSYPxRMRLo3hmWMMuKVwozfT/MBnvHACI14TPPFYl6arZKDDW5eycYs2lYz80o0G7xx2Ah+W8Z4tOcimkzgi4E9dpzKGMTh35pE/FsTin9LmmM7Tc+UolL2MBEWRkP8WzfEvx/aENWyGxL9NJqST3Rj8slDm5M01BNciEkxooEeg2617hYK1t4/9tXNlmfYQhD8v8GTAGcLfXKMM36FvuBpxG/dLJ9DpmY/d1+Ov9Dna/H54/iLkuwP46a6pykazHWbWp+ffE2JgVyvqYdyVP33DYGQHJbUsCUGzv0wxKC7MDSWLyjQkJFOSczrFe+T9PD4tTHzn8jy3WCcjPKaOii4+VMwEcci1VJtrzyyaJiMjX7ShJGHKHuWxFKvNWYoraGVmn7iQFKIQ0n1vWL0HYS96LopjVnaZ8tpDRcDE6eT6WmdA8RxyXTQqZuQYdYneTxVhE1m4/jWaAQ0wSSTB/Jq9BYIvQTxXy9oaqwqVJxll1c65zmQGB7iMBWWflixxrea8NiBGFgOz7bENbcrRTVADyNocKE5lKGUdIpIoonTE+rXCbV8WtQNgAaIL6jYiHCxSd0h0aQPKXjrU/R9RbNmNAddd4yl6j5NBkgqi9AvuxCg63BVwlq5H/uEtMQozxc1u1oj2IBGJkDmME/Di0W6nG802Eio+4kgeMAGg73Iit2IAcxKKCdFMHVx6vsCmQKL2WOllenMnMSZT8Rg4N7DxczdekJmTZnyVfLkDt7Lr99QihQkiNWm0NB/r9yAxaEoNVYQyJ2wNk48a08rXzHRHjpFCKqHH23hBWYtJb/qkeGMfiX8WYKCZlZ/3xsK3qN38nv8Pfr/H/3/j/7/R///1jS6ismpQAlIFt9yJ+Ae///z9is3/u/FixcvH/3/f8SfcNyTf79i/rhOcAdaL/QZOvWH9+8GiCwtXJBW/8zaW9iVuqSrhgrQyXRKMJucaykUuZYkDE7M1BcJmLiRTORaEUUOf/4gsq+I9xzE5paig1ifkvhGl294n+7uHlqADJIIWMd3s9HlIp3haWmGoPKuiZo3l8twGi1UjV/ef8SAjWO7ByHmuiv0IkQEzKFp4nGxRXK2xCM0lEIQqFcJQ84SgeriZ9KxdJhfVzXYqHwR+y3CK5PisbM4PJ/V6Li8UEzReAgnbD9k0oCABwD7v5J57SmXrUjvm23k8/4EFj9pCZVZGjOMP0y50VXthHsNRro4n42/pEkDlU/B8EimvZZhwgNVQZm1W6yz6itcydwAnnhOFzVGfoxnvnr8AlTvVy8YJW2TW3VKsVI0OPWBXAtH1zLLtGlGQ3IdTVYNiF2HdGT6lJq1b3SobO4SRkIoIY3A0xwsbp/Hw8WD2/DgI7rlLC210fmF7NV5AD/8h5LN7TDkVGPa9VbNuJplX2Amsx624Sada9hGyySZh5jtzSiL0bgNZ7+K0qOZZThK1y42jaOZWUbF7trFsnxcKHU83LULofiLXcxEqLAuycNm+xI8VBs2d1KQI1lcO7EaAYgxEqrmJRQf0p2nfDy197zecCuTTH6vTv69BWLW5g4lC7UOo3GtQMgS2DuLdO5FrlB+mA6ZxQtv9kV+vLhWPj5lY+IAsxahmpEk0DNGdICrtzFPbuPJRgPTU8EUX87yXhumU3ydjODlaL7cMJo4Fa5JFAf3jl/p2PWPhwZMP2W+CVUkuijyMG4cMz/1aF77M6RR4aJbWFZwMs1JN63yCql17sSqQbHtp3ryL9I071klZJy77r5Gomc40LUbn5Z7gNFTQkq/TJf5fJmH42RBb3X4HRcRaPMkZMQt177oT1Ps1vkxMbxs7mzWay859YiMEqa9JyOXgRAeewvh5gXzG6g9paWuaZkyhHYxi11zOZ+DeK8Hfxbp7NwtU8ozyXES1nyqHmCCF6gRKCUtCzKARqeEGwFoOhjMEHzWOzR+DOqGRDRxdbMDd52tmg0jcTAFxBqRFNNkloS0ooY4zwRre5MsbW2RLkZ7iDATJmOqUaub7kC93vlC1S2y0A6kpEivTDetFfx0Nm8VPecl6PtLluQaLBa+ZzKpoJQFprQMSQ6i3qDnViHpSLEyqr2j3KhSDNG3K2nSFx3tLnkthfufiKq6j4JLVZdcO03aGc03WFD0tmbSoeGye4Nih+qOVsGKnK8FbQLaFFSCsFGIgxFrRs/4bheyutWzftkFte7cc60bR5GDd9N4CotID7u3WpF62KRdPV8fJ+tXTlbfPP2nnKPOBHrgfNETs7deZ+Ss8c6XtWbfWpPK0Fi5a8Zmt4rLEM8qaovb2NvWhNPjjtDIvdQLPsuyXTXGBBKX2preKzo5rQfPVAkRnVEs88Vqoqid0a6obN3ci7I18roF5t4hFW2tHNBidkJnOC+X5+eTuEfbz79vMG1ngysCndGU++z6kSfOS5WSMY0rhqkuOGYRn4fFLV1gg5PWqaFBc3JzxQ1mra4966kp870x4mpSCXi+YS+01whsaD4eMCe1hu1jBBeFRuUrOKGEC+7lgHtG33b+GF1q+DrYMPnDiL6SUZZsljSk6dFQ5sXjNtPj/u/j/u/j/u/j3/9N+7/WJtm3PQd2z/2PL16asoD3fzutV4/7v3/EX7VaZTuV12eRWdFwxXGGZbmT2KxUDmZxcJfEE7qlJI8pZiziWFi6f0EoSpvq/sZkNk5GcdYMticT+QNVfkz2x9VAwcLcikaC35rMzdgQEe6N4BzvY6o38NzU6BIbnadZlpxB9bN4FC2zuCKR3GwDF1EJTrYZjRZ425rIubk1HBw1g4FO7ZieiZykgNNZml8GfCwEr7A7k7cSvCNDeGs7XmA6YwoCzf5q5oc0gVC6akxsTWknOfVpJZnpJPT5JQC4uKSubnJuSsaUATcrdN5DbPmO0vmd/D6NcrVLz/vj6lfMW8mo08Ujylwnd5JFVmYM+a7cv4/s3eB3t9jl/nr59nV2CXw0DsUmfhbH40qlEr492v7QD4/6FJzYHKXTeTKJa4tqeF77z/GzehV17ebg3f7BUX9n+7hfFxuIIY19eBXf1bgpsX3IIZN2dDNtQmKYIhXkvQbKfdoLVPNNTo1d0+GIybkoVYhuLniuqzvRDGMk59ECXkieY/YEjqBEll3TVW0cfJMbwLNcRCzT5lqNmm7S4NfaddXr0d1oEo9r8zQFZZs2jYA+M2PvlNCAt4Uw1hO534zJMrUlzkcO0TrjN/XgbwxXA6A25ZYMwjaOVc0umsLyqFEx88QVZeWkVONj86XAh9+fdKmxU3VMKrRcZHgSqiY4a3Uscpily8UobgSmn5IOeYlI28w6EVEMry74tV40pLuK/IGBMTN6bqg3Et5sC4jYwRTg9sO/BB3bg1VkJJELmAQAsSsnOP1tmWDq42gWxNfxzEqXFPzUCzpV4yCSigsWJBFbN+KXXczaw0C20w+cEGy7J1zYelb/6jMeLuUFdPexU4vHBsqeAUfW+JcbNm7IMlHOeOQU5ks+rDOb9Fxv2iAhfVs5KmbabA/dlZR9yACF2YhNIPh7VfVWxY3KNsbrLy5697GWSCHNN2AQiCkeyz3Duw8wsouWzbuAANL7qkMhyittb3u5SG1tuVgVulCA8hcPg907TeLFJt5+wp3x9sOcI1UPM+M+aDiHFcpASPaogKPsl4VkxTjggIdcNn8KzONTvH5vwgplvtnk7Nxy75oC9bW/h46WIYvo9bk2iaZn46hrPcN/jENXrufUmYHdwkkicepARzI554gMgaHPAnmOtpgnFMIVy635hwTpedZv3/EbLIsqGNGFji9rdPxHZIq8sqtScwuNCoEiEQBc7/MXRTj8Dq96xjLtbUFElpk+YKjmLVovdsrblRMAcEpiD7nB5lWBdA/Uh6LYnHPgiP12lFJi7ThcpDfOAbPLaHIumdyW6MDhHYuf5nyoPKP99hqj7XAAKGvTdFZ6Wm1dhhRMIQ+FeynkOewlG6equCHHD4S2xhJUPPs/VMiPu+ig+A14nziN8TqEdJSMI7hSNkhsetI6Df7W8y9o9kGciA2GNeD9VAbOe2JHLIiYNbpGKSQYb7pRJxeteqYwT5gjTJ0x9QViqIAMMV0mdH5fcCVP3cw2k7qiaSjdEO2uP6lQE+Xqdf4hEPfPr8rqJ0IfZsJ2PSwEnZ5hthHz6WWUhdgZdQacFAdBTaSuDyNoya7X9W6czhEeDKSfCO2G/9QfmwOXzVGcTGoGgYKt4HySAklxWtfr9XWriw7cX71IX4xum8TUxeLRVf/BxSfBbkrDAPrNCFP4k1NBuQL4WLk2m5vCksR7ThceYHQvxmyUb7EpJDmRlpNMXRmAl/7IezGowQYOnQcc3m346e3m4SLd2YaRya7I4bCc6drkKWCTHO/UaN5DE9J19dwrY99vyA1G+3pMiyJ+jRE2FhySvyps3BIE02ieVcGcBZPWktWnpeeqvxQbrjKJqlJYeEow6aAEf/GUMHoOxYxfnrL29ITi9gO7xpciWYzlVtKGx9BZVoy1V+591pRkY0lULxdzDQG07hp0MtMKr1bGQFmRZOqsKqVOASt0pbrr07KthaC6jxmLZuSYMhxb8vJZdAkSIEO/5usM8UDtRU769HJac+nXvKY7q2v1evDUp1fbVoeEZEMuWhrldpRV04Z+vpyYyOoGXWMzWuShvkayZ9hmVIDcWa4mxG+AWqN47C0wXgJatAcqRnfphKrjZHcn5YnLyiKhgVTY5PB7du85stGOs7T8Leikouu7apizCrDbZNkJv3h20W/g0qoN5HO38cXWCYJskubZFlnVVP9wsBvc4hetc+KFO2DFlWsGNjs3bHo1XG7fdN4XZa7JB43Vc6PhYcyy+B0jbQTu4lOfhWuKvhtal/Qy4DjwO3P68ts/9wyPRLcoiVZxlOZYzgNkcm2tVeLyoE+7D25VcZRd/jZ6VDI/cFlrsStT16qXTO3CGthqFKfnpr+pp36T3Ts4OYY2kAHtHPUXpDSmshQm4pc+A88ipTAQrrvVXjerRGJYdNSE5sG3OaqKgFQhEO2Mha99/OZWtgljNua8Mpr9oqmDYRuhQ6IG08zxdKac3sj1OFHH/RxGmGAVCsUR1GgYZSzW4LHQxYks9ZVidU2SVe6dI2azDkEbQatuZoihM0wgOzgBiMy1pb3xDzC4lVfeMON9Mt1JETE7TyVwY4GwQ8BCpWl61RjXikGYxRWmWxIGio4csSXBFYVWd9rQDT8lIjBhCmCUMWyDEarf2mDAYNb9PPHqzYzZCfc/Gd8KgN2afvIsaNfF41MvjGcC398HBQdWF9fHA0UPir1bx8qyjRBJzRILAkls6s42nT0LH1J9DetwjWEwmj0p9QSY5L3POWz+FUdhhXZZTuFvNFCaEqcF5xg7rWYGxTyeGWNzDcuXGZHSzPDTk7bTxbQiyw0tNXY4lqfBKqOG8FQVvGnizFcZ9j56if0/vyll7REaIjdCdUCv9LEUuiT6u+a2JG4n00azOC5Y0yvEM7xJ4kfJHI4WpuW50gdcOW9JIO0n6NG2fHMcx3P8YmimdjxnbMY821uwClgdd/UeYLtB0XjE21xEd1LBNbh7dN16MfzYz7V6OaLWiixLdeWeryYZjXJzns5rda+bnzat7dL+Sa561FzEUzC1sY2CIw4pyf1SqrSrHa7lBq0O8JDrDJYnsZUjIx4IzibZnDGWrHoIGKtp6ZBYsLYoZCahQk2jmIVKKaKmwlOak8lSZH3q6VpWhOesBZcqLijFoI6ad4hdy9yb9UxOWfzA+QpmQCd4+jR43gbtv10vMb8sA1xNc8+k44I+GeK4UVxkbVosMzHfFaPFZH1aP/9SuhFq4yS+nXQZ6umJ2inudh0Iej7SjTmUCE66SgVTkiNewLZTFdDT01XOD0SfABuUvUrmkm4PtbuQjFj9p0Jb97qdis67I1gIMJRGtf75C+WsjsdyK2ITnVFsboge3bfl4OtVo7ykSSzpfHI7f59/tV4YQfo8QUJ1T0uMY8+4yJghQFu+WjclpuHhkiE33kNpxTic8vibp9ECM0E8fXp1g9+MVvnBSdWYS9VTK5869XdJZ4SbCqwLcCWqeDLz+2JrpUq/H9nH+P/H+P/H+P/Hv/8h8f/6YNs3PAJwz/2vz9sv3PtfXvzweP/LHxb/b+ZSCi7ilO9UC6LlBV5twCoYGYS85WOE0YuN+KYZri7C0lfnkgMFa0ZB6qAXYVq5t1+d/K0kV53MOGdmLvqQjsE41gmFlKKxIpmUuqthez6f3Il9UYzpw4RRWyOAIil2R+EiGNSFhiAUCyTyuPMlY5ua6iYHN6e0ugynRJPhIGeVp6ohk1E1KN0U5ehpGNmiCps2HMPJDiJPyK8CjHoqBRWoJ3U3Ro3aFeaX+OUGBANKKhQYvhfCecfyLXytFwJnzaHvOdmWnOtqdOolxtqggEi9VKXUS1V/6qXqaL6s+raPwnCEtqPK60w3LhS3RszkzlSkEdSwXzI5fF2GZPFbnzU0vJtLH8QKRgQLaB6PcjxqM0tnm/F0jsF2dFsItmd4JTgxUcEnO3zbXHCiqISveFJs4Sb4Kkya5pvBzkf4v3g/DSNAKfuwe5WibxToZNj56bSmAhUUf9lE0egDxpdYiBGu2w1ysdOCIS+586egtQIulLLIILl4dRt5Osd96HMY3cs4ubiEz5tkTHablioU7D2PQDBmNQZw0jo1qO0bKMAIRYlEqayde9Cz4M1UXi/4ATJGJP5jUjb0LG2oGXkPdHmyxDNHawycAfB3E8KjkvVo/z3af4/23+Pf/832n3GG81vfArra/nve+uG5O/+fv3rM//3H/D3ouO86J4w9p5Zny+n8Du282dx3kLn8LLIvOfk8GV3htaTy5nb4OAgxGdmh3Njiw7OohokYQPgQRlbNuXzviJWaSN4GylvTAWYtHwdg9mJN+DW6ApOuQUcIxAlusA0odhz3bjJx92gsI3voEtLRpbyVVN0wymfyiojL47zqrKBoEXTlXi+ozkajSdWyPDx9997K5KURtTKLbwRFRFu9Kva1Wth2KMHW3jQUZRl/hNr85eBob1eMREZhNKCKhloP5cRKVFYMicDDPDIpycDF2GrOAFquCoOWecKINwSdToUFh9adyk/IP2tk7CH9VFtAXarNG5LV0XIcydO1Z8vzc0rnxQzXHAMTZ4S3OjFOe4BUrA72BigtL2j/srsyBPcIz4V+/oJ3vFIqgBR5afMC5gO09rnb7Jx/Cd69wUwKlOwKmFB0ZtUWl3PKtGGhthXUFG51afmWRrfyubU8DqPFIsLDe7N5E+c9QxNAZeZweLeELr4WWbBY9XdyjWtgdr5xqqgMcf6wM1BRfcFEc3ROpuEkWoCdmUs24g+bkey5bZjcaCefQKOnXT4RCyTGKSxhAKVjmLU0pXWCZHrZJWcLiATRw/wyyvFIAdWfRreB2gyVjd97kJgw7hU52x5bA8xPPXHCGAOy8WhBk3lmC90Ugn3k2Vh0XcSciYAlFNiP+SWn3AguEjxVTi3/mZHlnU3pIbKS4fMnBpPEk1rdl/lejaAoag4kggzpFjDTG8GV/ytepFntpP0AmHwlro7N0tTh5sTcR2protQUEg2jo4JlzAGwkKXIAnjQxAwneHaBNtjp4MFMlxRxPehYEtTD4Gb1WkiSJ8ENHkcdG9wmU5YwLQJjCNXd0SL9sYDAb0lgEAC6LHac4FxEV2N2Gc2F+wXlkh7PP/cUdoZYUh48cyhqqhubJqHqq2atZ8w9gmAEIktNVelqkZcJmDPeGCpz8huDaawb5sVzas4vZyYxYUpHi7MkX0SLO5bjFMxBgpWOTc5iXPWjRTK5k4St86K9vbgwRAfW6AbRzITCl1JXrPC8LmbCoSG1FIpm8OZOKknoywHlAQc/EuoGZbSpuIcVQdPISM/gGexoI80VMg6xPdXX71F3mSJSKNiCTlLPVEGsnAewTraLOUaoGVmRe1LQQqRru0wdW9Uuz82VjdvLzr2aRsWe6A2j6jrry3qTfQE8lVzj/OLFgymuBtJAuUw0knNXz8eHTEEtIhViK0SjgUYjsPraMwlGCQIkrqcqfSvLUe3vw6tHCrRl2ujxU2qVwBtUslq9SRYCfOYpagtZrX7StYOgFAoy0E5oZXiOIZOajkopytqorMJCxBe7do/CAHTGCc1V0Io5i8Xan2Q6VZXILoUDLBJu2qdGB+fyOYgbNG4EKsHR/rsGgrmD9XpGAgHW6Ey+pRC3PLXFwiLG1AYww4SQ0m3y2j9iuwSgyA020GtwqG9wpyHJWfaM42gMEv7KNk+gtxmre05gnojKE2oKcI8oaTASPrEkuSyGWVzFLhu7yEXerTsz1bqd80cNB5UHwSzi2vaNU4lEN96VJFGmsoUxDk7NnwMjuJ3EIFSMzeQoKLee/uxK/k0zlw7v69TvudVUrB6bTjKgGl35KVkI73m3zsVJ9HEWRSKuVsAx8pIUgMS3+kS+Vc26Lv6r8ie524dfk2LIEye4ZpKd1dmIVpwfLd7V8ICkNcWwaStPjAvbnybGAkYpPvCAlZvlRa8XTpKWWigTrMB/9dXJWuqe44KqRY7Clhco06203jPGvAlrVW1ixH/NPJT8JIA1MZmi7Cnhvpk4V+iPamw95JzT+FaF79q9cbNdy6vGoEIxEwS8/ttax0kY0D1HR8zuPCMO5CnuzWdUWScRlKbtV80JFZvaK7DzvUHmMmx8VTC3XgXohR00fU8MNgWphuY4shymxdhoQ7FHMcuBBoHnetrNVlCYtsbhgidWi/qHDq8GICIcuaafiVND/OJ0BfpheB7jtB8tF2hthbN0HFMBA8+GgFO/L7A3tPm1EN0r3pvDWNY6C3QPDsYlYGkOL/Vk8aFwhrqAKFNzgp4doWcEztPUzFFdzu3zIyTNtJHeahgNPHVHsVEYVvfUIzTDx3su5LX3jhx+GphDWlIkoYtNfgeAWvKsXW9oejpnW0xyyCMxjtQ1i4SzuXCtkWOsZr4rmUg0eVQFYxxPXMCnBe7SpQ2+MielIyGeFKa/nPD2WahQLCLrnYUiBOi4MZ99dd+KzLAWM9nHpUI+++89LrXioJREU/dqdJmiQ1jBbJQBxISk80k0Ern20UJxpFjJcamwuLKJpQkLUkTQzCWL/xiUGH8Pje3l0X+QT7ipWZT+7UEHLEXDBaqxqKGLCrynRwXB6N4gP708q4w4PFhczEtYSJ4lZKb2HR2TE8dXseI772h4Fj0JdbqrsBIZjoW6pVqnU3AtU5NyhkWVLBkbPcusM3De82USi686HSJOXNhXYH2HXKyPdsVX2hVrGhae9JFkbPgTtt7xjb7+jK3ehJPhjLIczwpgStNOPsSiObGa8eWg9Mg9p9IaNo/Iq7TC9HETMnksGQkwVGGlxHUjU9bdb+1gZda8WqU5FdekOfuNGQ+VLGclqeql9dGzKRJOe0Rh8QIs1QusKH6JlNV1b383e+rrX9YyvixKS+EvQKwy1WSRB9lk95lYX5NVSqcc/p7Jph5zE/135yZyxPljaqLH1ETfOTXRA3MJlOcRWOUQKs0S8DuzD6x0ND0J/nmcUN/UbVRyWN9x3KxxYr9MGv1hB/b/O07qu1fYPuygvs+PuNaR/TU9e0q3fnTu/c9x7lmcc2KwTnKqaWbCOV3lo1vDRVf0qD3QDrzfNpkZAr6ofhfNlfVMlHXdWSdTn32yXJTu+gixhkV+6hHyK/1pq9xaWNn1/Hlz2PhbuIK6ZF1cAyVqDAzQ8vu1mJ9gdTT9vHLRuSrz6S2KB9zKgT5b3dvFek5Oh35WE5Wv9ezptGk8W7rJs6I1eBqUdtQnkRR7eI3X08o6nkVMcK0Sla3jqH6QO/x/mlc7j6eUNi/rnfhdq2vKBjNirGRUhEvVn/1OoiF9QEbYVrnTVgh0jF56qiD4U5eppE8uXm7XTlqnpxS51ipPbfYHuHUfz/89nv97PP/3+LfO+b+byyVoeIvsWx/+u/f8X/vly84L9/xf+4cfHs///RF/T4J4NkoxIr8bLPPzzdcqcwtGa8vvv2bpTH5PM/2tifGPeFwvzeZfeROpeThQXCeKx+9UHczvNsCkBLvMqSpryy/vP4Z482bNLaHjSNXlnHxLPZ2CwVi1dC5yz9B9NJuDXQymjifpfEqHKeawijd5vX1Lqfswjwi6zjBPxoyrTu4CvKjxOppgFXF1bXp+nowwxTW31wx2NVgOHkdAl+kEFLd0mVvXbIi7bDQMdVssdAk0uRQrL0FtlFfb3FBqiICVPowtvoYechSxCSXOzHbc+FCmGGgyaLAoepVHjy7SNO9Vq40AGjtLs1hcl4nm4Vl8kcx6LXO3t1d0D/MBFMo1NTq/4AIiUwRiIR548vUVUvFZGxbGDZReF6fnprjt4fZxf3jc/HCwu703GA76xwFefUxe5TivfsWOqbmprakKU6P5a5rMaki7RqGEU5dG3a3p1mkEVSrnIvnbMl7crVGZyrmVL/DQ2FrVkacKfvDRZTy6AibA0OpwsZzVinuvzCJ0pFJ8N1Te6Cbk26Gk91ScoME2azZpNGSYtiHNKXlxV5xHeb6oKQYDbHf7n0IY4z4wLVs75JtXJYoOes5XaXKXbMbmKZj7auOXUiFJkE1s8tP2XjjYPXbuXELRYjqt7TrHh8CI4XG/v2tX43FF801aR8W6//axf/T38LB/FB4OdsOd7Q82CAzIt7e/P7N36aTNHiq+pocNaTEU6uoeJ70sP/7ivX6tFfzNIMzf2MgVbZdeSGfNS007dZ7xLM5v4ngWtCnHFtqzzAsAc7NdLaQit4xiPkZwnFO8gSJ/vTCSNnEwsbY0pwX2wluiOldqRHthhxm5UvHOQ9maXY57JLBAq9K0v9Xo2fFjBmznnkB7Kp0nE9wiAkqEi3gSncWTmhrkhtGyh+sagZALdoZ0nBHMleJ1zTO0qgUDz4bLzJV7bigLbxZJzg1Oo1lyDrKn2JZeQBrGHDO7ppDIGk7HViDgOb/N1yh92vy47VEaunywG0mP9ypt4U9oNhnztgg8W733gZPFGA12ZfnZZdU2RtEz+d1n/0P4TYmDIreVC3+1tDn3dTrMWahnrGp1S6YLBabrGfBq76fAVh3HVd/deVg4lEsjbtjibYWjrCb6abOZG1IkKUafnmUcXtGnd5FG36TDvcrVZ/K88zCZXhQfjqJp8eG1YBZqE3pHacEoUgsvl+AeesLpxNy22+aHTtv80GmbH97TNhXytC1H2mldPnbal48dDOTje3Cwx5T05IL+47jnOINmTlnbPUqVreE0HH2uUVDR3K00Xn1Ra4tvgQ2zGra13g2w1Y3PXzakGqQuXVCSigCZPXXnGJ7kXoROe/LOa+uWIyiDlyzgll/cHKXTeTKJa4tq7T/Hz+rhiD6qzkXXIoqwEAvnBBEa6nkjaDv9Vi8d1Vai7YB39Bpxys+QnWgZN/GfmgJlNgE659Pmr/OLar3uVZEUxPVGZz8NAJjIsIgXpXLeExw0NUZm80X9YxmXXEwjMeEMjqVYTUW4qhi+ZhZHi9EldR5NdaSZOgzpd5wzBK9lVq4JfpxxzktQlpU0hpWF2uuacQQr2tYnMym6a45nKBuMTlPc8OKpxTRTN3r6DnriHRUNwZ4OBMH6TrAltM9gC1lzpF9DTTDP8ims7+imYe/FGJwOPztUGOcc/OgG/OuZa3/hyNOrhlQvjcmkrhw12qhbl5HLu2dQlbXLFTNROjec6UvULX2DkmxktbovYae+Fdx7y1RNjQv3nbZjxBDRtHavjDFFsTmeorBWcMqObhi7YRX/dVBiXBl/9wq5ouJsDK2jomol2SBNQSvHi7d/D53VFmzxhKpLNFcJLM7kMrL2RN0VVJWdX7EtmJ3UjKPWKtSbQTvqZMgoAqVCQwQ2Su7nomEV0p3vr/LEnovzrj27JF2v1UAgPQ67wJCfaZf+PWl5ghhy4AOURrBsOMPckNGqFL/NzdXpNhyvVGVAPbC50SwW5f3kexIcLuIsXlxT1hHBO1yjGfwbYGH5IOV59I2sBBjlFMBhwAywAWi9kwlmPAGtSV6hze+CGGlP1k/TP6xicOQurOz0A6ItfvODOOkieUpORZU0e4JVuqcew8QSQ7JFnyViFZTNaNX/N2mGldpf1Nw9tpdOr3IvOIHWugCnSSaybgtMN0UblrOVC91/o7Th/qZ+IZPJFiQTat+0taaLKSZKm5qUEK+OEa/FrMdfwCLWchKs7R4oxhxrOCsDj9OsiRIfislE0Nw06edhesUH5Azd+A5NzcIt7FXtzzBDsp2ga+UPgzKUvAoDCkwPku7qqVNVOyhW1ZfkcWtL4w6VU3FPPDktuPIU6KqZWiw/zgXxVW2hrQYiWbkIRvMv7fCksCpo1dykfRXZgvd3cEurirnUbqoNtQfWq9IeWLWOG1KXIFUnjtDBWpQKsCbGqyGKNSi6b5b3Ov9cdwI9xn88xn88xn/87/3Dba3JFiaVOwPTPNu6hrVmfseJxr5VJMjq+I+X7Xa75cz/l+3nncf4jz/ir1qtBp/o+pxA3TUCqn3tUzKkw7qHd0PKvlzZll8xMGMSk06XnnvqZpS+Oc5Gi+QMTxzNKhvbs4ACNIJBFvwCit1l0H4V3OI/8AssPrs6rvlc/CgepRezhDZPojw4HkWTeANU0ss8n2fdra1ocZtcN9PFxVZ0lm11YN1otts/dn6sVIZmDMSv0W0wEiEcC7DdKbszmkz6Pl/M5yqAXoAKsTxD9+TWRZpeTOJNtJzQ47XF9wzpS7LiRaWCO4vLbGt4sHvQrTwN8L6USRYs56BSUQI3yseaTsEwTrAhVlAkZkjKJmUcC0SC2VQm/qREjzfRYixqE1nSyVgNA8d/ZE1o9Bf+GsxJaWY7zuo9tkMAnr9+cQv/U4ZrthqnmDKOpAB6Tl/dwqDg8+ed2+cdNOfpdltoY4gKJACvUSAGUIIzZNNA7cf5ZvuqHkzvghHMJ2h9g+BuMAAGj3374Yfmj41gA1vfoN8/Nl/gdSebbSYMpa7DocIW34Meh8d77vBsxBgvh2KU3x1+ZCY5Pt7D63WWMwOlOWjhMnAG0DsAVXDAntObLYUsAow38+WMbKDzJejt0GJle3Q1S28m8ZguvspwOJGP5hHmaIuW+WUquJOZCJsgtkKkxGhgfjnM8vhnqDuAZm4BJaQKRSzl6VU847FQGcYPL5NJ8Es0u9jIfBw4WY6SMfaHJPOmkMxBs9kMaMMBc/qBglshqy4FAsXJLJ1nW/CRLaeYBRAQOaYZGxhsCyb7HRmA2Zzu9Dq7C7Zn40X8a/BztEAfzp0fnSvxdmuazN4dDgH2m5hCvigP7ShmehBmwNEXiHcevF9eXACtziN4b8sJoBvnyDyfpDcEqlJ5j/lNcSJcxORkANS2gp10fregcKdOq9MKjjDh4i/4G0y8CkYzmWnlif0p/2GaTlQc2Txa5DAd+C0eyrLeLuJ5HOUVb8Z5XgxnMwpSm7lPnavM3uoE+Cr8rRmdjfCdyOqKrt2zEabieRK8RWyUYBVXUGec8nrGl3XNjPwb0Iksrt3aNqlxB9Vtw2mkOcAzdHjJuM9WDW5dq5qbZGogNHlUWrym9iuVwYftd/39/jDc7b/d/rg3DD/0t/fxgFmr+eL1y0YAHy9f0UfrVb1Y+ni4y4U7nR+xVKfzgj9e1it5GnYICUzKKigAJhVRZLxI5+SIR8z4B14fxfeV4cn5ZkNFzXUpIEjePqtDAnfxyjbez6kd5+noMsI922A3nuP9SjjRhXOkdoMZJvmWNrKAp7hfS7slsOzhVVrjJQw5HX/DpMHiEoAks5OD8ndsdSedzYAheP4PRC5PjvLok6wGmbOPARJxPgpmcY6JPUGeXKY3GNnHxi6F9sFEoKhE3gojjwqII8roDM1tUA9FY7StFxmJoukqsZRJSRGImDkyi/G+qlxIOpAt1NZxHGOCBBDouOh1feIgV5N3C2zsrSTLlqBCvvjxxRP6ilnKodHNl887P756/ePLVyS3BhvXMUZgct+pKRiF2QUlt4b+TaI7FLe4PC8ulqRnYE9RfAYbYzl8G8GCczyjvAUS3Fo0jrDXDIiohNCW4hLijWwJa8V1hPl4c1iGxBDJxsRImjmRJaeRr7Upb3RTnFbxTqqrOFYX6uGN5gpKRdykPkcWr9026SveEVYPngW1dgPPfcHj2TiZkuuXEogDL/AKiUOJmbNluuoG4fIrBkp1dnHYr4GHMiMNaqhyHGuMngnphSVq1L7MMHzbpE+VXfjWyu1tQWzCuKeLsEYIngFHLuQBY7X9A7WT65pqF3tmgah4tkt4qcTBPMSZDgL2A8W9fsUUfvAcNgfel+5IDqGZelzHpkqcebPeG6nK+/6anwyuUI3CpEC1T7R5WzzhY4lBG6IZR0C3MgpyDt7sFyjp6eB8Es3iYtAt1F7Rp8toct6WIYkEYKvj9BiLQAkqadXr4K4y1UGt3npNFQe4qgDiA7HA7YP46oxrVLIRROeoxzl+VKr3RtR7g+qnUalTX4fO5CBU2evplyI1QsEIA3Ovsy0jRQb7HGIIs7mJ63BysUyX1g4zlO7I0m9k6faK0nYSfWyMHNmduoWEnkNyxD9M5uuMeDILz2EdAv0Xl5oEbBD9QAdnu4+iUR6SdO1BE+/6ex95bvRazfUCtk2QGJBh/qTMUeqn5hYbN+Qm50lJRc4SMGozQ+wBw0SYr7q82w4rRXS4WvXYnczno44F2QFmk88jCLjyLi/HNXyyFoveSiaCntWMc+jqOSDsfY4teF9AR9aqoBY5yWnbuTgUsQ6/wcrF2eEuQWPJeq8bwW9X1+FZEmUcRYu/wwztfMlqeT4LBXM1cI/x1/BBrKYiu6hBkeWNvmvWgl8hLqk9Wli3tjxlngT7B8N+QJgFYMnAnAxuQHO4WaR4PfEMjTylmIG6llHqdczrjkFQYKUs6ciI6Q7g9Rzs1WtpPDpZYaitniIIMrhC9enTYLPVfOnEFAItLWYkalPx4HkjICpLcrtcLsls86N67Abzwzh4W/KU84BVj9fi9TeNANafHdInSFnRu6nUX9l14FK84hZL1LjO84Yz/gjGzK9HD+tN4J7pMgdDo4EJn6AWCNkXuiu/NfBI/zWNxTXd5oqfbfHZOSX+wL0+FtXo+Zrj/UDz+V1QAx5ADY0O5rAmhgonXQ6sRw/pjNrgb8G/BFd8j/U8BUtvEzDabNfrMo0FMYJbCz+aWXqeY/AAXqqyaawMoow9yDSuRvM42ekZNH9dN9oHOnRcou54hAQOqFd6qJFeKULeoAJmiY/15EcjmE7mIeWI6b1o3itLlBixhEoxQEApWFy4uNjh5br62R5+QSXjIRIJitOSpCDVirNHjJ0WsHaYmS1KDaIoMsgvBiXkF5MI6pspYO1Zz/KvGyj7i+MItPY9Ru27gTcdAa9MJrjBTiEqwiA+izF0kI01aXviRQw+zTiitDrKAlAP69oYwyI/oS1GB3ZQQRQRKz46d1bQGflHLNm8AqAWyxJTsZZ7EmyC0gz1K0OL6NFouAqUDd1kJfVNcOWDFv5bGdOnLQHFLzXNXjDl6vW1KgKeul7HrleYrIeoU/enZ/HYZ5wJzz0sdFQuoILkm2DPN6yNExCM+EA4l++zujD6kk7ekJtorvL29NqvMC3cIhnH4j2l+QvRmZD1QIjH2DQSvvfDq9drniQUbZHWLRxRNfnQjNUwMsHqgnNPKiUDwVD6tXQN461HZSGxLFvH0J5No2X4Xae1zG0ACz4L2kVwdxa4lgOuVQauZYPjIxIbS3J/c+kuxSCij4Xd/eKOCIwox2Y/f4HZRP35/GVDxffodoxF+s74bobVUgoTZhfzsoZbuS5SXSdFrh5K+dXRTcxBnJfkFLYbNn5VyhQidMF0MD8UM6LBhhgjuJjFfK9ab26kS2Zi9LzcUEifAtOtEMNpe4FxXZCIeOIYKStm08AFh/ip86jNj9B6wX7A82Is4LTJiivfGcs3zocYvkh59LLfFnmt0wy2gpkTvhhPfPgatroHabut82QCLbU9mWibuN5xIbzWLqyt07TtXvi2ra+n4O40gveN4BdDxzWW3reDf//QDyZpeoX7lBgSfkuTD1l3lALu6O4xzAdxleR79FdacwEHGqfpL8U3qM3+px0ZWx3M0I1HYVncWO3z+y9PP//ypU7XFM42chHYz/t7tc9uY1DYbeVLvVkt1x/t1ap5PsETB7Nap6CTAlVO8J5IMCBBuJ96Vit3sQoHO8dfsWBBrW+2QOHvxwXqf+QC5Vksvu8qVXE9Y6y+vnphDGw8DbkX8KLjG3ALpPUDiUrEVjBstEDsCFfDcfzbEnXvaGKbJ76l0NSFzbXwB2MJVA2qq0Jhqmijzgl8Rce2huq8BBSO4r2PgIBxI0WjBEsTtzI8nys82w2JXPufFDnXO/6VeJpJQ3mYtWsWgH13NekhvlJk2lIvhfvi960+YvmhcIejeLDrXXmMYIhNDgg5oDtlg6N4kw3a82REkdnfbQlCkUSogrXabrVazqLUYLu+1+543CTa9wCvH+6JwdKx7Y7Rj/j4CGaTuU7iG/hc4aXRtZJRFsZy/ZZNlzhr5G3QwliXpbMkDm+T7HLZazeh9csb0an2A93NgqjCaBC/isWM/QxOQi6pjxk21XfgN6sw2gSo+CUgLmejO2Fa8xXgFMnlpCo2O4rZa8zfViSJST9Pwn9mLCoBYBzdqnhCSTKl/GJxZnFi83Nr3VWs6pETPfVtdZbyFXj/t+K8yrg1EG6WG52jSRZyTBmJ1MNoAbMG002b13q3yZut23U99GmmCLMKhonks5UQYeqKfNM8ie23OJ3Fa/zqbHnIyYd0kN+drWQxIXGVEV8NS2mAwaJ0A3RwPOhrXd5kcnEy7SeRTQaxwB8etkEU7qWNAPeUAJXSmnNkLGejUJrJdgvIT+Nes9XxJSDZEG1otZUSjUjs52kyy52XSo3lqixG617grCgDucI9cXzRAaFGom5ONIuSv494fyTVHMJ8a5L8Xm76jkx0L6t8IxYpyhfPBmBPLfdGMq85Rimd3NIBL3FS8ZbOrhGBJhitChooOpjstV9oKfVTFAHungT8O4ruggWoXg5qHPbDiLFutof5m+xD5rw1VVgnLFlesg2jNSL1bc29mYpP19Ek8+7dSEqovSsg50lyaus/6mvxbLeRQ1tQ0x1KrG1vpfhWsyfBDio7oLrGvF/txktY+8YODYWeVBdX+Cot6qegtWqrxzMp1NromRSe4moZNIo7m3Hz+UQk82a1T2zam5lRzOdCM5+Wxuqy65Hp4LgcbQSl87Fkeq+ASksEOyXNNHcel/Csibg3yZsYzXJslJmz5Qi4YlOe3c+1QZYVlB0GHVzQ919YCPwKBZMLoEysqD5LBclDmuklabE/b6gh3mgEG4o9NoybhzDRz0gx76r82sTXqh6eDynUtBi6QdlU8Qhtmk56GxvutVVrWgzO5LEthq+aQa75rGwMaUdLUywUuRzojgpWJ+gLU4VpKR0NhmdbO7RPWqcew1vruZb7Vw2P0ojVk2Z8O8ew1TcYGUHREULqT2KzGp94oeh6ecJCns2wvcw6uu5EV4eOn1KwAdh9lcKNSlLD/UlmXrAU28LFDNbOq9a3n7k671NHTzhRlJevVBvP5ACc2rPTRe9bI+Jr7jt03NM5167zw654WEwoIOTfsXbVziZXal+NdYFiE1CmsC+hFkPrDV7KYc4F/3mLky7IP2At+tLuFl1HXKDUrUXTMaRUN8KVwnPSfELUMx4Us0ytnLM6ItAVCTZ1DFQsLEwEGpXydq1fPoei9qZZV8PhWYWpXF3R2+GmHqMC8lYcoTtCxZoujDuU8xDdIOhc622M5suNhozCC9PZ5M699IUyfvZa5mhvELyNgCLKZYtOOkETE/3jRFQ9tcDpK+++DqZR3wacxxGY7QsXavDkyROaB2Agp3bmpbNfbdhVAaJ66rMO0JWL+40Ih0ekSX8bzjof3/A+oZUWSuXgEUkeoG1/miLRmyu+GyxDl1etytvhzWrJ7cx4x+dVU6Rp1aUbQbXqTaiDCpLdgDwYXdoEBW7PlsXERulkHFL7lXuw0k348ZJ0O7miHGKelEsGQ8jCFR9tdUk/iZFZULMhTrnCeNMNvCHV+DlfxDBtLpI844e+G2g99EDApksL/e1CxxPAcRmllB+sLOB12C+KwJ8Eb8UhWHZz4oKeBwM+ikOHPxN4n6cBbU+xS53atR3p5t9BIxiovfeC781A1Ak9VanicExUhOQBKyUIzhN3cIXb7oYeyh4cBqwuW1Wv+bmPCMOUzq78VxxA4SDWG9Z42oVtdZ5pUW4c/aIKpBHJM7LxuBB5bI4Yjn0ymcTMD1p6+ieCEAaiEl8ehiNxmaagdfLhzdFEHYKd0aErsDM3/Bmarm3V7JrWxS5GKdDXTvdUK2i+ukygUFGzdt0ICpaez9V6V/JcHQC5caMC2WK7K7ms2rjJtA5TuIl3QoW167K7l5/12jbj3I7AGvckWmNy98r/+kdHB0elbz1kFyCZHccpSUORuBGnaPfzl64hQjC1cVbsouEUQrHTFKfLvKTgqV53d+73MA3SX8bBFv5DjoasufEXcR+1utnaBKau7QZ9rCIsMnv0ce9uetYI+DOcoZftkm3Mm2SMGkFhp+dJcBRz4D1y6sUC1PD0HAFwPgI17TKed6hi4MyjGaaRawbb42guT+ULwF+VamALdNSzrVbr9evn4/GrH9ujV8+jV6+ft3542X756vkPL16/evX8ZedV/LrdHsUxJfL4NbrdosPY5Pdrzu+e7HU6HCEwg3mIZMCFXtFEWGptoX+KF8KNIn4RIWQlnIo0KcXPllZqVQObvaDN8C5At4JV0bptlaLEcFAN8PWnapLVzYqIrIKxtWVvAAjmOaKRH3vGSYwMvO1ilu6Uv6IjnbbPLkkSduknMITl3mTcJC+79LI5SaDsoxb9UmsFrBOyM+rbDRm06jyCOozQ8QF926QD4/N0gpk7jXciU33NQouV5d7GWTIh78HGfXgaSHQYj7qJOwEH001MH3nmgCHYwruUj2wRLs+Y03sxkZGLcR0Pk5mKDOrVOni6vN15XS9ubpvbyC3P1nLBeQzP2p795vt3h18WrimR6q3e9a+st6/o7tJb+4llG/Ll+++Gl5muZ9FxfaKb5qZQj7ccHKIUHOyKhD4vNL9xXdHe3XiNi+GXFrkZavb+fDyHnsWbr+om3dU3d4SsX6Y4N4apYvIZ68mKyxDbyXL+yGX/1FzG1xH94UzWuYfJREKPFKReNA5t9z6fCgPSxhFvVkCXG8GZ0kJ2lnnwf2Acs1yo7zJdiMrwM8V3mAcHNO8gyTcyTutwDouvKiPyHuE566NfBOQPcX6ZjnUuGqmWzOMU88Jmo+Z5tmzG4+XW//fr2XJxFS3G+dYcVZRZTtZUtkVdwTwWojvN+fjc8MwD8UfjcythCXQonc5hYcG8sWAAYYYjrhuMltMlrGXJNSWeAO48W9ISLjOsuJ6hWrsZPONg83gBrYDGaEaegzoITzoioQNYNDUkMViWERChg17HfFxHs5af/xRgYgT5vOtopVUqg9k20kXM55g6WJCH5ARH7BTJLnczrDFuBtWSG2yrmGDI6izomCJ76zS6w9OiyWyULhYxqJLVhmAuzpXECWiYp2oWhT8xALzO6iKeUWZvyvHDtmEUqFEDnkkoJYiFgrxhjIHl2qqk3MDo7AGLbmf3LTkX8JkYPxNI04DwLs6D5XwusnpM0hvMHTw+dxNtT+TmIrJMDQcJaY5jiAOiii2tYmduMaPdj9w5SiA1mcjjl0Q8QWIevEkjWJ42uKOkcKNCBfQ1QJ10JmjYd5ab7VPdNZEIQxAxrCHzTDgzPH5dUv4OC6NMExApoNR7IqWHjKin4iXsasQMYM70cbGCKQFNqSMIwnWgGgTAc5CiGDImBY8LAWZjWEMef+rMK7dgNB6HNIncfeDpHNuBQhh4JiUTGf7cNO03u9BGWA/gJbNeRBmxe2cFp7DIH8KCtVyeUlQg7pq2Mcywt9mBj7Nep6mEKyY76Qa1oahDmYS8H/Vg8yeRrIrle7VafQtclYlJgSclhkUGGy+imxmzWeQMom/SUL6xaz174/NzzCF1HQMPG6CgyTIQQReHqvuP/8QPWKw+73+p/Wce3+afkR5fYG2kH0CTL/9Pp/4PLU5Eq+kyzzBiXIBhwfYPIDs3z2sMtH9H+GFNcXsNkuEML6fIuBdTXlyWmchxJASRFCOcB0a2SrmOCMwZ3ldIBrXAIAr+cxL/Fhh94Adn/+B5iMnzug4LdfGSx9kmaDPwk1Nz/YPFJQ/RP/T5TwDYJYRIvqfnZfLMCJ8fcwU1/TBDTiRl933VI9EaLBLT5RSWvByWaCaDvmZclIlu/WX6t26q959++im4UUZXPJ3ndzWw2F7WrRLetal2U7eii8UEe6Cy8pg69p/07/+K/M/PXxTzP3ce8z//EX+d1yL/c/uH169f/9B6/rLV/PHFj69edX54nNP/a/I/09U0vHX77a//vif/8wt8+6f2y86LH+DvefsHvP8b/nvM//xH/JmJU79B8lN1g7fIJ9408onLXKuGT7dhut6km2Q5u1lE81BvXNDdirG8cUHo7nYsorqNAfdc7JDLKvF1lTfA+Y4NNEOLlU9EydMCFPt+Dre4HRNV1Xs/a7VpFF+7YbNOxbxZ7n6CFK9ZU37EQFOczncTSJFOFrOE6kYtfz3YEovaVXxXLwm06LLmKm9aEndSGaRRF3pIBkhm5/EiRJcHmIfLSbSgzYKacQQFjPVogeGal+rbjT5YN8D6rKOny8UoDt7f/iJO/tI+hzDHxPk+Y7MIuFi5EptGBlDz8MvfemaYW5GcZll5fzHDv44F4QTG8hwL2Zc12SF0ZFhPhH4+AgbCe1rMu/wmyTSRt0+b7T59GrSaQvk/J4t0zJf8cXx3uyFqPrOuSnQ6+hexEVZZGd7B22Z2bgzcm6O6VhQKZgeiyy9rl7G9MVWTW7D0vO6mKrbIZNDnxrmTdZTS6bboLOOtxUl6UcOUWCLyvh1vtjtY2yS/c95BE1ld/kdgGwT1MtgM9DA9o2c3+tkNdAU7KWCKOalBruKaHc4SJjLLaX7c1NuXzMC0Cy74KBS4hWhp4qyXJBSkFZeMaQyseYtMIyjeoB88HHISii10cxbq7XSeV3LurZ6NvCML8+1kZ+/49BnNQN+EQyRGkyX1tdO+bbfQ49J+dfvanIkiKwE1L0OFej3xmNsWj4uB21RJAhIgKMvun3vB84ASqGuweAD+z5i5132+2aYXZlv4bMXg2rcdGbda+qjAmYG7jsP4vMo49D57CPBFUl2+tejwpeqEVnJddXCQf4qNfLOA2BLW7+XOvniPeW75G3oeyoS2cTw8rxmQVaiBYD41r6yfYorXS/Gyt9RVY+2GB8tGYSAZeOl2u92gvd2u/UG6kA5i5Q3EVf0yjtDTvnz1LBkt4f+qfh5NkotZCFN8Fi/kQeq1yLFq594kkYVf8NRGsIxaQoRwlIW1zW8yVsNEyN7mV7NYAJHT+M/3TePiBXPOHDn0zScRKXceJZN43A0++9r+go27M26tySRkiwAnZCeFKVOEHWbe5xieRYz3rwq1uCa/NAydywxjlhLPOM9qOBZ/ePV6czfAG+g/JcNAwpJqjRHdh7dncF56qeNt/uvhB6NNWCgugS6UGlx6ZrnDBB4jkUA5G9G5cSgOq5PYTRuQKh+hphiDfjjpUuyu3GzERmQO6gbtL9pn0GmbFs9szKXT95x31TD7O6hM5k00FJnPLuWnsl98mOYpXuMh03dvIW2EUnRN2uVZm2otBGzuFZUN2m1YvbkyHWqLqADKQ6LhWbsh3Ou5vhNzmmb55G5zOSOPNvWJDw002+0t+kmgRuk8wQtTzFG0ggO1Om+EpttKiM0STrB6dTRfVn3B6g5ncuBgMLyb82S5B4M1GjXFDkr8++w0Q9fFkxQyzNkM3GNmwtIkTIRam10loHyNQ9WUeD5NMopHNMuKmRea59jx1ANXiAgOjmEoDmCdAWvRZdYnxiELislUapJcpshYEfJQGy6GRJoB8ZGti0hUrFtaJQS20WbiiXNE2OqzutlWYVJfddWkQl1eMl3SPmhKVYVjlUxSFnIKQIkwPtFATguC2cVgtepYjHuVVRuem3LdxotlFF8VA3nXL3trl3WJXWSxzwXYQkMLiTrVboA3KNdoMATBiuhURcesKqUEL6+Payze2+mNMcBFvZxGHqj3Vrr1VHIG5ovFgN+GxfTsl7OjfBAACBDEmMeltOOSxixfb2Dd3nzbwf2ycrZ7gHBQuUJKV2fRKgmmqwjJ+wTvF6HVFm9hyNlnchnRlVBy+EEJwQW9Ia7JCFrNJthmkVivubQARmudUHtotxsW7l9iELGT5IyiUHAbmwPL6e5qIeCPB/2GWpkbGpYyvQK9vuKC3lSODVNSK7eSEKGFIy6jCW7x9oxKVloQfOuc/cmK535Macp1TjB6WRV2vIHcZonML8JalcjGu0BQrbrfRbNiEVBHLau/txFvGzYZpZYE5MEhLSmGo1ugNsbgk08R+DHGO8LO7lhHtRRB0jfFwg5a32pEnbWe+uZb5uUE6dSDA6nX2mo0IcHxHwIPQx8FBZNVy0yhRDz9IZrjg1bzKbo3TK2USPSUFmUo0LYKEHGe/lF8j+it5HtzTKGj5jQQdX3TwG2kfU8jzBEF+G0XvjtTCkMuzIsenTBjiVh/OD8YNDPgYNgggXcWqzLNs1QUL+LflnQXn6lcVNWRdMMvYKhw5kP/sTWziBi1FiUKxxsTysu01yrUXlWIhs96/KViXDEfGh0Wl72rJ5t4a4aksPIauBXXdw0YexyJtKg5Ygez08/wPo5JnMd/VZfTK0yUce16B4T9hZeVO2gVfASCYcwuBX8L2i9ePsS3cQB2XvDZhfNFiySNqrgZDExEYHou+VcH/6ryQeJRkAkLVfQWoEdh841e/M2+0NdoOaYtB5NHlQGIOle+cG1JQ7mpMjri+q+Qndl8q73bNbOWmCwltfitVUHqioWyWom0yhdUfKhSeGaUlyphgsdhEV8obzjozDK/zqchOz9YAMRZeRUhKbAKFw7R2RCCeAkFCWiFCWn+VfHa3KWnuqgqRNAKUpcKKZv6ypeGxwMABB4QMGSBYBXt8CoiJkZdzhBSza0ZXzcFhAi41pyN66BSK9EvpVjdns3daoP50xQZYrgL8dxvk4X0NFEjfOxRVcgQmK5+0n15ann8qB3h75O+GEr/cxUlU6BVTebDoQQsdAkhZl0POSFLGMI3fBiGFbUOi3JNvO22VuUcL1WykzaNfGIyiE+048kSRAdM2Kl8Hs3CdJlXrdXrvoRAKzL3NEXuHrGo2xhjHoBvgG8y+2PQVdlvJc4iWxLfKlfsQGl+ojUR8fCKkTJo6g1rKMkRJVvyZ4iC1lrtb0lCmc32SFyYOJhdR4sEyvHR1oUvue1/xIt0U01PWGjUbYsRV/qrnLyw+vCcYlUa57dwE9PG38qbgM7SPAdpBssNHV1q/9h5QJrWcXozK15iZYMUt2Y52UCMi+HEnUAu7OXcguwCLYVcNlsUwmqkyya4hED5BEXF5VxUqz/gmkmVXWcpLofBK+UUHnxJjOSMs2UyGZuHlde5C87KjyVSDMEzkT+Gvo3OLxpiU/xuvZHVaQrQpj6/aH442O3vNQ+P+sOj7cF+eLg9fG8sBbxVEo4u04Q8zZ4aO+8PBjt9N/15xqfKrCo7B8fh3vbf+0dOci+8p9sst9/f+blYhDZHRLlh/3hIxcK3/e2hkzJ+FoorM3u4FDt8l8Xh9Tno/6MIfe5pOqkhvMNPMK2an94eHh3sbNeLVVhBMVMKFyrvQc29cOdg/3hwPOzv7/zdAyZPFqFIAMHqdQHKcHAU7gKAwd7e9nBwsO8BwoaMyv5VK2bS9GOMZnEZIp7sQnxRapzlwENCnIFeBaaZCjUxsIbhCAf7n7aPBtv7w/DNXn9/1zjqIjQKPiNl7F2FfLoEU7XifcRSa6mqFKSKI4DT9o/fHhx96B+Fw78f9s00mhQqp6eHyqtLP3BdU1AwQefONsDY5lRvLRuGk3rXX//ToP+LW5szZAEIJA1PxpNy3E/tEVNnUrHGYP/w4xDa+Y9+SJPLdnvqA5hOnw76DWe3gQ6YOpSxy9CpU6vfTmPGSVijueHRYLcfIoZ2cefkqq6xe3RwSFLFU95X9ODj0C7pnG/VxbeHw5CqHG0P+w3XENM8rLaXSRhKA01tggkdoCDrekGVrnaZxXnVk65W7NqqhFtGqi1PEqjqnkh/Yew+G6mgaBf18xfF+QYwJ7+kD03VQx+eJd2/fw/en64Fu23mFVuxL8Q9Lzr+B4bWg9oMb9cXt+oNUikz5K+ek6JVOlolqy7iKbkdaf5sgyjCk7u/vP+4+WH76LhZLcHXS1uxHfm5OkOphMGaX9zQOzdO7eMM1t45GW+Bd53smsPsSTFjYWAjW8g3u15STK1EF5NjqrWyUQC5QrPTEEXW1xKl3ammlTzn8un22MGmtCLfHyWs4owPYNV8KBpVPCgK7dGTutLQDzxzSa+EQkmHjpQq/WVd8kD7GsqsBLMOnVYDWEW1FRBKmM0vS9bkvhUiprT1+xjTiYyNZwAhFfdKgJXkyU4uy6DvOKYo1JXX+whTo2yyGS1aE63hA2Kxg1HTX5rNrcZ9VCt26GFjruqXyReri6/84mQVtLWG0GOpiSyfZsZP0IGScaYTgsa9lh3Xjc9wKfUkaNUBfLRDfVvnYD0nSTMpUmBozulGerVSFnni1k0J7NXrVwyeKanMKsUUaMJliWaTzHOirAYDXycPXxZ/NaQGK1W2Z56NNkco1wyIzsbpJAtlpLqz2NS4tEsNz7yDdduV5oVC6MyyChYspvurlJpRNGy+1IQ/x/Gc3DgqFhA1IBmBnVzM+A4a3MOMb9GD0m9hTrkkv2uWpKnVFGvY44T/2sSKlsjQn6vmCFa71oB+KeU176rIsTBS/JpjXVgqy4fcBnI2K4IwGMdurQgI+thczmmr8rM3dKdqQyCXv/mgcV8tojW66MvWnprZmZIAoqoSeJwuVMLzyMFaSWqUUjm+mtLEmkWkvCE1K3kL9xJuNYMZ7y0JeFtfpWTp/OBeV0MhZbb0QOC5DbqACg+wUD6pUiDOEZbfza52RxGLYJPxwhhx8+0zge5Tp9HK1whHSTzDFQamX3QOuFa9ubStlsQzA7K4NgCjTZMRJ6PQjkha9GgfruYkjy4k8pQJR3So7EOCcg0LrDQe92Gt1Fekwxbm5MqE2HyDhUEAq1LJXRUagveIonvK0p+5elX26sJZyhXnKb8CeuHApI6Na8igJ6gC00x7vUbLBeXN7RWTl9rZlZ0zjatzLMtgHAx/WiMxNRJAi0oiAEHwJJsVvXjWC9prZ2VW4WmysyiuxPcTeikCFHEyGsGsnrzPdiWR5daOnLEJX8TUr5x5O3aP1ykQDqdAhBP08P5XAQi+1/0eCnMmNFz2qLh+CnsG4s48zOFZvHZm+sJE9HnY1ptZa88qGh2OMSpnwFUHdl3m/uLeNAj0MGaKaI/zDo5yvjx0/UEEBARZVf7WMidipRKGwjcdDsnxroJUqsaBc9BDzOPn+r04gy7ei1+NijyTrBMk1GhPSpny/p0rJ1VjcXvMuvxvBSCxBeb2zTiKJYhopHam1ug0j27QeG2f3uYEhY95MB7z//w35v9pvyzm/2k/5v/5I/7az0X+HzAyHsXA/74/tFLjLEsXW+rbN08BtDL/T6fVevnKnf/PX7Xaj/l//sD8P6PsWub2QdVdfv81S1XOn0l6cYFX6YqfaSa/cSpH+YucfBOVKAhES0X+AH1mfkeJhOYrcg2ptImgB0JZ/PmVyYj47C77t5d4aymXj6ZzkadomSeTrEm3sMqX29egg13EH/CZUwg02EwWO2qH0+3DMAbVWGiIhzvbNXYbyaQYqNrRvVhJntAVgIt0OeeAgxc6UO7AdJQeLtKLBUxCPMK8E2O6gWAbswBM0TarXaEDAZXifmur3xZ+07pKj8G7O4iDvseBffcyBXjg5K0QV/JhlfDsTiJ7J6HInAFuR86Ma7DV9dsjQtdIToOIKogq94wNyzyloszttyKuEeDXXNRO5Jfi7S+MAIbHMCSFPibu1bRnlJuYwLJWqK3Svpg48CvZnriRgh1Nqk2zvPYlEeuBfBldCSCZ3Fzh9ltis6UtElHgWfrRpfAvTNKMbj9cTjVEASbYtBGoN+fpTa1Tb2LhNt+cK0qibc9NizaoYUyDY48EB5+OM80ifvLV+YI6sPRmFzXLkkB8GwiiYSOnbnIAi4atGA6rR/eoM2N4H2vVzGmUOosDKjUbh9PoNiRAwooSkY9qwtGECjT4ABMRp2dZvLiOxXXg8mZtcbXLWZpf0oHH6DpKJhhPIrIgyLCL4DLKFK9vziM6OnKO9ztnvNUBQuWO3QtAIL58E6bREqRlOhUpafgx4pOOgIMpnwKe+XhHvcLoNvq5HS9AWGBmA7xWyahFuzQV6exhAarnXySlSEP7ajcHu9TTd4e7NHhx1gx2FvBlU93Mrqph7DDuVyaUKR4PjKSqJzw8mUwVhpYnUWwRg1QjMtrpEL5aTiXnZpm/GGyxKrXS4c8fuBrfgCWCoMcJ3rCDBwrO7oL9jx/Cwf7xcHt/py/MY2RB0a+e2erWltFsRbIdHqPwTh4NxppEZoIolhLRZFIzIDXj38yfIj1PfXU6FOpqugA7DsdAjbPKfeIOGLK0zPGWXCzTZSa9y/LKxzLJ9qDlgWXcphRyZdX8pDJWGJ6RPUusKoxOauo2elcO1IWwYrHIpVAskrAR60jrq5AT1NJLH9FlBkKHb3MvgOnYkPT17qBHJDojB9fWUn8lGKQv+oR6XBcDbhuUk3oU9wgf/m64jB64MmNxEouqaMc9mh9lVyKqNNMrNPIw3SlfKV5z1qM6tF55LnEjaihALMfx8kOq27zIa050Aot48msWdxMlL2vEKJ89tL6cZb8t4/i/cI2rN/O0Jos2iaB2G/UyZJUOoLDYEohyInvayqsbjXnrZ57ulishFc00IQUrc+KPZIy9kKqM0QkJO5TUN6qqfrX0NAslP9oVDdIL4aULN6PZnQBDwuwBmZuqnwDK5lulG6AavLMN68coTnBNjmaO6OKM9bPUXrYLZxUJOT05vZJMUgt4wqSJxRp1l0T4t+XSpmS0ob5WWlgQmlm8WOUDKU/I8uqRyQhtNZJCLzTAtpyBlSkArSkg+7bpb0amP9O6o7zFS4EVSmjNPF/hNGgRrqKnCuqYLpvVLSqZoyT5UvNTgZPdUZA8cY8WXiuEhYemRiz/nq5u2xrQSlEoWJyhu/SVXEEAvENq8fSmS4MVnOIdZwzsZJZQuo45o2Eam/Q+L5SnSW/MdL75mXnG6gMqMG7lU2GLVIp7fyYcVhSJoTCtKa/UeZpHE1M+UeFn4uSGqffLgcUChpHjKFdei4YaESZNGaEbNgoNozG2e9gaKEZf1cywpKLJo5UoI5Pmuzdb+4OjILpYxDFp5fPJMgvg8TN8LC5pDsxDMbh2D+GdyMzqJrU1rCBMgrlSjWarhhNemU0Ic5uO8XE8biAQ3YKWZcpbGU5n9rqYlHCVKmnVlIaD93HHSlV4cQbUTWDpzBOUESemkOBqJ8lsHN+eSj2VFUV6plWe5/VTCS6cESAOjKnBA2AxeKRlgZxdckBKBFOr+RJqIgDFTZg1JNHM5ajODDRZhBqwQAK79lS2V0RE8LNuELsgPQHPTJDiocoCy9SlTJ5EK5ZqvlTLRrYvOuvAF1HOFzEUWMjcguMoj7IY7wHqdNtBlM3pWivBk74Mx/7sxZSoUqMj8x0X8xmbhf4ik+IWwmBVDmOzeCGHcUl+YEoMzABUYmJKpIuXjDXRw2OnO/765MCUYdXKYw3EoatMKdBRboub4yTyBH+H/MBCrLkRok78oj09C1JuhTMnsOY+5qcUV+3BQLc0/+GFWsLfoqQjnrWT+o6ag0IQCsfNUOfsAWE+ZT+HvMpJms36hl9OP8mij8qfY/IAgoSYZVK8orsIbGrAhBwrSlaLu8UmqNohPlokiwuWOXz3+e1zhe8MKX+WLheXaUoXaefphFJoBRnIkUmQ8V1T0yRbxBfoMY/0rWtfL+QRL+sAp0+k821XWVVxshUxnWTOAXOfo6K8HRQdTBnB1kJLNK5bLhGnNuet5Z1ALawoYVE+MnPQwqG+5+o7oKDxMf3Ba0t8AcgR/O5TH3aiJamY6wVA4vbUQcZaDqT/t2Kvyl5sVy/V9yzXTnzS+ku3cdBxlYaMNFRSBdcv8T1X36U8z4Q3ffSg8RFYOePjPPWNj1bOen5IT72QrDVbSRZ1R4AbD/xSXEtX06XqQtrTE+1luZULJnnFago9NQ6AUBEIKHjnqPLimhGCKpSMYu16y9P5lQYE0rmn27S2ZfJLZJt0MibfjYSI+vZmu3tqb3cs4klCCV56moRNWO4VDPLQ5AbptHsD7xSlAMd0mRkNBdF1itp+RFkK53w9XbS4C6Ip6PqU+mgzR4+21I4r2pmEvVUoAU/o/qKWAet6wDqHYeDhsIixc5dZU4+yOFGnQTc1RszdQ2dYzZKFGWhKMqvBRuBr4/5853brb5tzjA7WzxoBspL4T94nXsUYwgRvNZSOc3PhYtmynJ3D+Bn7YibMq3gxiye8LfocZQJf5CsdshTDhleC1wjPdaigLyUvIUMj+LFIiTYRQ2Z+T6bJBLdXk9h2fxj8py3sDk1qq98V2zsgFXG83TBUwHGj1WypibMVi0M/jbtRuRcFT4yMzLdBIiqCgx1fjHha9MPIHDZ2DD1bs7ptofcJF2lI1wAvrlnpy/IlmsdqpZS/1ZK8QtOTzKBWWfFb1dXKnjpcdBMtppuUTRCQNi8kxktqcMKOl2xykJ8L9+KSWbzJYaTK3LCRdpYEt0eGUCt0rqSq7rwlEq3uOlXtl4aPwQOgrPnCez8YW40QWoRDkqcOtgUXuFa5bDjGZZkurZ4WO1Dxutdtm9VAV9utdvOG6cpJaQ4XaZ7iIvEmml09OCENRR7Q2c5pimJ/OQXTo6N2VqoYUVJ9QLahNU+zy2aF4wu/2gWm5PVijOw3bAgAZc+W5+fuuarqXFIjqzasbaaSXot+8kfdda3/i3P7tCKpOJvGBIXFlx1fDemKlj/H4zkHgxvmuiyMFxrJ77jmU+c0+mI/q97U25a1QhyHgmT9fjA0dHmO52TMobnSTLJQxQAAC5rPjVxX7pmPm3RBKhAVpds18AGtWTXnuAf2G0qhA8S4yxWeXcU1RRR2UIXaJULw6qeebaVyaBZh1oJI6IPtGV5EIIQXNYmsMc71lRUMlByGKFIBbVzzcLJuzHM6WcJyK1kNOvWKh01Esw0HXBkTm/l/gJvCjDLrGDOL6ezwW92pJRV178avT3iomelnZE+mI4Vek3yaId3W3Wp4++tFz6xn4WYC4Q7gnX+aW+kFb06b4JzdVSN5F+8jm5T5yTiRNbO289antFHvBJs4LewTKxKJ91smDvzMv4FbL0HOXJGNN4WgNbaNHMy5QVu4u2/LTFjWDCmDLi4WqA5iG8/k4vG0SA0zBk2IeLGCHouzt6tXUlCoPogFKdBosgMdU+je6d1bOg2b3OrAKXm6N1uZ689if/yhqhkrVlHF/B4Lt7xqTzzxlFW4GaXVs3rpao9F5c96cclna1/2qP61K7993q1M5vjlTrGHDbsXxSGwlAgnZUejLCnb6t7QlPz2PSmibsTU4NZgY+3OPEhBkvF7colRGMkHMiZF/Hbx9CpSNlBaw+xHqAgVV5kVi4nYHfVrSQ7OKNDsJ9+2OZsiqwShXfL/b+/bn9s2koT3Z/4VOKZyJhOKlhIne8eEqaMt2mFFknWS7L39dCoURIIS1xTJI0jbWpf3b7/pnlf3PABQm2z2qxOqEovATM+rp6e7px/2cjzOBnq08J+FL7Trpxg6P1mOzy/yRY8weQzQVTBw0C6tOku/e6N20Wq3ydd59yZ9zpZNt79Py/lcPm3eni6vzIbvbv8YVjisstP7AMdMDylb0+14oCKxDLX1nD7X4LR1D8nkdChsn4rvTCqdGEOWfMwzUEjA7T4ljIIzChzhX9tWOABlpuxxCCEoLuXyRQWHbOkGSs9XeUB5dAz+qZARQiev7lqlPEI6Fz0ia4smZEIc4cSukl3XSG/LxBMKxpVQ6Dd3KCEOX9tE8sa5Nao2izQWke1eWSqnhbS12sYtrZ1ZukTIIKCwXqjXTEbx2Xq2hIRT9wSQLhgxtWJo6ACSDJkJZ4W/HABM3rEDdvqhBkEudG0czT5tS48Wpz4sl93NPuaTchkJVZVMStI9c4Ql+bb2dOol0nsIbQKcmLh2ZB3Z1Q5pKdYEGzyEwwihgFLTm6hJt9l6kt6sJoZGd2LU91rIdjE9Pdz49b+D28f1zWzRlxeQm2yLf1kx8PxuCY4f0ObeIhcHGvixiTP4HSjjl+/BHYm0PV7O59kKsmlmY3A7cYRBGelMLd4k4BcmR0MEaobStDQMjaC3MfRipvdYSKGv3dTOTZBiPWYL0FY3ryedcTHZ++l6DEpV29lO4qohHDDOrU/xDtJwzOYkxuLfJAmhZpz6yre5N1tMmzozMnGd0Yea8iiRzA/JVqm7Z7xqDMEm3zxvAZ28ngm2dACXpHWKXVfd8RwC7eo72uPZArPC5Qku956GZ1ooftC2PGAnltxsYQibXMxYJoiq2EYKkPFdWMIlr4yOu3iHTlhwMyTqb1ddSK4yx7C5aD0DqeogCYdutBsZW7cQDA0InzyZtPnMKWxoQShcUGb5TehrvgN2zTcV/cXu9pO/yRWcFVOgFHlLwzAWN7qse8Togpe6wJW7Vg3fxAoXztagS0jfmv7blw3LTnOL7F2vOAMVwwthu1ZzJYxYlmqCZLexmd9A89591DtlhSFtD1fvlFFcAH4XirUxQk6rTf170vXyQ6B1s7rJv4a6y50u3iU/9pN9cAc0fAaCdTGBBElDjxbXgBrPBUOjmWWHq0ig03JpW7xCww/uwEqWNLAFaGX/2BbHiTJYkWspfos5Psj3nll/WEXZi+V0A6bP5DJc6cfwfIK7QT6+vcRO8lNoSfYXbiPV38SJNS+MkZQygtXEPL3LNuvZRzxPlF240qSqmWcnkHPqMGoIBLfQqm75GV5RhNO5yPqy8CU4q0HesHzveycjmkcFLC8C5u2q1NWVvQ4z7+jY6YnpHpawxcJ9BfSEPunZenV66Hj1+rPlm7srXuJbNQqV7Wqdr6hL5UqAdd3UqtkExiKg45CjmgtNXCdJ0Wynxsor5IQolyC4kr78B52yjaAFBPfMnONZmApY6+XqviXhdMgE6HlljNxOk9vwWbmDfcLLHez/88y6pBBsG9VfBIfJKlkJl0KxI0opYg7oKoDNGpi1KjstdVHV+pvbX8awtbv5x1W2mKRZ0aIttBkpkI6Q+rALt9pJbOQ0eo5F+Uj42zkUo8cYsRH0hiONhdRRJsiojn+A2GgEOXJ4mN7R04HzOXjq+ccgAcls5OXnkvPNO9vISbHO59vw2aA6T04G/xy4lG1fOecBqOzS5QIiwakeqVrE884m/RidX8hkJw0aZzmgNg5+Z+pjv4SrNU5+SrQxquosiF9+T01l/NyGuWbD0ilgFJDt4sM6W6kAePh/Dk6m+pBRBAGWYMUFPq9l0U6i4gs2FVgZc67RSM8vILvJ8D/fDM8vhoewYBgPXzV6K0YpGKFC4FUqo8q04B8IipdicAXVB2Wt5ECTng9eC7CPNMWGcDYwCUfiT7HhbZ6RLoZqaLa7QpwAmzG7rs0z7ZQqe5R8KYSWDJKbbe/Q8szmvhRUDwSQPPkg9ucmXySZzK+9yD9uhCwyFbLIJl+Riyw1OL58GIJ1PpezIGdkbYKKYipgrAXK7pbsUvd89Gp0ctFJ7M+L4dkxvfGUH9w59efb9EIm7RAC1Eo0LyPGyiyWOisd992xQZPzDeIBrSHQQQFqSupGLs90+Ug9Zevp1I7Asw5E6rN0+vcdbiDysC5hM+TZaOjyWyB1I01ozC8pbdaEc9W1RiRsug6NLovRPSVjzWsONF9loAEMrEAnyVfL8W1Hw5DxN1UyAOxhKmiY9A8xeQH0gPula9vwp4f7dsA33kIogYzj+6HzdxuwY+nfhJsIHHAKIXiA0zeOiwTEJcpTQmMUFEADQc9UHYLsavnMxxb+3x2bnDVcdB+wE9Y0BN6NfMrAtsv77ExhrPdOsZbzm6S6jK5JdaLkW7HG4XUR5MtApGFYg91gNIzNRYh6PBgb2WYNTG5wyfiW8wM7B/ZftlnezcYqWG+RvYeI2PfQLXRi0SF+BZe0Wq7BwQD9XG8Fq9Hsbu5WTcsEL1eQsFiXE138cC1OxaxIJPHtubGjWFOyjJ1g+bs7FZLwLWEOlkV3Wtwvxi39fTbPF8uW4tyWhQn7S/ohow7z0ULwt195sIJC54vxEi38m9vNdO/fwqOHpruT7d3KHXwHzYoWm/43v/00rBc3CmU5s0NSX6/uN7dLCCosY+ABM6Fq0EToEPZOlFmsurZY6pfDJRfl5NIjc2Z7YMt9kZxvIH+IDMME+/Xw8BS17E8KE0XtxZvDQQK53cSmXK67yX9u8/U9aBMwFBWBpaMgvTp9IwMsy1hVKhgkkIBkvM6BNAoeELSxE6W9hQaxGQIMbCUEd1PgdvyQCf4muXiW3OV3yzXJ7yEtsHrOHa+N0+cMnXxQo0uljrrV9mKlk7IR3lpfSPP8eCb/tF76vIA5hl60JAXvUZEEX/VC55Ja4ELjAf7/UuOJkh4tIhQGEVRBiStXJMT4eLVNr+8FhZKJvGVMdZX+x3V2lvIUKxlmN2Qod2oPEzPdUpkN6P3oVjC3/+bExolZyZAcAqrjYvDghLXO7tslKRAwJzlORiD9zaorKD1A0DBl78R77Fr7wX1rwUTDVZj4R3axrI9qmjFtkpzrwDy1nbPX5H9wDt5Pn5Ozk1cSs5K7bbEByUG28FTN11PVuxuBgWVJ9hA1Ogn0RPWLJxv3rxcVun1B80+wzBM/wpb6qQ0bXJAHscEXYoMIUvBCUA3otuxoATctQBK6Ctzp/QUAFHQJCgJRQLqEA803aCqrIsWh9y+Wei4GeSHBdRvkJGQ0wd0UavdICnolThoBqWld7aNkQRqkQmUgOi1lGxpOlA3fFJfYT1SDWP4qglS2gsAsaRmz2QqWw0WqL5Ln2fgdpPgS83snjqDZ9Qyvt/AQfX9AZMqiG6OZbH7A8Lrl2025swZqHZgrsSZNFfRCvJHpIHTXudVUmVFPrDOtyn7QiVK9iZqSlpwGbko4zc0I6RkOq3R5DfmDChnAnxJHRdUDeh2y5y+xxpW+zZGKr0tkPh1zs6BiRvlSONZeqk8tbWJAEmZQSl1QZY6uY4cBplPqSg7FvmAqeV2SY6IMdYmfvBHL15egLbRaJHHyCKZOqelQIcjuEHQ/DOsvGLB0Os9uSHf1rbNWYoivVocoMeLyAHov805ITdQVp61iL3z7TdBJaTaNLaSZ+3U+2Y7R/kd0abnq44czfPl61T0e/BdbAcxgDWW1GlSPDXNCYOrJYpyBtKI5Y5pCiJ0YQuLovhIVzmV5RW4aJD1Qa7BRsTvxkOjY88LHSAea6Rdup2y7EcRbnEy1OmVKy5nEHBPKUh44diCWE5K844GdNa1wiJbnEmJmapLEkdWzG4mZBpbbzYKN7i62uYy0JSwghMf35x9X+XoGtviQ2EzInDZX+PC/Todno+PhyQXl7cUmvMm9sucXg1dDWgxiVqJ6osC8bTJF+Pnro7fDM8DLdHj6+sXP57SGHbqqYV/QYsp/EhVoPujR8Xkqep0+H1y8+JlWwzwp87WoYVOiqzrPB+fD9OiMll6uNrM70fCaDFSVfn16MToe/T/RxsngeOhIR6kmUqRnh4OLwdHrwaGoS6OzsjnN84k/lvPh8JCWAk0+4rPfqaPX5+cy3Topvxpn6E6q4oexoauMxy8GKVb903D06me2zDerSap9NAI1X50epsevATfeHLNlNzdrohLyk3oKzocX51B5cDS6GA3ZyqsIPBhvTCtAe5JaWQw7HYzOhoeY1T09HxyfHg3PYjBWy/lsDHJqEwO1CXSBJQFUWtzMIRenLHrQZGgNaX30N7Da8bsAKdVfXKSqJzAoNmNOsFayoLL6q7PXb07EtAnsfzE4HrG1xdNFNZ5tbwJt//nkhW558OYVrasS9Pl13r48PXv9YhAom6pbc3e+1MWbvMmV8fPYLOErE0o5hFiqZVglsdKvTgBFAuhlHZ5nkziY0cnbwdloICCMDgNASArGIg7k/MXwREB5nb44CiF6KBFhAMrF8Fz0wvTn+dHwxNmcTlQ8fzmOxFocpS9en5yPzi+GJy/+XFrfHRB3E40DVUMMxZ5p6pt3v28/D84OU7GpQ6XjU6trBabVVIa7VG8rmIoXr09/CVaTd5xlbR4Pzl6NToKVpSJXKtCjTQsyfHYhzyEKRGc/8+fo5ehkePHmhNHY21wwTfN1eredb2YQVHwd6vJwcCgOmPT4zdHF6PRoxCmXG3jMb/hidJbC5evo6GhwMXp94tZWR2J0maD+q6PXzwWiBPBfAJDIV1pf4llZdRt6pxTEL8PhaXoG42CzzoNx5DWx/+VwcPHmbJieng3Ph2dvh2XI7xkSB4isJhWh7cDrV5MbhFFCtBBMcHdwEO4W4QCi+4QD8TeL049sWwnjYvAmDsDfcpEl4zDJJixfNLCU8RmSqjaeD05+MXxKVEeKtiKgbAgx7nAb+T6fOGpTeNUj+TcfcgOPAzzKbzIIPWov28H4d7HUd1WmLz9gikZQfKMyRfAr27F4DyFMoW6BWvRmwOKe6HRtZpKwjKIEe/BVhahThUk8KKNx3feST03bU2BDYR5Q4SS+wv21akF80rlL9MfPbqpRkqyTX2BTkBDnz4WkFs9IRqa7dkHu8qIQYorof/NMziPG0rrZqks/wf5guMJeVP1o7m2KFmlBIMNSoLnoReFkgGTSmscyCvL05ngIx/TL0avKi2XV+/bD8MvU1hYPJi9nOl5taZbguCT9wOzA8czAO2UFVkoJTIoptYCoRFcXaPoiLagbMpdsmNsXRWSWdRS/0jSm+AIv/vAvnmgUr6AroHtJfaub8HL4KqoSbaks0OUxZubUrSh9b6bU71Ab0kit75sRBQAIkrCpyjOolqYJxpZ1GlVOWRHr5ELCpaW2olJpacnFj5oBvH5VFuHLogs/0axunrvZreVEvBRfTpablyB5qfn49Fna2sErtr3VZYLKssqXJrhJVIwsqSavRkdpphWwL/MtKqSC2MskW2ubzxZTcseFKWfzSfJlIe88xb+tLyf6FqPd7CRk2FLjSew42mydwOMEj3F57Om1wvAhcPzypfL54uA1oocCNP4+wLdw/jQ4O5b8AOoYhLR78bNAwuE3NEqa3J4sa6y2qUXk6TuKKQtUyMIXr0FHgoBtyFdWv+f6P7pYyEq3Q6Tcx0nvBgDGZCDRsz+MuU6jkauvEmyO1Mej1rIAlkTJKySXRRDI9Olz2zurCQAgiE54BF5CAiY6RzzgxXQ0WS1FAYKVtbajkzhp6duV56q/Dn+yiEVWwRBRuMSaY9i94TdP377cU9k8totmbA3MTGu6wWbUfob91GRz6Vb1LNRqD0ogl89O8qZ/SLIN3JgnTb/66v0WZNqs2KQWTHe1uY0NWnceIYdvHG1kInQlcQmiM/ZIku0HkEdKIsW0KPtau/Wwx4pwNjsOLfDNv7DfcltIGqmYGEnJjNKY/JnqbDcFxPDegjGX75gqL10oqbU+auonu2cih6Wd4po03OXIPvG50gLcAe9mE0x9iV1fL9nvBCqmesOIArg7nUJmElIwGF6h0jtYTnwtUkEkjECJNqC8kNJ6oOmx3x8MJno3OBWf9iDccOCrhu1+hGj4oBuFlJhbPd5AB3CLVBViFoPhIh/gJg82dFrkQkyZFCmm64CeeR0vIKXmciE9Hfk6fW6UHFs1mSctLFWeSJaJ+iKB/SWkT7R5wHDy3QSZ0qd2nzkbHg8Ks0cUGLcMZG8FM/PZmhplgN358gOm5kMLjFUG9vPSW+jDrRiRgkZtOcbLNeR0wLwed2CuG7TOIIMuYwiVhQecs5/UduloGaNDb47AahM3dvNzhMm3LWqJQh18ug2xfMX2uhBHhy1aJgxwXJEMkBI9geeR1jhyiGIqo4S+4xwLTXka4hj30FiPHweK9a1Qo5A2wuxFewcW2gIzElvg1DCLUVrfLtmV4QrdzroEnVrhut/qNaYBxds01JKZUeuXpa3Yqgq8xMSKOtmc9Sd8qOPedbvqMjaOS1z41KeNOwBCizmb8kOxslOmdLx3DKDXQa5dZFMVhsy77ewPtHhZoxsss36hnlaBXSIOout7rNBsBz8zJ3Fm76lbVEZxK5WSGZxn/fXDT026+Pim50gLSPFUkD9d5lLRQWpUxdgBcCEGTbuuoMQAzjJohp4GoqRMh9OohOHwJZ1kv01ZHKQwust0AF8naJfjdBPtJUgxyuLyopy19Tq6H8gE9oVjAJd8gAwr2qUKyWq2ISKH7KiK9D/LicGcvxIUOavXgiFnpO/V80e3uMarT58b1A3CSEE7ILyuWoL0nKdql9u3KCaPjoXabLh8LX/RacQZXP6C3Vn4XG4A/f1iZgcwuwSXFXagON8DpjKKQ+Z4ImvTErh3qMWM5aDVvZBT2RToIIvtV2YXsKHKmn3idYP8t0ex/ELsOt3jzV0Abgk26Q7Tzn5Tk6Uo5x66nnI6EKvcAba/Hb4Nc7j/0MTyMji3sFudKy/Yy9JDCSbRwpBdho3JjoyOzfkgFpz8IvtJypqc73J+amm4wTiZDuFQOg3ONOhvVBhWdxfEb5DmAQBcVlA8FJHvnZXXTQoJe7ktUrMsqmk1nShU56DJFDzHcjEb888yZJDRGG/VjK3zrIAWtNuNPcyBKIbteamvTJtR0+qqJf5pbdbfXMWr6icw1K4ZVauNocQiY7YJKwkAier+/LUx+hhrTmLDdrPabrS2Vguqf1nO0Mq1+/rNxembi/RwdNYp00VZE1lj0Ovkw7P6UEfHIWXY9L2QGSVp+KbjWLH/ArdYmGM7aMUuVnUCCVWTl6JIBiIo2F6qAxv8mBxwM5mPTd++Yrkfkmy7uV2K01/GdZEn5RyjIcCtiibyYfVMmPvqeNGSJVPXS7SWDX+3SxUpAJq8acf1KnLh9Yt2mYoFgNoX7ToKl9juLSHxwY1NTRNzIM1B+ZK6Tjr1qC2oFSjrVNAiXs8XEUuqW9mtR6S90gqZLp1VFHXklV4gOikR2CigEoHQd0Jzzi1uyVGjD1ws89xaHVe5uFRYr2dUxOpRGh1R5dmyzhsXrqvg6EXMLmrrAxnprdAMwpZj77wFQXZeEMLtYgYV8CCA//kIhieasjqWP7w5xINOFZE/3CLSAgM4MUHl0SO27SovUYIt8VAmRwe5xcIOpVFy/+v0Xi0ckH4w7QQRyh0fNYwhPXUV5Tsa3O9gdP/bU30QNMay6/6uPdgXjGvylXsuwBbVP5KfIORbvW1ZdoAYmPLMNQB/l4Nl953HuaL0drldI4I6zNnT5Nvv9/07AEsfsGKYOsQq19r1/m60HvT8epftPd5UKWfHkPjizXn6cnQ0dBwqanlBXWfr9Yz6DKFkI+0NQKfC7sHQcd6G26nDgpoqjQhxqmYnnJAEmG05vctBUaj49vXyww5dsnN3PATzMjJ5ygpLTExBoNBLICemgbzAbMJ1+iL/MJ8t8n6zbmgDUF1hqItx8b57KMb6J3zR0vENprN8PoG5K/roCSJG2QXLORNKktyKyD47SQUQXBf/uUWWm5z/9KMADMDNFKudmrO1f49J15Bxl3Hl/gcCCWBiQLhLhhBjs1W62WTKoE32RYFawjDPDpAEwitixZJ9xLO//x3ZaRhfGoK29WGtwHUALZXTk9dnxx2iXlMBhW2ps2F6Njj5ZXTyqkPiZ6zSd7YIhIH6JR2+HRx12M14vu6rkRB9mOk+ZJvMNf8kY1zhONrGl1O6v6H5CN1uRnWttXj2LfNlC8fwUp5rGjbxR5MX2sZbUnm+ake90kgJJhoSjKOTtOzKkoVtgxSVi5+Yatqu119nq1YEFdoqyJCOAWqx0U4j+ANjaXDpb8kO2DZdjz09brSLgcLoZgr52+3U/Usfp5ej/lgmgeV2d7M7wQQIagLZ6NHDSAj84l/le4yIju+QhswWBOOdfWVjGGIidrBsRfLlhnjHkdxJO1r8F8IrqMD7Ytcu0uv5cowIzA01nGjvmOYPiKMaAGZbhf8FuXm9DXvBAN7wdQWhAR3Q0aycKgiDqKabn8zuiv7lt1dt0pNg9Xa4B6blQBRvHSUw+Toer71kOG5k9nhvLEaqLDy2BxQ/ECXUQHX6cYvLq/lsgw72KlPy3ViUzLNFCtlsdWhq9EoT++QrCCNqK4NmBPLNthuOx7xMZjKGzJg8ClEZeEW5J0upk2SEW6W+GyOlB+6L6/4YYeczV9MgB0MkptMFOxY4JOnhsrZGkJLUYmbjaqMkUkPaJzWlyZnWv6oSsQh5QT0ksG9aeyfZt3J1ZUDTV4MOk3GTk8NQgVBYCuV3jeHnZRRHeTkbCCPZ47agphOLRRfMOuZz0dahJaOH2SY7Ve/5llKYopqeTcT+tj2/Ak5kATO2BWbbGoyELml5mA7AB8janU2K1sH3MFALFrWN8kR7praW5DoF8AwOywBf2DDMgcyUpoMD2oodcI1MV/NsgdlN//i9CrvCU7cF65EiouZ3+/s22DR6DQOjFvAY7s6XHzBrHMzzSmGFmKk0235MpS14gXiuwYDBJnhTNx1VPXNo53n2+GWp7Wef5jLzEoXAJPXDGWNMPrywR7KTXiac7Yyd1u6AuYja9m8h2GjD2QV3HzXLtdP//uFTUuYGtfvklDjIRSYqUzHw/MASDXuxDAWoRSW7F274Xl3EkqnjWJH7tjidqHlOx7eloa8y9tu9iYrcRtmZpNy3yQ6vqJuZJjanER9GyBfqWaNTf+TBi5+HZ8RU/gGWwiVNaxu0IvFbihkCu+MFCz5xHuQr+IMQq7Z7gpQ7CnigOxG3P7+njvJjul7+NV+AJbCC1wxhPGurC5TBc842AX7jdVy33hpVVhgUdrN8Jxj6iuJEeNPigTnYgPfnpe2Z57L45ktXr7fcri1iXE9cO5W5idywjqmJ0pC69jq6rGNpwSt5thDaYkjX9o0lHACOwYmpx27yr9yLYqePVCeq4BvNpb7o1GXNRRgtGJokosdURX0NJOlxQGd5paONZ3OtNyIVXHXlVeQ+2xtB7J7hqu1fbTtj4ipPHeSPkTVCrXuOoiJkpK8sjxXg5MsJGEPJ6RR/W6QSP5SiGoNOi98dnPoE1ujL7rNp20moGrihJ9rL9cY1CQqhMv/qGRqYJDTMPoKEo9POpxBZRDCToGYzq0EO1+H5+ej1SXo4HBwejU6G6ZuTkQngJL3i1UKJyt9TXTvVpmKUcEnNj0cnby6G59qIYKoiYivRgZy3ge7tuW0yhiBQgaa3DjEFcOshpNFx9RgEDX/xy+nr0clFOhSs6p/5OJCOGGDMaLvVcBfdF4O+9jrC/FjcTnqjUokI3OQ82I9URhzt0zwENAQCeADD2NSwzi+Gp+dtnSJlMbsT3B/s49gMBVgiMTOoChRLfiwEqtHJKz1ZNKdWmZVEfEf+kt3czO2OhBxWk16iZlRstf1pB/MPJAYF5DsMCE/WBXAOP0U2JpVoO64WzEUzBwTHaXEI7h14m08efOxeEJTSvWQgViu7yY/he0tGDYQPGIDeuRESwg/Y82fj8Xadje/h7xnY6zVBZprnG/yow+LADwgv4dsfSI0HFoRCNpoOAly8TyVQzWC6EJANgQImgkWHBgDRv1Qxh/VxAmzQdjCCg8cKyUsgiGq00kreknBWNsyrvnBsqWDujkVl4lgsdqKGlInHp+vD380TXe7LBNswaHfiGX9iknP2sl3pmRTI7wr3f7xcW8aXZ+8eYKng2aAij8Tftmv4XGE17wO7ADTLifdpxEBQL6911UNzN23qppkbGr4R2ftyi0NC2vpM/KNWiH2n7eDh2/dPYc6e9V3DRSZK9gMShpEg+wHxMiRi9uMyJ8PnfsQrUEqhfVcY5QJpPySbevJpPyKtujaUfd+gMsDv9KO8j8+29tUrXs7hVvuMq3WH6rKw/ZiVZuW536+w4wxyi/1y3lGgfZ8ae1pqBDuhr20/neMI9hTeWkIS3Ltsfd/ydhDDch4Zm5zj/8LOccftHrso4f9WFjG/tSGLSh61UxDJUgsYNZ+/kvWjtnYxAmLczKXMsIWIjYL/qOVlWrJltJkSt0WixgR+COP6Nrexs6m+uYjEyE6F1a85JVT5LoBrtkM7CZk/UF1gFG+q3ZA6G2Q++8GMSmHOWMbR5nxl1KWdtUF+iJUkFzOADRyiy7i4wYUtKOP5TfgrX/ZJJ9vcH7t46eWfd0bLvsHIPWtw0feYxBWNNRUZz4QETLbD0cYaKaSXWwvJZz1R3FqPJPxdIAgrYVPvA74hrJTE7htTfuEIOGHMRFwOpK7NSFhbHkIo0Zc4Fq2XHzwa7VPYEHX1eWVDYB3iGihZxR5LoYXROpV+Ts5pqPiZGPregVdDDP9y/ypa4btghWfxCgf7wRr/7tb4zHE/Znrl7OmIQIzNv5U+ziAQa+VUT6mevpkmZwfq3+/07338o+kPJMB/Kly4xEm/inxTM1z6+buK2vvudz4DnqJx+cHNTqJQIPnJ7EjfXMPTnGq8CZekqlOS18ppmKD14O0wfS7IedhQpNQOUJ1xsodSQ7655eFYIjaHIbtD6eQxmqKTh+BQxzmG6dOKEyDjoNH+i0yFMYWMN5mRASaJa1f6hSGJAiAoQT9mY60KVdXHt9kCrA6wRXnbMt2uIQx/1/jv+jrmIAEy5ahfr1e37ZUnTp9G4A8LBD6i74e0rZXujPD4Ztf8DfEdXgqUWiy3N7da+b3bQRhnAaqK7rGz/8egai9ycjjHpjMGc3gCfxFnfLSHcFTGDi1jgNKuMrSXwAuCuZBmNwEq1nS6mAr0TAM3GJ1YB/olaNL2rUGNzPQ7dTcyX+0yMYwZ/pxtFxi7RHA++XrNdj8qIPWh0uzwDdR2bREZvxQpGrxnYihciiflY26u5VCorOGU0IMkHTBqKlc9StVGgfsTVYnyvNpznl6U2ik0OUzoJU8SlB/BPZYae6I6TVpo+QZWxvZU37RK9bJKC+zuQ321Km1vG455J06udB409JcvgXrbp1dVHv2xmQ0vXQ3hlVe45V3TwmW/GFDsJjYY4lRXTpfTqRibuY0kYHXIBKf3Oh2vxcDQxa1zn1sKiyG0l180qvDqNCrYMZ6ENOICbq8RbWZSd3YiVjVozxFBhF5YX9iFNXG5I1et7OIQu7d1jtcrL+9ccJ4BcaIgomcjro6HKl9jEEo/HSbZ7nZSK7mMwLrFpz8wW/xjIBZZ+O4hsqR/56HMx/zQI1krLfHCLpUco460ED2GfcXT3336lvfEGWz1ccotvqRpLaWpfrAYBw8Y+ZYaCXIrJa3DhWg/g6Scs829sqEuHEeCQM5XD/ECjQPa8ybDFwhd8d8STXBaYIC6WaYLsTIB+3rPo7huRTlOyPhVw6Tf+h3ALMiq/EyRkwTgxF9iaDXgyYIyhzVU5gCl2hemUC3EDk4HoKKxGWhAJydIjex1O9CI2KqguJM/IAByLqRUDoMgmHGdCKel4i7/gs9D4UxZnClzLBkeLymWAj8KkndWCHiz94gVRSIOrwC8dT7PM3DrUxIgwIbFnok52hsLWRRTohabLUwazDIm4VtlbgQBakmmzGj65oXJguKyiYTEcRu/qE4r4GuyUOjZ7sWdNRRw6T1Lekb8R8QWlQtmNmgUHNhrY95eChUvTp7F+1DXeNI3pnSNC2W4vfzjaglR+nT0WHURXzRLIcYHlerhFIL1F1uCr2bHfr9e2I/Z9qPHF5RPfmP3noXQiHTgkiT9gUkQzKkHyiz8bguuFlovsOBevg0vMCQKUvOmbnmgJ2LS4B/wmIyPXU7hp8++Js/LH1mrtY6CqJr0c58uCzyNUvmHMjTBX9ocf7po7dSupXqN6lWVcs0l2LlcaScj1RuVPpAC7Ba32SoHJW8UkDaVMdDokMpB+guOR448+YoYtbKBJtTqkskIoZDjAxBeU6aDVAm24sTE60J4H8Sqo21QqjGh0L5QBSoypeVQJ7FWRJVbHItOxWmzXEOmwBQjaVeTtmCnO5XV1K6tLCd3dXU5fjJXl7emSzX6EM3StkvdYNqzzgMJffyL3lGORZnZWAY5zK46qAZGjNEMIPuuClKcCJbhsUDY0xeDcgQMULCOiwpkqXecTj16a7xnBm87TQcfhAI5xxRhfnV62KpJDuxwaOBvts8bNfeCgLTt73f3v+00dh87GBKaUeuhVC24oIOQYBJznhjfsDgGkGNLiEJ2apOvkmg6ymi70OEHtasH14hHHJJLUpRwwDXJP81wiM7CMqmiWNj1MpQLPkJs8RyHwLIlh3d8iQPDUq6aQtK5jPahJUnypSYwV8lPJRQSojMvblpxEvOVK5h9bdx/457R0r8fC1llriuchWpeVUyFQondFoTUvhGyG0b6deZ2h2VRXWiVom3049dJaYZMMd0U92qBCeTIFGDYlD2AsCiLZss+km5V0RcNw9hCGyisV6WkmW1WL1FmL7I0YzT6kDpHmZDVc/+qQBbqxwWY4hNrVDho/vZ3QZxY3lCx7HYKHrDm0vjcLJaFVX+l3HSX4YUiiS+VhGQyUfLVcx3xapPeKj43tNZ1D+xGOdNscCNe0Kbb7Jen2ez8Lvjl5RwViOUsWW04NPeoAvN34ShxmbDCKO9bXfJk/S0YpPpov6M+zeRHVSvluHVUIDjlpX+tXeDon+prh34fvIy5PH/Fp/YBWOV52BiMKJEHSJMWUyKNh9AnogDysh2HVVoLHWX+p35SniHZVxiF8RM9k9RqaS+l30EeKgkHtHrXj+ShjteSSXb70STUD0BlJZFEc2kLhDRzWYp2xhfMoJupV0V7qpDHi/awCxZV5/mtQCUa2VWLLyopGhpAuVFf40TzISr9po7pIX0cIdSFiYhgdPm6D7AYmZj7rLmj+oHnUFao4SWqrr2BKrgKEB7jZdzJrlHSdykq2Wt+VusdNlwom3XZcLf9kizWv8/JE0oMXiIy+6jxgDOJe3hWH0h+o7udSjoCNfzTgurt7nU2fgeXkY5+QJXcLvCPtGXus52LWh0Qaiv496I7huBwGKACgqulLT+8RQcjMmLsxQOaRoH2DoxoIu3pbsl5ckZX546g/oUnCbRdtSxc9z+ZrPqhcFo74EdZ1OxevX1f2em6dGc32rML1YMnNlmdEkrNjeaUz3eQCJibti66/LcvD666+f+07LDbXWn73u6C9XurXWLnYiXooqAC9C73bUadrR3VrTZbvYkJNjQoytd9Z7fHbWswEZC7SZziX/K4Y69ScF95fegEIgiZywbXqDkEZuPyy8lVMtJtiF9P4cURUOsvu99Ok8F4LP8IH8nN0aH8fHE2UhXwBg3/hMO+rK6QSfdeqerizyP55y85hCOBv873fgaeAf8+OgMPkLwZxreaLvIVGhfEl+w9+Df46w/vy7V0E7e2vamtrEzvTRgMyZFW1meiOO8EkawrwQRkr8o67tkYrWDNL1PYffO1ssAMqmfaNXYDjRUS3ANgOKLdCl2bQp8GMTdA0HvFHARDMoBtCiyzWIWIUYOKx1tpmllhphmnLyWMZ519ETHk3MWos9YBamau5MCssvgsm9jyc62WLSiroK0xbY10uZaZKOYVdeNWovUurCusR3+3cdWf8vjYHG+PBy1//X5Ue13wydSkYLZIlWtAnXrV6x2ej1qxmXxFvuNyXBKiKUJpywIcVfIUkp+AwGITUC3MgAk4mBY/SNEPQor9AEwg/hV15GQ+X3vUh6TT+LUObuZAoh1iHmIh7/jfAevqBeUpDYPjU8v6ZvLafwkuxZW3E+UPMZoVYRAbv6J9vT9rv46NfTbdGHeIuIm98kuakhmIRIj41U3vWQcD07CD9T3tv5MEtcLjEp4yr0utS6zpeRkpvpP3pT/cHbww/WO/Fr2vg4Q7HYRN4l1nPO7AsVHjQFllhpydGmahNY7yf0zP68yj3/3AaR0PQNHgfpKheBqagvFQf+ibfjQ4VwEMA8hu/BT7/bBTYoBy1pIKZlPb2eU6xqQKcnAHXv6GBse6YRwMDaDfgORan1B5I6r6htSxNopxYQbrhpglH0cCHbJhynbvWZDyWtfiSmkial5pQ7lNfF6uzrDq+npVeNvqWWhUy0K/is92xYR2dsa58gMuEMbYy4gdClfMozVHwhKzUyzms+tm6I57XiqAJDxwKTsY3OF2bghbyFGEs3JlrJ5JCCGdW+N41Kvngs4H5SUUDLuSh7ZvPWfzKlmiTlARDJzlBhWpncTM3zV0mOGhObPUtslUTHqfOpmwdstsIs6dUGKT4UK6xct2bW6TsjQj9bKI+MlCFosuSwlCcmwE85Q4AaFK4kDtGgMqMBEkUBCEtp5vitB0QeCc5FOv+82Xn5tdmZfYhMlpm4gGmG4EotIedJLvOsnBfjscv7f54vgF6BLeCyYVI/186v347eeeAx8zlcJkXCLcveTgqt0OpCUYnQhJ7OXR6DS9uBj0ysNZQCLjvy4Xm2y+BymNTJKkDEPsWjRA3mOTpbgU8McdLgX89euF5SKp3CIZXtgYXorCe2KISWgxVB/bPPhD2YJU6xtMg2K5yhaqEbZjgNVTc2hXsIL1JRHaAsHGmiy8YNMuZqon0otlHAgLpqfKKRoJCaZH4IUFi4UE0xWehSsEQoLpGiws2GeSH9xPtegllgjnXRSLl7q5FwNo5qVZ/PCQNIvmSPh7Uy1aQJGcim4Bk1fR8kmJXDNJP55dNf7wz/N0n3af/sdp9vFnHNZv08a+fGL/7u8ffGf/hvcH+98cHPwh+fiPmIAt6BtF83/4v/kcfJvcYZBgQQMaf3h8/q89yBp3V/e/ZRuwqb9/9gz+Pfjjd/v0X/jzm2ff/dHd/99/L/b//j9y/y+zWWm5qu//nz7T9fIukWZiSoaZQXyNTVKIk2uVKnYdS4GpZoH2pLIEpimDl5KrlIWURT4pgW/kx2I5f29bwK/GooyW6FppWfpd3+s643UOSkfzXdbCOycKFQ3/8BM4awvxbmla1dkyG+q3YAYnyzv9C4Up/UMwyat7YC4WK/1qWei/svXNKlsXeeOLBBsSw7iz/S7vr0zRYcpMb5TwKeccA6W8nxWz63muEvgWRP7NF+/1W8mIiRez9XKBoSCfvHhzOEjfjs5Hz4+G6eHw7ejF8PyJ5EWEbJUVu1V9YkQc0qqbQUIXYfBtIdvMZbh3oJFhdeUw50qwUjZoWDgdHe4IOABBTbaQ+gHZUpucsiXWtCCzTNNWerMl3Wsg7zSfJFIpaB6oOEIM2MqKGyjQi24YDCqW3e8/MW0Lge8UZBzpvsG4tMhzCH+UT9TQpULhLlts8fJHf3RT1u5SAPPl2kKLVVduu65TO/xWwgST2HwxKQD4YtGd5FKlCj5qY6r8C5a+FkLD7V22fqdLyuFnq9X8Pp0KyWKzXQhUWKd32/lmtprPwCyWSs/W8lVOUrMpJCgwjj86S0CphRLu8Jskm2Qr0bGnICbYPHGFjkBkCQRSBiE7dqUi8uI2T5bT6Ww8y+a2seR6O5tPigSW3maqQ799uO5PZBLrbnIsBqIi29r8M+prAlMhZgWjJ2GqHm3vVWBAJCG33qB+/lpswacf8tnN7WZvko8z6Wa8xsyeH25nc4F98/nyA7STAQlTrlPvc2zhGvooJgPm4UO2vtvj2Xq7etaYrpPqTYYXb06GQdpi1ySQ/+vn4eAwPTpLj98cXYxOj0bDM7ORSL0f+R7BlXsLwSelU0MzBktGI7oWc7YsZjBWpZJBqRFUArNJyyxMuyfnV+dE6vDsglK9Bh9oPt1WWwrXgDA2i6GVqZuY83QmZNU1qDKvl5vNPF/k43cq+5FyOFN4R1QO5COvZEz4xNn4lxyO12aHJeUCp/GJ0eDDaCQ+iTHYkGs4ghQ/EGJPML4va8kIxfgeskFdXrFbtzmK+boORpk6qEjqjlPclyuAwOkSFKgaEXjGWskW9y2cWhiCWSLzhky9o5LCEVw252u8NpCoR961k68IkrlX4mIBZhicUhSFZrCif/+t4JHCXlv0W0mbeuWMJTKcoHo1AxuA+fU0XwoquAdkEHYx2TqTmbrLBJ9dmErF45k5V3O9WrOLCALPIE2PUYpPve63+ecOTj9tEBR6U/HeXs81P312yV8hKC3EBs8nYc2fJRPq7ub54Hwo9ja4OpimOnp6HDVUu9GAu4cUUCVNYe6epOkdhDBMn/QkvUbeD+iR5gO7g/XNFmx6T/FLa5IX4/VshbFNm2f56DB5LrhnzPh2wTOYS1DdbCKOSQWDTOPenuQWMb1rE+woppkYAGrCbvP5qt9ElZyg74qrVOXA0r9fbNY0pV2opaZYncLAOl5OZtN7DWq5ktH1toUOmz5e3oljfbIH4yCdKTdxXAAj0jcTJbPuHWpCHezU3p7lW0g7ewdqYALV4rWfqNp7UPuJrQFwik3/iQWtOWPRP3R9R1j4D0ArWjYVIPJSZCUwoXezx24J7/L1TZ4Chy9z8bp1FH3lJVHziCVhIWyR6TrP/2qcaSokAzOKLuNZYyyugSm5N7JLzofDQ56XNJ5+nrB6AErdTnlMJ5aX8drSyWyteHKrItaNkSLafEJrmfOPYpKKli3RZlIAiHziJSvQ4NdyVJolN3ICtWydjuiFlA1JkEx26XGevYeNoGRcGasSd1/vk72A4KNr+2DIEtRALNaBI5C0JybFo4qADrVIBzy0s2fhF0S77hbrJE/WT1CXPp72SA11CEMxQU7EXDb/e9FEH72uYGGpFc0XXodtvbbL97l4BXY3Du70+/sVN2g4GtlI778XfBHa5XhskEzdrQoMW8+ut+JA6c6KVJ24EO+NGkwGyoqCqVIySG6opUSP/pPFeDx/AglNRRFxdN0uxTsh8/WePn2i+rZZ3xPgNM42+4WeeVnZHR78jYwiREqRoWJT8U7FuRN/YX5Vpq+RhMO7H7Y6G2XIpyH3I230I83pP0kbMv7idjHWfnnpGG9MpMGI0dw4DeesaQLO5hX0AvtqcOY9E+bcxgnMh0iEDd/KA6ico/qRlUO1tErKv7v1My06uV6dgXRqBm6neBQOkFyeqjFixuwkLTSr7YUb1mjrbHiHDUMLjfk9S+UX3K3Z+2w2z8Sh2GrLfFw7bOnwtgZGYb28d3Z2+/GG5PF5fB6fx+fxeXwen8fn8Xl8Hp/H5/F5fB6fx+fxeXwen8fn8Xl8Hp/H5/F5fB6fx+fxeXwen8fn8Xl8Hp/H5/F5fB6f3//5Xzi++McA+AIA"
overlay_bytes = base64.b64decode(OVERLAY_ARCHIVE_B64)
with tarfile.open(fileobj=io.BytesIO(overlay_bytes), mode="r:gz") as archive:
    members = archive.getmembers()
    for member in members:
        destination = (UAD_DIR / member.name).resolve()
        if not str(destination).startswith(str(UAD_DIR.resolve()) + os.sep):
            raise RuntimeError(f"Unsafe overlay member: {member.name}")
    archive.extractall(UAD_DIR)

OVERLAY_HASHES = {'config/defaults.py': '839faddc24b14d21f073c0a2b588406cd24ac50651304c7d7dcdbe8d7416b89e', 'configs/PVUAD.yml': '1aa85aa03deee5b9449c71b4599fe630dcff6b11a454b51b458321131e23713a', 'datasets/bases.py': '7712bac25aee214f38a913cf3aad1ce4ef33b9a713d7e177ad67ec17932c016d', 'datasets/make_dataloader.py': '136cdc2da834f6ab181dc35c9c8f9a9cae085fec493685d730fde545cd4afe21', 'datasets/pvuad_sampler.py': 'c5c5e445a23e04d3a19bde3e49ea814d7c37ee8d540b70acd1254c19f3717220', 'datasets/pvuad_transforms.py': '056fc9f25aba6361d4612bcc313f0cc2d175e2b695757f6912e09fc7b5fc61c0', 'datasets/sampler_ddp.py': 'e4c455f7c7afbfac09a503a924c7b09586dbdb8eda6c88735ad1a3e37599bf7c', 'datasets/whu_mars.py': '11d3a0c501912a9887d78601df01afb6495d2f859835a6b69d2079135dba24b3', 'model/backbones/vit_pytorch.py': '723305c1a05e204b744ddb0ff7873b5e02840329e01787200173c9064ed3ad05', 'model/make_model.py': '8b7db7f5a190041beddf2788fc8820abe30f6f75b9b31818a402fef101b517ba', 'processor/processor.py': '9f678d53aa8fe6b7e01ba40242a1fb18d96e1a0ddf8f1046d5439124781b55df', 'train.py': '8da1552749d67272ca6d8078ac3dd8c1df4183924d7795a6e7b0355eecf18ff5'}
for relative, expected_hash in OVERLAY_HASHES.items():
    actual_hash = hashlib.sha256((UAD_DIR / relative).read_bytes()).hexdigest()
    if actual_hash != expected_hash:
        raise RuntimeError(f"Overlay hash mismatch: {relative}")
patch_manifest = {
    "base_repo": OFFICIAL_REPO_URL,
    "base_commit": PINNED_UAD_COMMIT,
    "overlay_variant": "transreid_init_trainable_768_global_b1",
    "overlay_sha256": OVERLAY_HASHES,
}
(UAD_DIR / "PVUAD_patch_manifest.json").write_text(
    json.dumps(patch_manifest, indent=2), encoding="utf-8"
)
subprocess.run([sys.executable, "-m", "compileall", "-q", str(UAD_DIR)], check=True)
print("Pinned and patched source:", UAD_DIR)



TRANSREID_MODEL_NAME = "vit_transreid_msmt.pth"
TRANSREID_GDRIVE_ID = "1x6Na97ycxS0t2Dn_0iRKWe1U5ccIqASK"
TRANSREID_SOURCE_STRIDE = [12, 12]

def find_named_file_without_images(base, filename):
    base = Path(base)
    if not base.exists():
        return []
    found = []
    for root, dirs, files in os.walk(base):
        root_path = Path(root)
        if filename in files:
            found.append(root_path / filename)
        if root_path.name.lower() in IMAGE_SPLITS:
            dirs[:] = []
    return sorted(found, key=lambda item: str(item))


def torch_load_cpu(path):
    try:
        return torch.load(path, map_location="cpu", weights_only=False)
    except TypeError:
        return torch.load(path, map_location="cpu")


def unwrap_checkpoint_state(payload):
    if isinstance(payload, dict):
        if "model" in payload and isinstance(payload["model"], dict):
            payload = payload["model"]
        elif "state_dict" in payload and isinstance(payload["state_dict"], dict):
            payload = payload["state_dict"]
    if not isinstance(payload, dict):
        raise ValueError("Checkpoint does not contain a state_dict")
    return {str(key).replace("module.", ""): value for key, value in payload.items()}


TRANSREID_CACHE = Path("/kaggle/working") / TRANSREID_MODEL_NAME
checkpoint_override = TRANSREID_CHECKPOINT_OVERRIDE or PRETRAIN_PATH_OVERRIDE
if checkpoint_override:
    source_checkpoint = Path(checkpoint_override)
    if not source_checkpoint.is_file():
        raise FileNotFoundError(source_checkpoint)
    if source_checkpoint.resolve() != TRANSREID_CACHE.resolve():
        shutil.copy2(source_checkpoint, TRANSREID_CACHE)
elif TRANSREID_CACHE.is_file():
    pass
else:
    attached = find_named_file_without_images("/kaggle/input", TRANSREID_MODEL_NAME)
    if attached:
        print("Caching attached pretrained TransReID checkpoint...")
        shutil.copy2(attached[0], TRANSREID_CACHE)
    else:
        print("Downloading official MSMT17 TransReID* ViT checkpoint with gdown...")
        try:
            import gdown
            result = gdown.download(
                id=TRANSREID_GDRIVE_ID,
                output=str(TRANSREID_CACHE),
                quiet=False,
            )
            if not result:
                raise RuntimeError("gdown returned no output path")
        except Exception as error:
            raise RuntimeError(
                "Cannot obtain vit_transreid_msmt.pth. Enable Kaggle Internet, "
                "or attach the official checkpoint as a Kaggle Dataset and set "
                "TRANSREID_CHECKPOINT_OVERRIDE."
            ) from error

if not TRANSREID_CACHE.is_file():
    raise FileNotFoundError(TRANSREID_CACHE)
if TRANSREID_CACHE.stat().st_size < 300_000_000:
    raise RuntimeError(
        "TransReID checkpoint is unexpectedly small; this is likely an HTML/"
        "partial download: {} bytes".format(TRANSREID_CACHE.stat().st_size)
    )

payload = torch_load_cpu(TRANSREID_CACHE)
tr_state = unwrap_checkpoint_state(payload)
required_transreid_keys = {
    "base.cls_token",
    "base.pos_embed",
    "base.patch_embed.proj.weight",
    "base.blocks.0.attn.qkv.weight",
    "base.blocks.11.attn.qkv.weight",
    "base.norm.weight",
    # These two are validated only to make sure this is the official full
    # TransReID checkpoint; they are intentionally NOT transplanted into UAD.
    "base.sie_embed",
    "b1.0.attn.qkv.weight",
    "b2.0.attn.qkv.weight",
}
missing = sorted(required_transreid_keys - set(tr_state))
if missing:
    raise RuntimeError(
        "Attached/downloaded file is not the expected full MSMT17 TransReID "
        f"checkpoint; missing keys: {missing}"
    )
if tr_state["base.cls_token"].shape[-1] != 768:
    raise RuntimeError("Expected ViT-B hidden dimension 768.")
if tuple(tr_state["base.sie_embed"].shape) != (15, 1, 768):
    raise RuntimeError(
        "Unexpected MSMT17 source SIE shape: "
        + str(tuple(tr_state["base.sie_embed"].shape))
    )
print(
    "Validated pretrained TransReID source:",
    {
        "path": str(TRANSREID_CACHE),
        "size_MiB": round(TRANSREID_CACHE.stat().st_size / 2**20, 1),
        "source_pos_embed": tuple(tr_state["base.pos_embed"].shape),
        "source_SIE": tuple(tr_state["base.sie_embed"].shape),
        "source_has_JPM": True,
        "target_embedding_dim": 768,
        "target_stride": TRANSREID_TARGET_STRIDE,
        "target_SIE": False,
        "target_JPM": False,
        "backbone_will_be_trainable": True,
    },
)
del payload, tr_state

TRANSREID_PATH = TRANSREID_CACHE
PRETRAIN_PATH = TRANSREID_PATH
print("Persistent TransReID initialization checkpoint:", PRETRAIN_PATH)


if RUN_TRANSREID_INIT_SMOKE_TEST:
    print("Running trainable 768-D TransReID-initialized UAD smoke test...")
    TRANSREID_INIT_AUDIT_PATH = Path(
        "/kaggle/working/transreid_trainable_init_audit.json"
    )
    smoke_script = r"""
import json
import sys
from pathlib import Path
import torch

uad_dir = Path(sys.argv[1])
checkpoint = Path(sys.argv[2])
audit_path = Path(sys.argv[3])
sys.path.insert(0, str(uad_dir))

from config import cfg
from model import make_model

def load_state(path):
    try:
        payload = torch.load(path, map_location="cpu", weights_only=False)
    except TypeError:
        payload = torch.load(path, map_location="cpu")
    if isinstance(payload, dict):
        if "model" in payload and isinstance(payload["model"], dict):
            payload = payload["model"]
        elif "state_dict" in payload and isinstance(payload["state_dict"], dict):
            payload = payload["state_dict"]
    return {str(k).replace("module.", ""): v for k, v in payload.items()}

cfg.merge_from_file(str(uad_dir / "configs/PVUAD.yml"))
cfg.MODEL.PRETRAIN_CHOICE = "transreid"
cfg.MODEL.PRETRAIN_PATH = str(checkpoint)
cfg.MODEL.STRIDE_SIZE = [16, 16]
cfg.MODEL.SIE_CAMERA = False
cfg.MODEL.SIE_VIEW = False
cfg.PVUAD.VFPROCA = True
cfg.PVUAD.LOCAL_CONSISTENCY = False
cfg.PVUAD.TIR_DISTILLATION = False

model = make_model(cfg, num_class=500, camera_num=8, view_num=0).cuda().train()
if model.transreid_init_audit is None:
    raise RuntimeError("Missing TransReID initialization audit")
if model.in_planes != 768:
    raise RuntimeError("UAD backbone must remain 768-D")
if hasattr(model.base, "sie_embed"):
    raise RuntimeError("Source-camera SIE must not be copied into target UAD")
if not all(parameter.requires_grad for parameter in model.base.parameters()):
    raise RuntimeError("TransReID-initialized backbone is unexpectedly frozen")

source = load_state(checkpoint)
source_qkv = source["base.blocks.0.attn.qkv.weight"]
target_qkv = model.base.blocks[0].attn.qkv.weight.detach().cpu()
init_qkv_max_abs = float((source_qkv - target_qkv).abs().max())
source_global_final_qkv = source["b1.0.attn.qkv.weight"]
target_final_qkv = model.base.blocks[11].attn.qkv.weight.detach().cpu()
global_final_qkv_max_abs = float(
    (source_global_final_qkv - target_final_qkv).abs().max()
)
if init_qkv_max_abs > 1e-7 or global_final_qkv_max_abs > 1e-7:
    raise RuntimeError(
        "TransReID weights were not transplanted exactly: "
        f"shared_qkv={init_qkv_max_abs}, global_final_qkv={global_final_qkv_max_abs}"
    )

images = [
    torch.randn(1, 3, 256, 128, device="cuda"),
    torch.randn(1, 3, 256, 128, device="cuda"),
    torch.randn(1, 3, 256, 128, device="cuda"),
]
output = model(x=images, mode=0)
cls_score, global_feat = output[0], output[1]
if tuple(global_feat.shape) != (3, 768):
    raise RuntimeError(f"Unexpected UAD feature shape: {tuple(global_feat.shape)}")
loss = cls_score.float().square().mean() + 0.01 * global_feat[:, :16].float().square().mean()
loss.backward()

qkv_grad = model.base.blocks[0].attn.qkv.weight.grad
patch_grad = model.base.patch_embed.proj.weight.grad
if qkv_grad is None or patch_grad is None:
    raise RuntimeError("No gradient reached the TransReID-initialized backbone")
qkv_grad_norm = float(qkv_grad.float().norm().detach().cpu())
patch_grad_norm = float(patch_grad.float().norm().detach().cpu())
if not (qkv_grad_norm > 0 and patch_grad_norm > 0):
    raise RuntimeError(
        f"Backbone gradients must be nonzero; qkv={qkv_grad_norm}, "
        f"patch={patch_grad_norm}"
    )

audit = dict(model.transreid_init_audit)
audit.update({
    "smoke_test": "OK",
    "feature_shape": list(global_feat.shape),
    "init_qkv_max_abs": init_qkv_max_abs,
    "global_final_qkv_max_abs": global_final_qkv_max_abs,
    "qkv_grad_norm": qkv_grad_norm,
    "patch_grad_norm": patch_grad_norm,
    "backbone_all_trainable": True,
    "source_sie_used": False,
    "source_jpm_local_branches_used": False,
    "source_jpm_global_final_branch_used": True,
    "target_stride": [16, 16],
})
audit_path.write_text(json.dumps(audit, indent=2), encoding="utf-8")
print("TRANSREID_TRAINABLE_INIT_SMOKE_OK", audit)
"""
    smoke_env = os.environ.copy()
    smoke_env["CUDA_VISIBLE_DEVICES"] = "0"
    smoke_env["PYTHONPATH"] = str(UAD_DIR) + os.pathsep + smoke_env.get(
        "PYTHONPATH", ""
    )
    result = subprocess.run(
        [
            sys.executable,
            "-c",
            smoke_script,
            str(UAD_DIR),
            str(TRANSREID_PATH),
            str(TRANSREID_INIT_AUDIT_PATH),
        ],
        cwd=UAD_DIR,
        env=smoke_env,
        text=True,
        capture_output=True,
    )
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
        raise RuntimeError(
            "Trainable TransReID initialization smoke test failed. "
            "Do not start E2 until the initialization path is fixed."
        )

Attached UAD source candidates:

fatal: detected dubious ownership in repository at '/kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/WHU_MARS_official_pinned'
To add an exception for this directory, call:

	git config --global --add safe.directory /kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/WHU_MARS_official_pinned

,path,base_commit,selected
0,/kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-...,3e2a07314119402586c76096e87d40420894ad30,True

Reusing attached UAD source: /kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/WHU_MARS_official_pinned
Pinned and patched source: /kaggle/working/WHU_MARS_official_pinned/CVPR26_UAD

/tmp/ipykernel_23/786275482.py:116: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  archive.extractall(UAD_DIR)

Caching attached pretrained TransReID checkpoint...
Validated pretrained TransReID source: {'path': '/kaggle/working/vit_transreid_msmt.pth', 'size_MiB': 399.8, 'source_pos_embed': (1, 211, 768), 'source_SIE': (15, 1, 768), 'source_has_JPM': True, 'target_embedding_dim': 768, 'target_stride': [16, 16], 'target_SIE': False, 'target_JPM': False, 'backbone_will_be_trainable': True}
Persistent TransReID initialization checkpoint: /kaggle/working/vit_transreid_msmt.pth
Running trainable 768-D TransReID-initialized UAD smoke test...
using Transformer_type: vit_base_in as a backbone
using stride: [16, 16], and patch number is num_y16 * num_x8
TransReID -> trainable UAD backbone initialization: {'checkpoint': '/kaggle/working/vit_transreid_msmt.pth', 'loaded_tensor_count': 152, 'target_tensor_count': 152, 'mismatch_count': 0, 'resized_pos_embed': {'source_shape': [1, 211, 768], 'target_shape': [1, 129, 768], 'target_grid': [16, 8]}, 'source_sie_loaded': False, 'source_jpm_local_branches_loaded': False, 'global_jpm_branch_used_for_target_final_block': True, 'global_branch_mapped_tensor_count': 14, 'embedding_dim': 768, 'backbone_trainable': True, 'loaded_required': ['blocks.0.attn.qkv.weight', 'blocks.10.attn.qkv.weight', 'blocks.11.attn.qkv.weight', 'cls_token', 'norm.weight', 'patch_embed.proj.weight', 'pos_embed']}
Initialized UAD 768-D ViT backbone from pretrained TransReID; the backbone remains TRAINABLE on WHU-MARS.
===========building transformer===========
TRANSREID_TRAINABLE_INIT_SMOKE_OK {'checkpoint': '/kaggle/working/vit_transreid_msmt.pth', 'loaded_tensor_count': 152, 'target_tensor_count': 152, 'mismatch_count': 0, 'resized_pos_embed': {'source_shape': [1, 211, 768], 'target_shape': [1, 129, 768], 'target_grid': [16, 8]}, 'source_sie_loaded': False, 'source_jpm_local_branches_loaded': False, 'global_jpm_branch_used_for_target_final_block': True, 'global_branch_mapped_tensor_count': 14, 'embedding_dim': 768, 'backbone_trainable': True, 'loaded_required': ['blocks.0.attn.qkv.weight', 'blocks.10.attn.qkv.weight', 'blocks.11.attn.qkv.weight', 'cls_token', 'norm.weight', 'patch_embed.proj.weight', 'pos_embed'], 'smoke_test': 'OK', 'feature_shape': [3, 768], 'init_qkv_max_abs': 0.0, 'global_final_qkv_max_abs': 0.0, 'qkv_grad_norm': 0.004050535149872303, 'patch_grad_norm': 0.019206363707780838, 'backbone_all_trainable': True, 'source_sie_used': False, 'source_jpm_local_branches_used': False, 'source_jpm_global_final_branch_used': True, 'target_stride': [16, 16]}

## 4. Pairing audit và state machine resume

Thứ tự ưu tiên vẫn là **E3 resume → E2 completed → E2 resume → E2 fresh**, nhưng chỉ checkpoint thuộc pipeline tag mới `e2_e3_transreid_init_trainable768_b24_v1` mới được auto-resume.

Điều này ngăn notebook vô tình lấy checkpoint của:
- UAD ImageNet-init cũ;
- frozen TransReID-JPM 3840-D;
- các experiment E2/E3 khác.

In [5]:
FILENAME_RE = re.compile(
    r"(?P<pid>\d+)_c(?P<camid>\d+)_m(?P<modid>\d+)_f(?P<frameid>\d+)",
    re.IGNORECASE,
)

PIPELINE_ROOT = Path("/kaggle/working/pvuad_runs") / PIPELINE_TAG
E2_RUN_DIR = PIPELINE_ROOT / "e2_final"
E3_RUN_DIR = PIPELINE_ROOT / "e3_tdh"
PIPELINE_ROOT.mkdir(parents=True, exist_ok=True)
E2_RUN_DIR.mkdir(parents=True, exist_ok=True)
E3_RUN_DIR.mkdir(parents=True, exist_ok=True)
PIPELINE_STATE_PATH = PIPELINE_ROOT / "pipeline_state.json"

INIT_AUDIT_SOURCE = Path("/kaggle/working/transreid_trainable_init_audit.json")
INIT_AUDIT_DEST = PIPELINE_ROOT / "transreid_trainable_init_audit.json"
if INIT_AUDIT_SOURCE.is_file() and not INIT_AUDIT_DEST.is_file():
    shutil.copy2(INIT_AUDIT_SOURCE, INIT_AUDIT_DEST)


def read_json(path):
    path = Path(path)
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as error:
        print("Ignoring unreadable JSON:", path, error)
        return {}


def write_pipeline_state(status, active_stage, **extra):
    payload = {
        "pipeline": PIPELINE_NAME,
        "pipeline_tag": PIPELINE_TAG,
        "status": status,
        "active_stage": active_stage,
        "updated_at_unix": _time.time(),
        "notebook_started_unix": NOTEBOOK_SESSION_STARTED_UNIX,
        "session_deadline_unix": SESSION_DEADLINE_UNIX,
        "remaining_minutes": max(
            0.0, (SESSION_DEADLINE_UNIX - _time.time()) / 60.0
        ),
        **extra,
    }
    temporary = PIPELINE_STATE_PATH.with_suffix(".json.tmp")
    temporary.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    os.replace(temporary, PIPELINE_STATE_PATH)
    return payload


def remaining_minutes():
    return max(0.0, (SESSION_DEADLINE_UNIX - _time.time()) / 60.0)


def copy_if_present(source_dir, destination_dir, filenames):
    if source_dir is None:
        return
    source_dir = Path(source_dir)
    destination_dir = Path(destination_dir)
    destination_dir.mkdir(parents=True, exist_ok=True)
    for filename in filenames:
        source_path = source_dir / filename
        destination_path = destination_dir / filename
        if source_path.is_file() and source_path.resolve() != destination_path.resolve():
            if not destination_path.exists():
                print("Preserving:", filename)
                shutil.copy2(source_path, destination_path)


def status_progress(status):
    return status.get("progress") or {}


def candidate_sort_key(candidate):
    status = candidate["status"]
    progress = status_progress(status)
    path_text = str(candidate["root"]).lower()
    return (
        int(PIPELINE_TAG.lower() in path_text),
        int(status.get("status") == "completed"),
        int(progress.get("epoch") or 0),
        int(bool(progress.get("epoch_complete", False))),
        int(progress.get("next_iteration") or 0),
        int(status.get("global_step") or 0),
        float(status.get("saved_at_unix") or candidate["checkpoint"].stat().st_mtime),
    )


def scan_stage_candidates(base, experiment):
    base = Path(base)
    if not base.exists():
        return []
    candidates = []
    for root, dirs, files in os.walk(base):
        root_path = Path(root)
        if root_path.name.lower() in IMAGE_SPLITS:
            dirs[:] = []
            continue
        if "pvuad_last_checkpoint.pth" not in files:
            continue
        checkpoint = root_path / "pvuad_last_checkpoint.pth"
        status = read_json(root_path / "session_status.json")
        summary = read_json(root_path / "training_summary.json")
        manifest = read_json(root_path / "run_manifest.json")
        declared = status.get("experiment", summary.get("experiment"))
        lowered = str(root_path).lower()
        legacy_match = (
            experiment == "E2" and "final_e2" in lowered
        ) or (
            experiment == "E3-TDH" and "e3_tdh" in lowered
        )
        if declared != experiment and not legacy_match:
            continue
        if status.get("stage", summary.get("stage")) not in (None, "final"):
            continue
        # Reject a manifest that clearly belongs to a different batch/LR
        # recipe. Missing legacy fields are tolerated, but contradictory
        # fields are not.
        recipe = manifest.get("recipe") or manifest.get("effective_training") or {}
        expected = (
            {"global_batch": E2_GLOBAL_BATCH, "epochs": E2_EPOCHS}
            if experiment == "E2"
            else {"global_batch": E3_GLOBAL_BATCH, "epochs": E3_EPOCHS}
        )
        incompatible = any(
            key in recipe and int(recipe[key]) != int(value)
            for key, value in expected.items()
        )
        lr_value = recipe.get("base_lr", recipe.get("backbone_lr"))
        expected_lr = E2_BASE_LR if experiment == "E2" else E3_BASE_LR
        if lr_value is not None and abs(float(lr_value) - expected_lr) > 1e-12:
            incompatible = True
        if incompatible:
            print("Skipping incompatible stage candidate:", root_path)
            continue
        candidates.append({
            "root": root_path,
            "checkpoint": checkpoint,
            "model": root_path / "pvuad_best_model.pth",
            "status": status,
            "summary": summary,
            "manifest": manifest,
        })
        dirs[:] = []
    return sorted(candidates, key=candidate_sort_key, reverse=True)


def candidate_table(candidates, label):
    if not candidates:
        return
    print(label)
    display(pd.DataFrame([{
        "root": str(item["root"]),
        "status": item["status"].get("status", "legacy_checkpoint"),
        "epoch": status_progress(item["status"]).get("epoch"),
        "next_iteration": status_progress(item["status"]).get("next_iteration"),
        "global_step": item["status"].get("global_step"),
        "best_mAP": item["status"].get("best_mAP_percent"),
        "selected": index == 0,
    } for index, item in enumerate(candidates)]))


# Pairing audit is invariant across sessions. Reuse a validated cached CSV when
# available; otherwise compute it once from the official train split.
PAIRING_AUDIT_PATH = PIPELINE_ROOT / "pairing_audit.csv"
cached_audits = []
if RUN_METADATA_PAIRING_CHECK and not PAIRING_AUDIT_PATH.is_file():
    for root, dirs, files in os.walk("/kaggle/input"):
        root_path = Path(root)
        if root_path.name.lower() in IMAGE_SPLITS:
            dirs[:] = []
            continue
        if "pairing_audit.csv" in files:
            cached_audits.append(root_path / "pairing_audit.csv")

pairing_frame = None
for cached in sorted(cached_audits, key=lambda item: str(item)):
    try:
        frame = pd.read_csv(cached)
        required = {"pid", "paired_frames", "ground", "aerial"}
        if len(frame) == 500 and required.issubset(frame.columns):
            if frame["paired_frames"].ge(1).all():
                pairing_frame = frame
                shutil.copy2(cached, PAIRING_AUDIT_PATH)
                print("Reused pairing audit:", cached)
                break
    except Exception:
        pass

if RUN_METADATA_PAIRING_CHECK and pairing_frame is None:
    keys_by_modality = {}
    for expected_modid, modality in enumerate(MODALITIES, start=1):
        by_pid = defaultdict(set)
        for path in sorted((DATA_ROOT / "train" / modality).glob("*.jpg")):
            match = FILENAME_RE.search(path.stem)
            if match is None:
                raise ValueError(f"Unexpected filename: {path.name}")
            pid = int(match.group("pid"))
            camid = int(match.group("camid"))
            modid = int(match.group("modid"))
            frameid = int(match.group("frameid"))
            if modid != expected_modid:
                raise ValueError(f"Folder/modality mismatch: {path}")
            by_pid[pid].add((camid, frameid))
        keys_by_modality[modality] = by_pid

    pids = sorted(set.intersection(*[set(mapping) for mapping in keys_by_modality.values()]))
    pairing_rows = []
    for pid in pids:
        common = set.intersection(*[
            keys_by_modality[modality][pid] for modality in MODALITIES
        ])
        ground = sum(camid <= 5 for camid, _frameid in common)
        aerial = sum(camid >= 6 for camid, _frameid in common)
        pairing_rows.append((pid, len(common), ground, aerial))
    pairing_frame = pd.DataFrame(
        pairing_rows, columns=["pid", "paired_frames", "ground", "aerial"]
    )
    pairing_frame["view_coverage"] = np.select(
        [
            pairing_frame["ground"].gt(0) & pairing_frame["aerial"].gt(0),
            pairing_frame["ground"].gt(0),
            pairing_frame["aerial"].gt(0),
        ],
        ["Ground+Aerial", "Ground-only", "Aerial-only"],
        default="No paired frame",
    )
    if len(pairing_frame) != 500:
        raise RuntimeError(f"Expected 500 train IDs, got {len(pairing_frame)}")
    no_pairs = pairing_frame.loc[
        pairing_frame["paired_frames"].eq(0), "pid"
    ].tolist()
    if no_pairs:
        raise RuntimeError(f"IDs without a complete RGB/NIR/TIR frame: {no_pairs[:20]}")
    pairing_frame.to_csv(PAIRING_AUDIT_PATH, index=False)

if pairing_frame is not None:
    if "view_coverage" not in pairing_frame.columns:
        pairing_frame["view_coverage"] = np.select(
            [
                pairing_frame["ground"].gt(0) & pairing_frame["aerial"].gt(0),
                pairing_frame["ground"].gt(0),
                pairing_frame["aerial"].gt(0),
            ],
            ["Ground+Aerial", "Ground-only", "Aerial-only"],
            default="No paired frame",
        )
    print("IDs with complete modality coverage:", len(pairing_frame))
    display(
        pairing_frame["view_coverage"]
        .value_counts(dropna=False)
        .rename_axis("view_coverage")
        .reset_index(name="identities")
    )
    # Ground-only/Aerial-only identities are valid WHU-MARS data. The sampler
    # falls back safely because STRICT_PAIRED_DATA remains False.


if E3_RESUME_PATH_OVERRIDE:
    E3_CANDIDATES = [{
        "root": Path(E3_RESUME_PATH_OVERRIDE).parent,
        "checkpoint": Path(E3_RESUME_PATH_OVERRIDE),
        "model": Path(E3_RESUME_PATH_OVERRIDE).parent / "pvuad_best_model.pth",
        "status": read_json(Path(E3_RESUME_PATH_OVERRIDE).parent / "session_status.json"),
        "summary": {},
        "manifest": read_json(Path(E3_RESUME_PATH_OVERRIDE).parent / "run_manifest.json"),
    }]
else:
    E3_CANDIDATES = scan_stage_candidates(E3_RUN_DIR, "E3-TDH")
    if AUTO_RESUME:
        external_e3 = scan_stage_candidates("/kaggle/input", "E3-TDH")
        external_e3 = [
            item for item in external_e3
            if PIPELINE_TAG.lower() in str(item["root"]).lower()
        ]
        E3_CANDIDATES += external_e3
        unique = {str(item["checkpoint"]): item for item in E3_CANDIDATES}
        E3_CANDIDATES = sorted(unique.values(), key=candidate_sort_key, reverse=True)

if E2_RESUME_PATH_OVERRIDE:
    E2_CANDIDATES = [{
        "root": Path(E2_RESUME_PATH_OVERRIDE).parent,
        "checkpoint": Path(E2_RESUME_PATH_OVERRIDE),
        "model": Path(E2_RESUME_PATH_OVERRIDE).parent / "pvuad_best_model.pth",
        "status": read_json(Path(E2_RESUME_PATH_OVERRIDE).parent / "session_status.json"),
        "summary": {},
        "manifest": read_json(Path(E2_RESUME_PATH_OVERRIDE).parent / "run_manifest.json"),
    }]
else:
    E2_CANDIDATES = scan_stage_candidates(E2_RUN_DIR, "E2")
    if AUTO_RESUME:
        external_e2 = scan_stage_candidates("/kaggle/input", "E2")
        if not ALLOW_LEGACY_E2_BOOTSTRAP:
            external_e2 = [
                item for item in external_e2
                if PIPELINE_TAG.lower() in str(item["root"]).lower()
            ]
        E2_CANDIDATES += external_e2
        unique = {str(item["checkpoint"]): item for item in E2_CANDIDATES}
        E2_CANDIDATES = sorted(unique.values(), key=candidate_sort_key, reverse=True)

if E2_COMPLETED_DIR_OVERRIDE:
    override_root = Path(E2_COMPLETED_DIR_OVERRIDE)
    E2_CANDIDATES.insert(0, {
        "root": override_root,
        "checkpoint": override_root / "pvuad_last_checkpoint.pth",
        "model": override_root / "pvuad_best_model.pth",
        "status": read_json(override_root / "session_status.json"),
        "summary": read_json(override_root / "training_summary.json"),
        "manifest": read_json(override_root / "run_manifest.json"),
    })

candidate_table(E3_CANDIDATES, "E3 resume candidates (highest priority):")
candidate_table(E2_CANDIDATES, "E2 candidates:")

SELECTED_E3 = E3_CANDIDATES[0] if E3_CANDIDATES else None
SELECTED_E2 = E2_CANDIDATES[0] if E2_CANDIDATES else None

# Preserve compact E2 evidence even when a completed legacy E2 is used only as
# the warm-start for E3. Large model/checkpoint files stay at their selected
# input path until E3 has created its self-contained teacher/resume artifacts.
if SELECTED_E2 is not None:
    copy_if_present(
        SELECTED_E2["root"], E2_RUN_DIR,
        [
            "metrics_history.csv", "session_status.json", "training_summary.json",
            "pairing_audit.csv", "ablation_summary.csv", "effective_command.txt",
        ],
    )

if SELECTED_E3 is not None:
    ACTIVE_STAGE = "E3"
elif SELECTED_E2 is not None and SELECTED_E2["status"].get("status") == "completed":
    ACTIVE_STAGE = "E3"
elif SELECTED_E2 is not None:
    ACTIVE_STAGE = "E2"
else:
    ACTIVE_STAGE = "E2"

print("Selected pipeline stage:", ACTIVE_STAGE)
write_pipeline_state(
    "ready", ACTIVE_STAGE,
    selected_e2=str(SELECTED_E2["root"]) if SELECTED_E2 else None,
    selected_e3=str(SELECTED_E3["root"]) if SELECTED_E3 else None,
)

(PIPELINE_ROOT / "RESUME_NEXT_SESSION.txt").write_text(
    "PV-UAD TransReID-init trainable E2 -> E3 multi-session pipeline\n\n"
    "1. A partial session ends normally with e2_paused or e3_paused.\n"
    "2. Start every run with Save Version -> Save & Run All; Kaggle then commits "
    "the output automatically after this notebook exits cleanly.\n"
    "3. In a new session, add the immediately preceding version output as Input.\n"
    "4. Use this exact notebook, keep Settings unchanged, and Run All.\n"
    "5. The state machine resumes E3 first, otherwise completed/partial E2.\n\n"
    f"Pipeline folder: pvuad_runs/{PIPELINE_TAG}\n",
    encoding="utf-8",
)
print("Pipeline output:", PIPELINE_ROOT)

Reused pairing audit: /kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/pairing_audit.csv
IDs with complete modality coverage: 500

   view_coverage  identities
0    Ground-only         284
1  Ground+Aerial         216

E2 candidates:

,root,status,epoch,next_iteration,global_step,best_mAP,selected
0,/kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-...,completed,60,0,91710,11.665469,True

Preserving: metrics_history.csv
Preserving: session_status.json
Preserving: training_summary.json
Preserving: effective_command.txt
Selected pipeline stage: E3
Pipeline output: /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1

## 5. Chạy E2 → E3-TDH → flip-TTA

**Fresh E2:** load pretrained TransReID vào UAD ViT 768-D rồi train toàn bộ backbone trên WHU-MARS.  
**E2 resume:** không load TransReID lại; resume chính xác optimizer/model/RNG từ checkpoint.  
**E3:** warm-start từ E2 tốt nhất và dùng lại full TIR local/global vì backbone vẫn là trainable ViT có patch tokens.  
**Final:** standard evaluation + horizontal-flip TTA, không re-ranking.

Mỗi phiên dùng chung guard 10.5 giờ và checkpoint định kỳ để chạy qua nhiều Kaggle sessions.

In [6]:
environment = os.environ.copy()
environment.update({
    "CUDA_VISIBLE_DEVICES": ",".join(map(str, range(NUM_GPUS))),
    "PYTHONPATH": str(UAD_DIR) + os.pathsep + environment.get("PYTHONPATH", ""),
    "PYTHONUNBUFFERED": "1",
    "OMP_NUM_THREADS": "2",
    "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True",
    "TORCH_NCCL_ASYNC_ERROR_HANDLING": "1",
})


def stage_status(run_dir):
    return read_json(Path(run_dir) / "session_status.json")


def display_stage_status(name, status):
    progress = status_progress(status)
    display(pd.DataFrame([{
        "stage": name,
        "status": status.get("status"),
        "reason": status.get("reason"),
        "epoch": progress.get("epoch"),
        "next_iteration": progress.get("next_iteration"),
        "epoch_complete": progress.get("epoch_complete"),
        "global_step": status.get("global_step"),
        "best_mAP": status.get("best_mAP_percent"),
        "remaining_minutes": round(remaining_minutes(), 1),
    }]))


def run_command_checked(command, run_dir, stage_name):
    command_text = shlex.join(command)
    (Path(run_dir) / "effective_command.txt").write_text(
        command_text + "\n", encoding="utf-8"
    )
    print("\nLaunching", stage_name)
    print(command_text)
    if not RUN_TRAINING:
        print("RUN_TRAINING=False — command prepared but not launched.")
        return {}
    result = subprocess.run(command, cwd=UAD_DIR, env=environment, check=False)
    if result.returncode != 0:
        write_pipeline_state(
            "failed", stage_name,
            returncode=result.returncode,
            run_dir=str(run_dir),
        )
        raise subprocess.CalledProcessError(result.returncode, command)
    required = [
        Path(run_dir) / "pvuad_last_checkpoint.pth",
        Path(run_dir) / "session_status.json",
    ]
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise RuntimeError(f"{stage_name} ended without required outputs: {missing}")
    status = stage_status(run_dir)
    if status.get("status") not in {
        "paused_time_limit", "completed", "running_checkpoint"
    }:
        raise RuntimeError(f"Unexpected {stage_name} status: {status}")
    display_stage_status(stage_name, status)
    return status


def make_stage_manifest(run_dir, stage_name, recipe, resume_path=None, **extra):
    payload = {
        "pipeline": PIPELINE_NAME,
        "pipeline_tag": PIPELINE_TAG,
        "stage_name": stage_name,
        "recipe": recipe,
        "dataset_variant": DATASET_VARIANT,
        "dataset_root": str(DATA_ROOT),
        "dataset_counts": coverage_rows,
        "source_commit": PINNED_UAD_COMMIT,
        "overlay_sha256": OVERLAY_HASHES,
        "resume_path": str(resume_path) if resume_path else None,
        "python": sys.version,
        "torch": torch.__version__,
        "cuda": torch.version.cuda,
        "gpus": gpu_rows,
        "seed": RANDOM_SEED,
        "session_guard": {
            "notebook_started_unix": NOTEBOOK_SESSION_STARTED_UNIX,
            "session_deadline_unix": SESSION_DEADLINE_UNIX,
            "hard_stop_hours": SESSION_HARD_STOP_HOURS,
            "stop_reserve_minutes": SESSION_STOP_RESERVE_MINUTES,
            "checkpoint_every_minutes": CHECKPOINT_EVERY_MINUTES,
            "time_check_every_steps": TIME_CHECK_EVERY_STEPS,
            "min_eval_remaining_minutes": MIN_EVAL_REMAINING_MINUTES,
        },
        **extra,
    }
    manifest_path = Path(run_dir) / "run_manifest.json"
    manifest_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    shutil.copy2(
        UAD_DIR / "PVUAD_patch_manifest.json",
        Path(run_dir) / "PVUAD_patch_manifest.json",
    )
    return manifest_path


def e2_command(resume_path, strict_resume=True):
    # Fresh E2 receives pretrained TransReID backbone initialization exactly
    # once. Resume sessions reconstruct the model from the saved UAD checkpoint,
    # so they must NOT apply the source initialization again.
    pretrain_choice = "none" if resume_path else "transreid"
    recipe = {
        "experiment": "E2", "stage": "final", "epochs": E2_EPOCHS,
        "global_batch": E2_GLOBAL_BATCH, "base_lr": E2_BASE_LR,
        "paired_view_sampler": True, "vfproca": True,
        "local_consistency": False, "hard_gpd": False,
        "initialization": "MSMT17_TransReID_trainable_backbone",
        "pretrain_choice_this_session": pretrain_choice,
        "embedding_dim": 768,
        "backbone_stride": [16, 16],
        "source_sie_used": False,
        "source_jpm_local_branches_used": False,
        "source_jpm_global_final_branch_used": True,
    }
    manifest_path = make_stage_manifest(
        E2_RUN_DIR, "E2", recipe, resume_path=resume_path
    )
    opts = [
        "MODEL.DIST_TRAIN", "True",
        "MODEL.PRETRAIN_CHOICE", pretrain_choice,
        "MODEL.PRETRAIN_PATH", str(PRETRAIN_PATH),
        "MODEL.STRIDE_SIZE", "[16, 16]",
        "MODEL.SIE_CAMERA", "False",
        "MODEL.SIE_VIEW", "False",
        "DATASETS.ROOT_DIR", str(DATA_LINK_PARENT),
        "DATALOADER.NUM_WORKERS", str(NUM_WORKERS),
        "SOLVER.SEED", str(RANDOM_SEED),
        "SOLVER.MAX_EPOCHS", str(E2_EPOCHS),
        "SOLVER.IMS_PER_BATCH", str(E2_GLOBAL_BATCH),
        "SOLVER.BASE_LR", str(E2_BASE_LR),
        "SOLVER.EVAL_PERIOD", "10",
        "SOLVER.CHECKPOINT_PERIOD", "5",
        "TEST.IMS_PER_BATCH", "256",
        "TEST.RE_RANKING", "False",
        "TEST.TOP_K_EVAL", "0",
        "OUTPUT_DIR", str(E2_RUN_DIR),
        "PVUAD.EXPERIMENT", "E2",
        "PVUAD.STAGE", "final",
        "PVUAD.DEV_MODE", "False",
        "PVUAD.PAIRED_VIEW_SAMPLER", "True",
        "PVUAD.STRICT_PAIRED_DATA", "False",
        "PVUAD.VFPROCA", "True",
        "MODEL.PCA_LOSS_WEIGHT", "0.01",
        "PVUAD.VIEW_ALIGNMENT_WEIGHT", "0.5",
        "PVUAD.INVARIANT_ID_WEIGHT", "0.5",
        "PVUAD.SCENARIO_CLS_WEIGHT", "0.1",
        "PVUAD.TEST_INVARIANT_BLEND", "0.5",
        "PVUAD.LOCAL_CONSISTENCY", "False",
        "PVUAD.SYNC_PAIRED_AUG", "False",
        "PVUAD.HARD_GPD", "False",
        "PVUAD.FINETUNE", "False",
        "PVUAD.TIR_DISTILLATION", "False",
        "PVUAD.FEATURE_PRESERVE_WEIGHT", "0.0",
        "PVUAD.SCENARIO_HARD_GPD", "False",
        "PVUAD.FINAL_FLIP_TTA", "False",
        "PVUAD.SAVE_LAST_EVERY", "5",
        "PVUAD.RUN_MANIFEST", str(manifest_path),
        "PVUAD.SESSION_DEADLINE_UNIX", str(float(SESSION_DEADLINE_UNIX)),
        "PVUAD.STOP_RESERVE_MINUTES", str(float(SESSION_STOP_RESERVE_MINUTES)),
        "PVUAD.CHECKPOINT_EVERY_MINUTES", str(float(CHECKPOINT_EVERY_MINUTES)),
        "PVUAD.TIME_CHECK_EVERY_STEPS", str(int(TIME_CHECK_EVERY_STEPS)),
        "PVUAD.MIN_EVAL_REMAINING_MINUTES", str(float(MIN_EVAL_REMAINING_MINUTES)),
        "PVUAD.STRICT_RESUME_CONFIG", str(bool(strict_resume)),
    ]
    if resume_path:
        opts += ["PVUAD.RESUME_PATH", str(resume_path)]
    return [
        sys.executable, "-m", "torch.distributed.run", "--standalone",
        f"--nproc_per_node={NUM_GPUS}", "train.py", "--config_file",
        "configs/PVUAD.yml", *opts,
    ]


E2_STATUS = SELECTED_E2["status"] if SELECTED_E2 else {}
E2_RESUME_PATH = None
E2_MODEL_PATH = None
E2_CHECKPOINT_PATH = None
E2_STRICT_RESUME = True
E2_COMPLETED_THIS_SESSION = False

if ACTIVE_STAGE == "E2":
    if SELECTED_E2 is not None:
        E2_RESUME_PATH = SELECTED_E2["checkpoint"]
        selected_hashes = (
            SELECTED_E2.get("manifest", {}).get("overlay_sha256") or {}
        )
        selected_processor_hash = selected_hashes.get("processor/processor.py")
        current_processor_hash = OVERLAY_HASHES.get("processor/processor.py")
        # E2 v2.3 checkpoints predate E3's gated fields in the resume
        # signature. Their known E2 structure is compatible; disable only the
        # signature-key comparison while retaining strict state_dict/optimizer
        # structural loading. New combined checkpoints remain fully strict.
        if (
            selected_processor_hash
            and selected_processor_hash != current_processor_hash
        ):
            E2_STRICT_RESUME = False
            print(
                "Known legacy E2 overlay detected; structural resume checks "
                "remain enabled, signature-only strictness is relaxed."
            )
        copy_if_present(
            SELECTED_E2["root"], E2_RUN_DIR,
            [
                "metrics_history.csv", "pvuad_best_model.pth",
                "pairing_audit.csv", "ablation_summary.csv",
                "training_summary.json",
            ],
        )
    else:
        print("No checkpoint found: starting E2 from pretrained TransReID ViT weights; backbone is TRAINABLE.")

    write_pipeline_state(
        "e2_running", "E2",
        resume_path=str(E2_RESUME_PATH) if E2_RESUME_PATH else None,
    )
    E2_STATUS = run_command_checked(
        e2_command(E2_RESUME_PATH, E2_STRICT_RESUME), E2_RUN_DIR, "E2"
    )
    if not RUN_TRAINING:
        write_pipeline_state("dry_run", "E2")
    elif E2_STATUS.get("status") in {"paused_time_limit", "running_checkpoint"}:
        write_pipeline_state(
            "e2_paused", "E2", e2_status=E2_STATUS,
            next_action="Attach this output to a new session and Run All.",
        )
        print("E2 PAUSED SAFELY. Save Version and continue in a new session.")
    elif E2_STATUS.get("status") == "completed":
        E2_MODEL_PATH = E2_RUN_DIR / "pvuad_best_model.pth"
        E2_CHECKPOINT_PATH = E2_RUN_DIR / "pvuad_last_checkpoint.pth"
        required = [E2_MODEL_PATH, E2_CHECKPOINT_PATH, E2_RUN_DIR / "metrics_history.csv"]
        missing = [str(path) for path in required if not path.is_file()]
        if missing:
            raise RuntimeError(f"Completed E2 is missing: {missing}")
        E2_COMPLETED_THIS_SESSION = True
        ACTIVE_STAGE = "E3"
else:
    if SELECTED_E2 is not None:
        E2_MODEL_PATH = SELECTED_E2["model"]
        E2_CHECKPOINT_PATH = SELECTED_E2["checkpoint"]


def create_teacher_cache(source_model, destination):
    source_model = Path(source_model)
    destination = Path(destination)
    if destination.is_file():
        return destination
    if not source_model.is_file():
        raise FileNotFoundError(source_model)
    try:
        payload = torch.load(source_model, map_location="cpu", weights_only=False)
    except TypeError:
        payload = torch.load(source_model, map_location="cpu")
    if isinstance(payload, dict) and "model" in payload:
        payload = payload["model"]
    elif isinstance(payload, dict) and "state_dict" in payload:
        payload = payload["state_dict"]
    if not isinstance(payload, dict):
        raise ValueError("E2 model file does not contain a state dictionary")
    teacher_state = {}
    for key, value in payload.items():
        clean = str(key).replace("module.", "")
        teacher_state[clean] = value.half() if torch.is_floating_point(value) else value
    temporary = destination.with_suffix(".pth.tmp")
    torch.save(teacher_state, temporary)
    os.replace(temporary, destination)
    del payload, teacher_state
    return destination


E3_STATUS = SELECTED_E3["status"] if SELECTED_E3 else {}
E3_RESUME_PATH = SELECTED_E3["checkpoint"] if SELECTED_E3 else None
TEACHER_CACHE = E3_RUN_DIR / "e2_teacher_model_fp16.pth"

if SELECTED_E3 is not None:
    copy_if_present(
        SELECTED_E3["root"], E3_RUN_DIR,
        [
            "metrics_history.csv", "pvuad_best_model.pth", "pvuad_last_model.pth",
            "e2_teacher_model_fp16.pth", "tta_metrics.csv",
            "training_summary.json", "TRAINING_COMPLETE_BEFORE_TTA.json",
            "FINAL_TTA_FAILED.txt", "effective_test_command.txt",
        ],
    )


def e3_command(resume_path, student_model, prototype_checkpoint, teacher_cache):
    recipe = {
        "experiment": "E3-TDH", "stage": "final", "epochs": E3_EPOCHS,
        "global_batch": E3_GLOBAL_BATCH, "backbone_lr": E3_BASE_LR,
        "head_lr_multiplier": E3_HEAD_LR_MULTIPLIER,
        "tir_global_weight": TIR_GLOBAL_WEIGHT,
        "tir_local_weight": TIR_LOCAL_WEIGHT,
        "feature_preserve_weight": FEATURE_PRESERVE_WEIGHT,
        "scenario_hard_weight": SCENARIO_HARD_WEIGHT,
        "initialization_origin": "MSMT17_TransReID_then_WHUMARS_E2",
        "embedding_dim": 768,
        "backbone_stride": [16, 16],
    }
    manifest_path = make_stage_manifest(
        E3_RUN_DIR, "E3-TDH", recipe, resume_path=resume_path,
        e2_model_path=str(E2_MODEL_PATH) if E2_MODEL_PATH else None,
        e2_checkpoint_path=str(E2_CHECKPOINT_PATH) if E2_CHECKPOINT_PATH else None,
        teacher_model_path=str(teacher_cache),
    )
    opts = [
        "MODEL.DIST_TRAIN", "True",
        "MODEL.PRETRAIN_CHOICE", "none",
        "MODEL.PRETRAIN_PATH", str(PRETRAIN_PATH),
        "MODEL.STRIDE_SIZE", "[16, 16]",
        "MODEL.SIE_CAMERA", "False",
        "MODEL.SIE_VIEW", "False",
        "DATASETS.ROOT_DIR", str(DATA_LINK_PARENT),
        "DATALOADER.NUM_WORKERS", str(NUM_WORKERS),
        "SOLVER.SEED", str(RANDOM_SEED),
        "SOLVER.MAX_EPOCHS", str(E3_EPOCHS),
        "SOLVER.IMS_PER_BATCH", str(E3_GLOBAL_BATCH),
        "SOLVER.BASE_LR", str(E3_BASE_LR),
        "SOLVER.WARMUP_EPOCHS", "1",
        "SOLVER.EVAL_PERIOD", "5",
        "SOLVER.CHECKPOINT_PERIOD", "5",
        "INPUT.RE_PROB", "0.0",
        "TEST.IMS_PER_BATCH", "256",
        "TEST.RE_RANKING", "False",
        "TEST.TOP_K_EVAL", "0",
        "OUTPUT_DIR", str(E3_RUN_DIR),
        "PVUAD.EXPERIMENT", "E3-TDH",
        "PVUAD.STAGE", "final",
        "PVUAD.DEV_MODE", "False",
        "PVUAD.PAIRED_VIEW_SAMPLER", "True",
        "PVUAD.STRICT_PAIRED_DATA", "False",
        "PVUAD.SYNC_PAIRED_AUG", "True",
        "PVUAD.VFPROCA", "True",
        "MODEL.PCA_LOSS_WEIGHT", "0.01",
        "PVUAD.VIEW_ALIGNMENT_WEIGHT", "0.5",
        "PVUAD.INVARIANT_ID_WEIGHT", "0.5",
        "PVUAD.SCENARIO_CLS_WEIGHT", "0.1",
        "PVUAD.TEST_INVARIANT_BLEND", "0.5",
        "PVUAD.LOCAL_CONSISTENCY", "False",
        "PVUAD.HARD_GPD", "False",
        "PVUAD.FINETUNE", "True",
        "PVUAD.WARMSTART_MODEL_PATH", str(student_model),
        "PVUAD.WARMSTART_PROTOTYPE_PATH", (
            str(prototype_checkpoint) if prototype_checkpoint else ""
        ),
        "PVUAD.TEACHER_MODEL_PATH", str(teacher_cache),
        "PVUAD.HEAD_LR_MULTIPLIER", str(float(E3_HEAD_LR_MULTIPLIER)),
        "PVUAD.TIR_DISTILLATION", "True",
        "PVUAD.TIR_GLOBAL_WEIGHT", str(float(TIR_GLOBAL_WEIGHT)),
        "PVUAD.TIR_LOCAL_WEIGHT", str(float(TIR_LOCAL_WEIGHT)),
        "PVUAD.TIR_LOCAL_KEEP_RATIO", str(float(TIR_LOCAL_KEEP_RATIO)),
        "PVUAD.FEATURE_PRESERVE_WEIGHT", str(float(FEATURE_PRESERVE_WEIGHT)),
        "PVUAD.SCENARIO_HARD_GPD", "True",
        "PVUAD.SCENARIO_HARD_WEIGHT", str(float(SCENARIO_HARD_WEIGHT)),
        "PVUAD.SCENARIO_HARD_TOPK", str(int(SCENARIO_HARD_TOPK)),
        "PVUAD.SCENARIO_HARD_MARGIN", str(float(SCENARIO_HARD_MARGIN)),
        "PVUAD.SCENARIO_HARD_TAU", str(float(SCENARIO_HARD_TAU)),
        "PVUAD.SCENARIO_HARD_START_EPOCH", str(int(SCENARIO_HARD_START_EPOCH)),
        "PVUAD.SCENARIO_BANK_MOMENTUM", "0.2",
        "PVUAD.FINAL_FLIP_TTA", "False",
        "PVUAD.SAVE_LAST_EVERY", "5",
        "PVUAD.RUN_MANIFEST", str(manifest_path),
        "PVUAD.SESSION_DEADLINE_UNIX", str(float(SESSION_DEADLINE_UNIX)),
        "PVUAD.STOP_RESERVE_MINUTES", str(float(SESSION_STOP_RESERVE_MINUTES)),
        "PVUAD.CHECKPOINT_EVERY_MINUTES", str(float(CHECKPOINT_EVERY_MINUTES)),
        "PVUAD.TIME_CHECK_EVERY_STEPS", str(int(TIME_CHECK_EVERY_STEPS)),
        "PVUAD.MIN_EVAL_REMAINING_MINUTES", str(float(MIN_EVAL_REMAINING_MINUTES)),
        "PVUAD.STRICT_RESUME_CONFIG", "True",
    ]
    if resume_path:
        opts += ["PVUAD.RESUME_PATH", str(resume_path)]
    return [
        sys.executable, "-m", "torch.distributed.run", "--standalone",
        f"--nproc_per_node={NUM_GPUS}", "train.py", "--config_file",
        "configs/PVUAD.yml", *opts,
    ]


can_enter_e3 = (
    ACTIVE_STAGE == "E3"
    and (E3_STATUS.get("status") != "completed")
    and RUN_TRAINING
)
if (
    can_enter_e3
    and E2_COMPLETED_THIS_SESSION
    and ALWAYS_START_E3_IN_NEW_SESSION
):
    write_pipeline_state(
        "e2_completed_e3_pending", "E3",
        e2_status=E2_STATUS,
        remaining_minutes=remaining_minutes(),
        next_action=(
            "Kaggle will save this completed E2 output. Attach it to a new "
            "session and use Save & Run All; E3 will start automatically."
        ),
    )
    print(
        "E2 COMPLETE. This Kaggle version now ends cleanly by design. "
        "Attach its output to the next session; E3 will start there."
    )
    can_enter_e3 = False
elif can_enter_e3 and remaining_minutes() < MIN_E3_START_REMAINING_MINUTES:
    pending_status = "e3_paused" if E3_RESUME_PATH else "e2_completed_e3_pending"
    write_pipeline_state(
        pending_status, "E3",
        e2_status=E2_STATUS,
        remaining_minutes=remaining_minutes(),
        next_action="Save Version; attach this output and Run All in a new session.",
    )
    print(
        "Only {:.1f} minutes remain. E3 will start/resume in the next "
        "session.".format(remaining_minutes())
    )
    can_enter_e3 = False

if can_enter_e3:
    if E3_RESUME_PATH is not None:
        teacher_source = (
            SELECTED_E3["root"] / "e2_teacher_model_fp16.pth"
        )
        if not teacher_source.is_file() and E2_MODEL_PATH is not None:
            teacher_source = E2_MODEL_PATH
        if not TEACHER_CACHE.is_file():
            if teacher_source.name == "e2_teacher_model_fp16.pth":
                shutil.copy2(teacher_source, TEACHER_CACHE)
            else:
                create_teacher_cache(teacher_source, TEACHER_CACHE)
        student_model = TEACHER_CACHE
        prototype_checkpoint = None
    else:
        if E2_MODEL_PATH is None or not Path(E2_MODEL_PATH).is_file():
            raise FileNotFoundError(
                "E3 needs a completed E2 pvuad_best_model.pth. Attach the "
                "previous combined/E2 output or use E2_COMPLETED_DIR_OVERRIDE."
            )
        if E2_CHECKPOINT_PATH is None or not Path(E2_CHECKPOINT_PATH).is_file():
            raise FileNotFoundError(
                "E3 needs E2 pvuad_last_checkpoint.pth for prototype warm-start."
            )
        create_teacher_cache(E2_MODEL_PATH, TEACHER_CACHE)
        student_model = E2_MODEL_PATH
        prototype_checkpoint = E2_CHECKPOINT_PATH

    print("Frozen E2 teacher:", TEACHER_CACHE)
    write_pipeline_state(
        "e3_running", "E3",
        e2_status=E2_STATUS,
        e3_resume_path=str(E3_RESUME_PATH) if E3_RESUME_PATH else None,
    )
    E3_STATUS = run_command_checked(
        e3_command(
            E3_RESUME_PATH, student_model, prototype_checkpoint, TEACHER_CACHE
        ),
        E3_RUN_DIR,
        "E3-TDH",
    )
    if E3_STATUS.get("status") in {"paused_time_limit", "running_checkpoint"}:
        write_pipeline_state(
            "e3_paused", "E3", e2_status=E2_STATUS, e3_status=E3_STATUS,
            next_action="Attach this output to a new session and Run All.",
        )
        print("E3 PAUSED SAFELY. Save Version and continue in a new session.")


def run_final_tta(best_model):
    test_opts = [
        "MODEL.DIST_TRAIN", "False",
        "MODEL.PRETRAIN_CHOICE", "none",
        "MODEL.PRETRAIN_PATH", str(PRETRAIN_PATH),
        "MODEL.STRIDE_SIZE", "[16, 16]",
        "MODEL.SIE_CAMERA", "False",
        "MODEL.SIE_VIEW", "False",
        "DATASETS.ROOT_DIR", str(DATA_LINK_PARENT),
        "DATALOADER.NUM_WORKERS", str(NUM_WORKERS),
        "TEST.IMS_PER_BATCH", "256",
        "TEST.RE_RANKING", "False",
        "TEST.TOP_K_EVAL", "0",
        "TEST.WEIGHT", str(best_model),
        "OUTPUT_DIR", str(E3_RUN_DIR),
        "PVUAD.EXPERIMENT", "E3-TDH",
        "PVUAD.STAGE", "final",
        "PVUAD.DEV_MODE", "False",
        "PVUAD.PAIRED_VIEW_SAMPLER", "True",
        "PVUAD.STRICT_PAIRED_DATA", "False",
        "PVUAD.VFPROCA", "True",
        "PVUAD.TEST_INVARIANT_BLEND", "0.5",
        "PVUAD.TIR_DISTILLATION", "True",
        "PVUAD.FEATURE_PRESERVE_WEIGHT", "0.0",
        "PVUAD.SCENARIO_HARD_GPD", "True",
        "PVUAD.FINAL_FLIP_TTA", "True",
    ]
    test_command = [
        sys.executable, "test.py", "--config_file", "configs/PVUAD.yml",
        *test_opts,
    ]
    (E3_RUN_DIR / "effective_test_command.txt").write_text(
        shlex.join(test_command) + "\n", encoding="utf-8"
    )
    (E3_RUN_DIR / "TRAINING_COMPLETE_BEFORE_TTA.json").write_text(
        json.dumps({
            "status": "training_complete",
            "best_model": str(best_model),
            "last_checkpoint": str(E3_RUN_DIR / "pvuad_last_checkpoint.pth"),
            "tta_pending": True,
        }, indent=2),
        encoding="utf-8",
    )
    print("Running final standard + horizontal-flip TTA evaluation...")
    result = subprocess.run(
        test_command, cwd=UAD_DIR, env=environment, check=False
    )
    tta_metrics_path = E3_RUN_DIR / "tta_metrics.csv"
    if result.returncode != 0 or not tta_metrics_path.is_file():
        warning = (
            "Final TTA failed after E3 training completed; checkpoints remain valid. "
            f"returncode={result.returncode}. Attach this output to retry TTA only."
        )
        (E3_RUN_DIR / "FINAL_TTA_FAILED.txt").write_text(
            warning + "\n", encoding="utf-8"
        )
        print("WARNING:", warning)
        return False
    (E3_RUN_DIR / "TRAINING_COMPLETE_BEFORE_TTA.json").write_text(
        json.dumps({
            "status": "training_and_tta_complete",
            "best_model": str(best_model),
            "tta_pending": False,
        }, indent=2),
        encoding="utf-8",
    )
    failed_marker = E3_RUN_DIR / "FINAL_TTA_FAILED.txt"
    if failed_marker.is_file():
        failed_marker.unlink()
    return True


E3_COMPLETED = E3_STATUS.get("status") == "completed"
if E3_COMPLETED:
    # When completion came from an attached output, preserve its full checkpoint
    # so the newly saved combined output remains independently resumable.
    if SELECTED_E3 is not None:
        copy_if_present(
            SELECTED_E3["root"], E3_RUN_DIR,
            ["pvuad_last_checkpoint.pth", "session_status.json"],
        )
    best_model = E3_RUN_DIR / "pvuad_best_model.pth"
    if not best_model.is_file() and SELECTED_E3 is not None:
        copy_if_present(
            SELECTED_E3["root"], E3_RUN_DIR, ["pvuad_best_model.pth"]
        )
    if not best_model.is_file():
        raise FileNotFoundError("Completed E3 is missing pvuad_best_model.pth")

    tta_path = E3_RUN_DIR / "tta_metrics.csv"
    if not tta_path.is_file() and RUN_FINAL_FLIP_TTA:
        if remaining_minutes() >= MIN_TTA_START_REMAINING_MINUTES:
            tta_ok = run_final_tta(best_model)
        else:
            tta_ok = False
            print(
                "E3 training is complete, but only {:.1f} minutes remain; "
                "TTA will run next session.".format(remaining_minutes())
            )
    else:
        tta_ok = tta_path.is_file()

    final_status = "completed" if (tta_ok or not RUN_FINAL_FLIP_TTA) else "e3_complete_tta_pending"
    write_pipeline_state(
        final_status, "DONE" if final_status == "completed" else "TTA",
        e2_status=E2_STATUS,
        e3_status=E3_STATUS,
        tta_complete=bool(tta_ok),
        next_action=(
            None if final_status == "completed"
            else "Attach this output and Run All; training will be skipped and TTA retried."
        ),
    )
elif ACTIVE_STAGE == "E3" and not can_enter_e3 and not RUN_TRAINING:
    write_pipeline_state("dry_run", "E3")

Frozen E2 teacher: /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/e2_teacher_model_fp16.pth

Launching E3-TDH
/usr/bin/python3 -m torch.distributed.run --standalone --nproc_per_node=2 train.py --config_file configs/PVUAD.yml MODEL.DIST_TRAIN True MODEL.PRETRAIN_CHOICE none MODEL.PRETRAIN_PATH /kaggle/working/vit_transreid_msmt.pth MODEL.STRIDE_SIZE '[16, 16]' MODEL.SIE_CAMERA False MODEL.SIE_VIEW False DATASETS.ROOT_DIR /kaggle/working/pvuad_data DATALOADER.NUM_WORKERS 4 SOLVER.SEED 1234 SOLVER.MAX_EPOCHS 25 SOLVER.IMS_PER_BATCH 24 SOLVER.BASE_LR 0.0001 SOLVER.WARMUP_EPOCHS 1 SOLVER.EVAL_PERIOD 5 SOLVER.CHECKPOINT_PERIOD 5 INPUT.RE_PROB 0.0 TEST.IMS_PER_BATCH 256 TEST.RE_RANKING False TEST.TOP_K_EVAL 0 OUTPUT_DIR /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh PVUAD.EXPERIMENT E3-TDH PVUAD.STAGE final PVUAD.DEV_MODE False PVUAD.PAIRED_VIEW_SAMPLER True PVUAD.STRICT_PAIRED_DATA False PVUAD.SYNC_PAIRED_AUG True PVUAD.VFPROCA True MODEL.PCA_LOSS_WEIGHT 0.01 PVUAD.VIEW_ALIGNMENT_WEIGHT 0.5 PVUAD.INVARIANT_ID_WEIGHT 0.5 PVUAD.SCENARIO_CLS_WEIGHT 0.1 PVUAD.TEST_INVARIANT_BLEND 0.5 PVUAD.LOCAL_CONSISTENCY False PVUAD.HARD_GPD False PVUAD.FINETUNE True PVUAD.WARMSTART_MODEL_PATH /kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e2_final/pvuad_best_model.pth PVUAD.WARMSTART_PROTOTYPE_PATH /kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e2_final/pvuad_last_checkpoint.pth PVUAD.TEACHER_MODEL_PATH /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/e2_teacher_model_fp16.pth PVUAD.HEAD_LR_MULTIPLIER 5.0 PVUAD.TIR_DISTILLATION True PVUAD.TIR_GLOBAL_WEIGHT 0.1 PVUAD.TIR_LOCAL_WEIGHT 0.03 PVUAD.TIR_LOCAL_KEEP_RATIO 0.5 PVUAD.FEATURE_PRESERVE_WEIGHT 0.05 PVUAD.SCENARIO_HARD_GPD True PVUAD.SCENARIO_HARD_WEIGHT 0.15 PVUAD.SCENARIO_HARD_TOPK 5 PVUAD.SCENARIO_HARD_MARGIN 0.05 PVUAD.SCENARIO_HARD_TAU 0.05 PVUAD.SCENARIO_HARD_START_EPOCH 3 PVUAD.SCENARIO_BANK_MOMENTUM 0.2 PVUAD.FINAL_FLIP_TTA False PVUAD.SAVE_LAST_EVERY 5 PVUAD.RUN_MANIFEST /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/run_manifest.json PVUAD.SESSION_DEADLINE_UNIX 1788973459.7964337 PVUAD.STOP_RESERVE_MINUTES 15.0 PVUAD.CHECKPOINT_EVERY_MINUTES 30.0 PVUAD.TIME_CHECK_EVERY_STEPS 10 PVUAD.MIN_EVAL_REMAINING_MINUTES 35.0 PVUAD.STRICT_RESUME_CONFIG True

[W909 06:47:57.340452833 socket.cpp:207] [c10d] The hostname of the client socket cannot be retrieved. err=-3

2026-09-09 06:48:11,845 transreid INFO: Saving model in the path :/kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh
2026-09-09 06:48:11,845 transreid INFO: Namespace(config_file='configs/PVUAD.yml', opts=['MODEL.DIST_TRAIN', 'True', 'MODEL.PRETRAIN_CHOICE', 'none', 'MODEL.PRETRAIN_PATH', '/kaggle/working/vit_transreid_msmt.pth', 'MODEL.STRIDE_SIZE', '[16, 16]', 'MODEL.SIE_CAMERA', 'False', 'MODEL.SIE_VIEW', 'False', 'DATASETS.ROOT_DIR', '/kaggle/working/pvuad_data', 'DATALOADER.NUM_WORKERS', '4', 'SOLVER.SEED', '1234', 'SOLVER.MAX_EPOCHS', '25', 'SOLVER.IMS_PER_BATCH', '24', 'SOLVER.BASE_LR', '0.0001', 'SOLVER.WARMUP_EPOCHS', '1', 'SOLVER.EVAL_PERIOD', '5', 'SOLVER.CHECKPOINT_PERIOD', '5', 'INPUT.RE_PROB', '0.0', 'TEST.IMS_PER_BATCH', '256', 'TEST.RE_RANKING', 'False', 'TEST.TOP_K_EVAL', '0', 'OUTPUT_DIR', '/kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh', 'PVUAD.EXPERIMENT', 'E3-TDH', 'PVUAD.STAGE', 'final', 'PVUAD.DEV_MODE', 'False', 'PVUAD.PAIRED_VIEW_SAMPLER', 'True', 'PVUAD.STRICT_PAIRED_DATA', 'False', 'PVUAD.SYNC_PAIRED_AUG', 'True', 'PVUAD.VFPROCA', 'True', 'MODEL.PCA_LOSS_WEIGHT', '0.01', 'PVUAD.VIEW_ALIGNMENT_WEIGHT', '0.5', 'PVUAD.INVARIANT_ID_WEIGHT', '0.5', 'PVUAD.SCENARIO_CLS_WEIGHT', '0.1', 'PVUAD.TEST_INVARIANT_BLEND', '0.5', 'PVUAD.LOCAL_CONSISTENCY', 'False', 'PVUAD.HARD_GPD', 'False', 'PVUAD.FINETUNE', 'True', 'PVUAD.WARMSTART_MODEL_PATH', '/kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e2_final/pvuad_best_model.pth', 'PVUAD.WARMSTART_PROTOTYPE_PATH', '/kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e2_final/pvuad_last_checkpoint.pth', 'PVUAD.TEACHER_MODEL_PATH', '/kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/e2_teacher_model_fp16.pth', 'PVUAD.HEAD_LR_MULTIPLIER', '5.0', 'PVUAD.TIR_DISTILLATION', 'True', 'PVUAD.TIR_GLOBAL_WEIGHT', '0.1', 'PVUAD.TIR_LOCAL_WEIGHT', '0.03', 'PVUAD.TIR_LOCAL_KEEP_RATIO', '0.5', 'PVUAD.FEATURE_PRESERVE_WEIGHT', '0.05', 'PVUAD.SCENARIO_HARD_GPD', 'True', 'PVUAD.SCENARIO_HARD_WEIGHT', '0.15', 'PVUAD.SCENARIO_HARD_TOPK', '5', 'PVUAD.SCENARIO_HARD_MARGIN', '0.05', 'PVUAD.SCENARIO_HARD_TAU', '0.05', 'PVUAD.SCENARIO_HARD_START_EPOCH', '3', 'PVUAD.SCENARIO_BANK_MOMENTUM', '0.2', 'PVUAD.FINAL_FLIP_TTA', 'False', 'PVUAD.SAVE_LAST_EVERY', '5', 'PVUAD.RUN_MANIFEST', '/kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/run_manifest.json', 'PVUAD.SESSION_DEADLINE_UNIX', '1788973459.7964337', 'PVUAD.STOP_RESERVE_MINUTES', '15.0', 'PVUAD.CHECKPOINT_EVERY_MINUTES', '30.0', 'PVUAD.TIME_CHECK_EVERY_STEPS', '10', 'PVUAD.MIN_EVAL_REMAINING_MINUTES', '35.0', 'PVUAD.STRICT_RESUME_CONFIG', 'True'], local_rank=0)
2026-09-09 06:48:11,845 transreid INFO: Loaded configuration file configs/PVUAD.yml
2026-09-09 06:48:11,846 transreid INFO: Running with config:
DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 4
  SAMPLER: PKM
DATASETS:
  MODALITIES: ('RGB', 'IR', 'Thermal')
  NAMES: WHU-MARS
  ROOT_DIR: /kaggle/working/pvuad_data
INPUT:
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  PROB: 0.5
  RE_PROB: 0.0
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MODEL:
  ATT_DROP_RATE: 0.0
  COS_LAYER: False
  DEVICE: cuda
  DEVICE_ID: 0
  DEVIDE_LENGTH: 4
  DIST_TRAIN: True
  DROP_OUT: 0.0
  DROP_PATH: 0.1
  GPD_MOMENTUM: 0.2
  ID_LOSS_TYPE: softmax
  ID_LOSS_WEIGHT: 1.0
  IF_LABELSMOOTH: off
  IF_WITH_CENTER: no
  JPM: False
  LAST_STRIDE: 1
  METRIC_LOSS_TYPE: wrt
  NAME: transformer
  NECK: bnneck
  NO_MARGIN: True
  PCA_LOSS_WEIGHT: 0.01
  PRETRAIN_CHOICE: none
  PRETRAIN_PATH: /kaggle/working/vit_transreid_msmt.pth
  RE_ARRANGE: True
  SHIFT_NUM: 5
  SHUFFLE_GROUP: 2
  SIE_CAMERA: False
  SIE_COE: 3.0
  SIE_VIEW: False
  STRIDE_SIZE: [16, 16]
  TRANSFORMER_TYPE: vit_base_in
  TRIPLET_LOSS_WEIGHT: 1.0
OUTPUT_DIR: /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh
PVUAD:
  CHECKPOINT_EVERY_MINUTES: 30.0
  DEV_MODE: False
  DEV_QUERY_PER_PID_CAM: 1
  DEV_SPLIT_SEED: 2026
  DEV_VAL_IDS: 100
  EXPERIMENT: E3-TDH
  FEATURE_PRESERVE_WEIGHT: 0.05
  FINAL_FLIP_TTA: False
  FINETUNE: True
  GROUND_MAX_CAMID: 4
  HARD_GPD: False
  HARD_GPD_MARGIN: 0.1
  HARD_GPD_START_EPOCH: 10
  HARD_GPD_TOPK: 10
  HARD_GPD_WEIGHT: 0.5
  HEAD_LR_MULTIPLIER: 5.0
  INVARIANT_ID_WEIGHT: 0.5
  LOCAL_CONSISTENCY: False
  LOCAL_CONSISTENCY_WEIGHT: 0.05
  METRICS_FILENAME: metrics_history.csv
  MIN_EVAL_REMAINING_MINUTES: 35.0
  PAIRED_VIEW_SAMPLER: True
  RESUME_PATH:
  RUN_MANIFEST: /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/run_manifest.json
  SAVE_BEST: True
  SAVE_LAST_EVERY: 5
  SCENARIO_BANK_MOMENTUM: 0.2
  SCENARIO_CLS_WEIGHT: 0.1
  SCENARIO_HARD_GPD: True
  SCENARIO_HARD_MARGIN: 0.05
  SCENARIO_HARD_START_EPOCH: 3
  SCENARIO_HARD_TAU: 0.05
  SCENARIO_HARD_TOPK: 5
  SCENARIO_HARD_WEIGHT: 0.15
  SESSION_DEADLINE_UNIX: 1788973459.7964337
  STAGE: final
  STATUS_FILENAME: session_status.json
  STOP_RESERVE_MINUTES: 15.0
  STRICT_PAIRED_DATA: False
  STRICT_RESUME_CONFIG: True
  SYNC_PAIRED_AUG: True
  TEACHER_MODEL_PATH: /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/e2_teacher_model_fp16.pth
  TEST_INVARIANT_BLEND: 0.5
  TIME_CHECK_EVERY_STEPS: 10
  TIR_DISTILLATION: True
  TIR_GLOBAL_WEIGHT: 0.1
  TIR_LOCAL_KEEP_RATIO: 0.5
  TIR_LOCAL_WEIGHT: 0.03
  TTA_METRICS_FILENAME: tta_metrics.csv
  VFPROCA: True
  VIEW_ALIGNMENT_WEIGHT: 0.5
  WARMSTART_MODEL_PATH: /kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e2_final/pvuad_best_model.pth
  WARMSTART_PROTOTYPE_PATH: /kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e2_final/pvuad_last_checkpoint.pth
SOLVER:
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 2
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 5
  COSINE_MARGIN: 0.5
  COSINE_SCALE: 30
  EVAL_PERIOD: 5
  GAMMA: 0.1
  IMS_PER_BATCH: 24
  LARGE_FC_LR: False
  LOG_PERIOD: 50
  LOSS_TYPE: base+pca+gpd
  MARGIN: 0.3
  MAX_EPOCHS: 25
  MOMENTUM: 0.9
  OPTIMIZER_NAME: SGD
  SEED: 1234
  STEPS: (40, 70)
  WARMUP_EPOCHS: 1
  WARMUP_FACTOR: 0.01
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
TEST:
  DIST_MAT: dist_mat.npy
  EVAL: True
  FEAT_NORM: yes
  IMS_PER_BATCH: 256
  NECK_FEAT: before
  RE_RANKING: False
  TOP_K_EVAL: 0
  WEIGHT:
2026-09-09 06:48:11,852 transreid INFO: Saving model in the path :/kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh
2026-09-09 06:48:11,853 transreid INFO: Namespace(config_file='configs/PVUAD.yml', opts=['MODEL.DIST_TRAIN', 'True', 'MODEL.PRETRAIN_CHOICE', 'none', 'MODEL.PRETRAIN_PATH', '/kaggle/working/vit_transreid_msmt.pth', 'MODEL.STRIDE_SIZE', '[16, 16]', 'MODEL.SIE_CAMERA', 'False', 'MODEL.SIE_VIEW', 'False', 'DATASETS.ROOT_DIR', '/kaggle/working/pvuad_data', 'DATALOADER.NUM_WORKERS', '4', 'SOLVER.SEED', '1234', 'SOLVER.MAX_EPOCHS', '25', 'SOLVER.IMS_PER_BATCH', '24', 'SOLVER.BASE_LR', '0.0001', 'SOLVER.WARMUP_EPOCHS', '1', 'SOLVER.EVAL_PERIOD', '5', 'SOLVER.CHECKPOINT_PERIOD', '5', 'INPUT.RE_PROB', '0.0', 'TEST.IMS_PER_BATCH', '256', 'TEST.RE_RANKING', 'False', 'TEST.TOP_K_EVAL', '0', 'OUTPUT_DIR', '/kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh', 'PVUAD.EXPERIMENT', 'E3-TDH', 'PVUAD.STAGE', 'final', 'PVUAD.DEV_MODE', 'False', 'PVUAD.PAIRED_VIEW_SAMPLER', 'True', 'PVUAD.STRICT_PAIRED_DATA', 'False', 'PVUAD.SYNC_PAIRED_AUG', 'True', 'PVUAD.VFPROCA', 'True', 'MODEL.PCA_LOSS_WEIGHT', '0.01', 'PVUAD.VIEW_ALIGNMENT_WEIGHT', '0.5', 'PVUAD.INVARIANT_ID_WEIGHT', '0.5', 'PVUAD.SCENARIO_CLS_WEIGHT', '0.1', 'PVUAD.TEST_INVARIANT_BLEND', '0.5', 'PVUAD.LOCAL_CONSISTENCY', 'False', 'PVUAD.HARD_GPD', 'False', 'PVUAD.FINETUNE', 'True', 'PVUAD.WARMSTART_MODEL_PATH', '/kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e2_final/pvuad_best_model.pth', 'PVUAD.WARMSTART_PROTOTYPE_PATH', '/kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e2_final/pvuad_last_checkpoint.pth', 'PVUAD.TEACHER_MODEL_PATH', '/kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/e2_teacher_model_fp16.pth', 'PVUAD.HEAD_LR_MULTIPLIER', '5.0', 'PVUAD.TIR_DISTILLATION', 'True', 'PVUAD.TIR_GLOBAL_WEIGHT', '0.1', 'PVUAD.TIR_LOCAL_WEIGHT', '0.03', 'PVUAD.TIR_LOCAL_KEEP_RATIO', '0.5', 'PVUAD.FEATURE_PRESERVE_WEIGHT', '0.05', 'PVUAD.SCENARIO_HARD_GPD', 'True', 'PVUAD.SCENARIO_HARD_WEIGHT', '0.15', 'PVUAD.SCENARIO_HARD_TOPK', '5', 'PVUAD.SCENARIO_HARD_MARGIN', '0.05', 'PVUAD.SCENARIO_HARD_TAU', '0.05', 'PVUAD.SCENARIO_HARD_START_EPOCH', '3', 'PVUAD.SCENARIO_BANK_MOMENTUM', '0.2', 'PVUAD.FINAL_FLIP_TTA', 'False', 'PVUAD.SAVE_LAST_EVERY', '5', 'PVUAD.RUN_MANIFEST', '/kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/run_manifest.json', 'PVUAD.SESSION_DEADLINE_UNIX', '1788973459.7964337', 'PVUAD.STOP_RESERVE_MINUTES', '15.0', 'PVUAD.CHECKPOINT_EVERY_MINUTES', '30.0', 'PVUAD.TIME_CHECK_EVERY_STEPS', '10', 'PVUAD.MIN_EVAL_REMAINING_MINUTES', '35.0', 'PVUAD.STRICT_RESUME_CONFIG', 'True'], local_rank=1)
2026-09-09 06:48:11,853 transreid INFO: Loaded configuration file configs/PVUAD.yml

[W909 06:48:11.650158100 socket.cpp:207] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W909 06:48:11.656058056 socket.cpp:207] [c10d] The hostname of the client socket cannot be retrieved. err=-3

=> WHU-MARS loaded
=> WHU-MARS loaded
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   500 |    92133 |         7
  query    |   500 |     6405 |         7
  gallery  |   500 |    93609 |         7
  ----------------------------------------
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   500 |    92133 |         7
  query    |   500 |     6405 |         7
  gallery  |   500 |    93609 |         7
  ----------------------------------------
DIST_TRAIN START
DIST_TRAIN START
PairedViewPKM: 500 IDs (216 dual-view, 284 single-view), 37,148 paired sample slots/epoch, 3 PID x 4 instances per GPU
using Transformer_type: vit_base_in as a backbone
using stride: [16, 16], and patch number is num_y16 * num_x8
PairedViewPKM: 500 IDs (216 dual-view, 284 single-view), 37,148 paired sample slots/epoch, 3 PID x 4 instances per GPU
using Transformer_type: vit_base_in as a backbone
using stride: [16, 16], and patch number is num_y16 * num_x8
===========building transformer===========
using WRT loss for training
Fine-tune optimizer: backbone LR 1.000e-04, head multiplier 5.00, 10 parameter groups adjusted
2026-09-09 06:48:15,209 transreid.train INFO: start training
===========building transformer===========
using WRT loss for training
Fine-tune optimizer: backbone LR 1.000e-04, head multiplier 5.00, 10 parameter groups adjusted
2026-09-09 06:48:15,242 transreid.train INFO: start training
2026-09-09 06:48:16,405 transreid.train INFO: Loaded E2 warm-start model from /kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e2_final/pvuad_best_model.pth (173 tensors)
2026-09-09 06:48:16,456 transreid.train INFO: Loaded E2 warm-start model from /kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e2_final/pvuad_best_model.pth (173 tensors)
2026-09-09 06:48:20,257 transreid.train INFO: Loaded E2 global prototype bank from /kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e2_final/pvuad_last_checkpoint.pth
2026-09-09 06:48:20,257 transreid.train INFO: Loaded E2 global prototype bank from /kaggle/input/notebooks/liennnnnn/pvuad-e2-e3-transreid-init-trainable-kaggle-2xt4/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e2_final/pvuad_last_checkpoint.pth
2026-09-09 06:48:20,643 transreid.train INFO: Loaded frozen E2 teacher from /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/e2_teacher_model_fp16.pth (173 tensors)
2026-09-09 06:48:20,657 transreid.train INFO: Loaded frozen E2 teacher from /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/e2_teacher_model_fp16.pth (173 tensors)
2026-09-09 06:48:20,665 transreid.train INFO: Kaggle session guard: started 1788936495, hard deadline 1788973460, safe checkpoint stop 1788972560
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
2026-09-09 06:48:42,523 transreid.train INFO: Epoch[1] Iteration[50/1547] Loss 3.063 Acc 0.671 ID 1.590 TRI 0.143 Align 0.263 GPD 0.175 TIR-G 0.469 TIR-L 0.335 Keep 0.052 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:48:42,523 transreid.train INFO: Epoch[1] Iteration[50/1547] Loss 3.119 Acc 0.659 ID 1.642 TRI 0.119 Align 0.266 GPD 0.157 TIR-G 0.481 TIR-L 0.344 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:49:00,156 transreid.train INFO: Epoch[1] Iteration[100/1547] Loss 3.211 Acc 0.657 ID 1.675 TRI 0.136 Align 0.269 GPD 0.176 TIR-G 0.479 TIR-L 0.342 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:49:00,157 transreid.train INFO: Epoch[1] Iteration[100/1547] Loss 3.054 Acc 0.670 ID 1.581 TRI 0.133 Align 0.276 GPD 0.179 TIR-G 0.474 TIR-L 0.336 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:49:18,275 transreid.train INFO: Epoch[1] Iteration[150/1547] Loss 3.209 Acc 0.658 ID 1.673 TRI 0.140 Align 0.274 GPD 0.177 TIR-G 0.481 TIR-L 0.343 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:49:18,276 transreid.train INFO: Epoch[1] Iteration[150/1547] Loss 3.134 Acc 0.666 ID 1.627 TRI 0.142 Align 0.273 GPD 0.180 TIR-G 0.476 TIR-L 0.336 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:49:36,760 transreid.train INFO: Epoch[1] Iteration[200/1547] Loss 3.077 Acc 0.678 ID 1.593 TRI 0.138 Align 0.273 GPD 0.181 TIR-G 0.473 TIR-L 0.334 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:49:36,761 transreid.train INFO: Epoch[1] Iteration[200/1547] Loss 3.187 Acc 0.661 ID 1.665 TRI 0.138 Align 0.275 GPD 0.174 TIR-G 0.480 TIR-L 0.341 Keep 0.055 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:49:55,911 transreid.train INFO: Epoch[1] Iteration[250/1547] Loss 3.180 Acc 0.664 ID 1.649 TRI 0.141 Align 0.277 GPD 0.190 TIR-G 0.477 TIR-L 0.335 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:49:55,911 transreid.train INFO: Epoch[1] Iteration[250/1547] Loss 3.174 Acc 0.660 ID 1.657 TRI 0.139 Align 0.275 GPD 0.170 TIR-G 0.478 TIR-L 0.340 Keep 0.055 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:50:15,797 transreid.train INFO: Epoch[1] Iteration[300/1547] Loss 3.163 Acc 0.662 ID 1.652 TRI 0.138 Align 0.274 GPD 0.171 TIR-G 0.477 TIR-L 0.339 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:50:15,798 transreid.train INFO: Epoch[1] Iteration[300/1547] Loss 3.171 Acc 0.664 ID 1.644 TRI 0.139 Align 0.277 GPD 0.191 TIR-G 0.476 TIR-L 0.335 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:50:36,046 transreid.train INFO: Epoch[1] Iteration[350/1547] Loss 3.130 Acc 0.668 ID 1.632 TRI 0.137 Align 0.274 GPD 0.173 TIR-G 0.477 TIR-L 0.339 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:50:36,048 transreid.train INFO: Epoch[1] Iteration[350/1547] Loss 3.127 Acc 0.670 ID 1.622 TRI 0.137 Align 0.278 GPD 0.187 TIR-G 0.476 TIR-L 0.335 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:50:55,747 transreid.train INFO: Epoch[1] Iteration[400/1547] Loss 3.118 Acc 0.673 ID 1.617 TRI 0.135 Align 0.278 GPD 0.185 TIR-G 0.476 TIR-L 0.335 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:50:55,747 transreid.train INFO: Epoch[1] Iteration[400/1547] Loss 3.112 Acc 0.670 ID 1.621 TRI 0.135 Align 0.274 GPD 0.176 TIR-G 0.476 TIR-L 0.338 Keep 0.055 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:51:15,281 transreid.train INFO: Epoch[1] Iteration[450/1547] Loss 3.126 Acc 0.668 ID 1.630 TRI 0.137 Align 0.274 GPD 0.176 TIR-G 0.477 TIR-L 0.338 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:51:15,282 transreid.train INFO: Epoch[1] Iteration[450/1547] Loss 3.079 Acc 0.678 ID 1.596 TRI 0.133 Align 0.278 GPD 0.182 TIR-G 0.475 TIR-L 0.334 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:51:35,060 transreid.train INFO: Epoch[1] Iteration[500/1547] Loss 3.101 Acc 0.672 ID 1.617 TRI 0.136 Align 0.274 GPD 0.175 TIR-G 0.476 TIR-L 0.337 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:51:35,060 transreid.train INFO: Epoch[1] Iteration[500/1547] Loss 3.066 Acc 0.681 ID 1.589 TRI 0.133 Align 0.276 GPD 0.183 TIR-G 0.474 TIR-L 0.333 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:51:54,860 transreid.train INFO: Epoch[1] Iteration[550/1547] Loss 3.028 Acc 0.685 ID 1.571 TRI 0.132 Align 0.277 GPD 0.179 TIR-G 0.474 TIR-L 0.334 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:51:54,860 transreid.train INFO: Epoch[1] Iteration[550/1547] Loss 3.091 Acc 0.674 ID 1.610 TRI 0.136 Align 0.274 GPD 0.176 TIR-G 0.476 TIR-L 0.337 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:52:14,570 transreid.train INFO: Epoch[1] Iteration[600/1547] Loss 3.065 Acc 0.677 ID 1.597 TRI 0.135 Align 0.273 GPD 0.175 TIR-G 0.475 TIR-L 0.336 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:52:14,571 transreid.train INFO: Epoch[1] Iteration[600/1547] Loss 2.987 Acc 0.691 ID 1.549 TRI 0.131 Align 0.276 GPD 0.176 TIR-G 0.471 TIR-L 0.332 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:52:34,097 transreid.train INFO: Epoch[1] Iteration[650/1547] Loss 3.023 Acc 0.682 ID 1.573 TRI 0.133 Align 0.275 GPD 0.175 TIR-G 0.474 TIR-L 0.336 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:52:34,097 transreid.train INFO: Epoch[1] Iteration[650/1547] Loss 2.957 Acc 0.694 ID 1.534 TRI 0.129 Align 0.276 GPD 0.174 TIR-G 0.471 TIR-L 0.332 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:52:53,701 transreid.train INFO: Epoch[1] Iteration[700/1547] Loss 2.991 Acc 0.685 ID 1.557 TRI 0.131 Align 0.275 GPD 0.173 TIR-G 0.472 TIR-L 0.335 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:52:53,701 transreid.train INFO: Epoch[1] Iteration[700/1547] Loss 2.922 Acc 0.698 ID 1.515 TRI 0.128 Align 0.276 GPD 0.172 TIR-G 0.469 TIR-L 0.332 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:53:13,345 transreid.train INFO: Epoch[1] Iteration[750/1547] Loss 2.955 Acc 0.690 ID 1.538 TRI 0.130 Align 0.274 GPD 0.169 TIR-G 0.471 TIR-L 0.334 Keep 0.054 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:53:13,345 transreid.train INFO: Epoch[1] Iteration[750/1547] Loss 2.876 Acc 0.703 ID 1.492 TRI 0.126 Align 0.276 GPD 0.168 TIR-G 0.467 TIR-L 0.331 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:53:33,076 transreid.train INFO: Epoch[1] Iteration[800/1547] Loss 2.836 Acc 0.709 ID 1.472 TRI 0.125 Align 0.275 GPD 0.165 TIR-G 0.466 TIR-L 0.330 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:53:33,076 transreid.train INFO: Epoch[1] Iteration[800/1547] Loss 2.904 Acc 0.696 ID 1.512 TRI 0.128 Align 0.273 GPD 0.165 TIR-G 0.469 TIR-L 0.333 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:53:52,755 transreid.train INFO: Epoch[1] Iteration[850/1547] Loss 2.867 Acc 0.700 ID 1.493 TRI 0.127 Align 0.273 GPD 0.163 TIR-G 0.468 TIR-L 0.332 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:53:52,756 transreid.train INFO: Epoch[1] Iteration[850/1547] Loss 2.790 Acc 0.714 ID 1.447 TRI 0.124 Align 0.274 GPD 0.162 TIR-G 0.464 TIR-L 0.329 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:54:12,448 transreid.train INFO: Epoch[1] Iteration[900/1547] Loss 2.831 Acc 0.705 ID 1.474 TRI 0.127 Align 0.273 GPD 0.160 TIR-G 0.466 TIR-L 0.331 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:54:12,448 transreid.train INFO: Epoch[1] Iteration[900/1547] Loss 2.760 Acc 0.718 ID 1.431 TRI 0.124 Align 0.274 GPD 0.160 TIR-G 0.463 TIR-L 0.329 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:54:32,101 transreid.train INFO: Epoch[1] Iteration[950/1547] Loss 2.791 Acc 0.710 ID 1.452 TRI 0.126 Align 0.273 GPD 0.158 TIR-G 0.464 TIR-L 0.330 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:54:32,101 transreid.train INFO: Epoch[1] Iteration[950/1547] Loss 2.723 Acc 0.722 ID 1.411 TRI 0.123 Align 0.274 GPD 0.158 TIR-G 0.461 TIR-L 0.328 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:54:51,760 transreid.train INFO: Epoch[1] Iteration[1000/1547] Loss 2.683 Acc 0.727 ID 1.391 TRI 0.122 Align 0.273 GPD 0.155 TIR-G 0.459 TIR-L 0.327 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:54:51,760 transreid.train INFO: Epoch[1] Iteration[1000/1547] Loss 2.749 Acc 0.716 ID 1.430 TRI 0.125 Align 0.272 GPD 0.156 TIR-G 0.461 TIR-L 0.329 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:55:11,479 transreid.train INFO: Epoch[1] Iteration[1050/1547] Loss 2.699 Acc 0.722 ID 1.403 TRI 0.124 Align 0.271 GPD 0.153 TIR-G 0.459 TIR-L 0.328 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:55:11,479 transreid.train INFO: Epoch[1] Iteration[1050/1547] Loss 2.635 Acc 0.733 ID 1.365 TRI 0.120 Align 0.272 GPD 0.153 TIR-G 0.457 TIR-L 0.326 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:55:31,140 transreid.train INFO: Epoch[1] Iteration[1100/1547] Loss 2.648 Acc 0.728 ID 1.377 TRI 0.122 Align 0.271 GPD 0.150 TIR-G 0.457 TIR-L 0.327 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:55:31,140 transreid.train INFO: Epoch[1] Iteration[1100/1547] Loss 2.590 Acc 0.738 ID 1.341 TRI 0.119 Align 0.271 GPD 0.151 TIR-G 0.455 TIR-L 0.325 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:55:50,811 transreid.train INFO: Epoch[1] Iteration[1150/1547] Loss 2.596 Acc 0.734 ID 1.348 TRI 0.121 Align 0.270 GPD 0.146 TIR-G 0.454 TIR-L 0.326 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:55:50,812 transreid.train INFO: Epoch[1] Iteration[1150/1547] Loss 2.546 Acc 0.743 ID 1.318 TRI 0.119 Align 0.270 GPD 0.148 TIR-G 0.452 TIR-L 0.324 Keep 0.052 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:56:10,504 transreid.train INFO: Epoch[1] Iteration[1200/1547] Loss 2.489 Acc 0.750 ID 1.287 TRI 0.118 Align 0.269 GPD 0.143 TIR-G 0.449 TIR-L 0.323 Keep 0.052 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:56:10,505 transreid.train INFO: Epoch[1] Iteration[1200/1547] Loss 2.545 Acc 0.740 ID 1.321 TRI 0.120 Align 0.269 GPD 0.143 TIR-G 0.451 TIR-L 0.325 Keep 0.053 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:56:30,145 transreid.train INFO: Epoch[1] Iteration[1250/1547] Loss 2.486 Acc 0.746 ID 1.289 TRI 0.119 Align 0.268 GPD 0.139 TIR-G 0.448 TIR-L 0.323 Keep 0.052 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:56:30,147 transreid.train INFO: Epoch[1] Iteration[1250/1547] Loss 2.441 Acc 0.755 ID 1.261 TRI 0.117 Align 0.268 GPD 0.140 TIR-G 0.447 TIR-L 0.322 Keep 0.052 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:56:49,729 transreid.train INFO: Epoch[1] Iteration[1300/1547] Loss 2.431 Acc 0.753 ID 1.260 TRI 0.117 Align 0.267 GPD 0.135 TIR-G 0.445 TIR-L 0.322 Keep 0.052 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:56:49,730 transreid.train INFO: Epoch[1] Iteration[1300/1547] Loss 2.392 Acc 0.760 ID 1.235 TRI 0.117 Align 0.267 GPD 0.137 TIR-G 0.443 TIR-L 0.320 Keep 0.052 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:57:09,306 transreid.train INFO: Epoch[1] Iteration[1350/1547] Loss 2.338 Acc 0.767 ID 1.206 TRI 0.115 Align 0.266 GPD 0.133 TIR-G 0.440 TIR-L 0.318 Keep 0.052 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:57:09,306 transreid.train INFO: Epoch[1] Iteration[1350/1547] Loss 2.379 Acc 0.758 ID 1.232 TRI 0.116 Align 0.266 GPD 0.132 TIR-G 0.442 TIR-L 0.320 Keep 0.052 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:57:28,963 transreid.train INFO: Epoch[1] Iteration[1400/1547] Loss 2.319 Acc 0.765 ID 1.199 TRI 0.115 Align 0.264 GPD 0.128 TIR-G 0.438 TIR-L 0.318 Keep 0.052 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:57:28,964 transreid.train INFO: Epoch[1] Iteration[1400/1547] Loss 2.281 Acc 0.773 ID 1.175 TRI 0.113 Align 0.264 GPD 0.129 TIR-G 0.436 TIR-L 0.317 Keep 0.052 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:57:48,609 transreid.train INFO: Epoch[1] Iteration[1450/1547] Loss 2.263 Acc 0.771 ID 1.169 TRI 0.113 Align 0.262 GPD 0.124 TIR-G 0.434 TIR-L 0.316 Keep 0.052 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:57:48,610 transreid.train INFO: Epoch[1] Iteration[1450/1547] Loss 2.227 Acc 0.778 ID 1.146 TRI 0.112 Align 0.263 GPD 0.126 TIR-G 0.433 TIR-L 0.315 Keep 0.052 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:58:08,361 transreid.train INFO: Epoch[1] Iteration[1500/1547] Loss 2.207 Acc 0.777 ID 1.139 TRI 0.112 Align 0.260 GPD 0.120 TIR-G 0.430 TIR-L 0.314 Keep 0.051 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:58:08,361 transreid.train INFO: Epoch[1] Iteration[1500/1547] Loss 2.173 Acc 0.784 ID 1.117 TRI 0.111 Align 0.261 GPD 0.123 TIR-G 0.429 TIR-L 0.312 Keep 0.051 S-Hard 0.000 LR 9.96e-05
2026-09-09 06:58:19,797 transreid.train INFO: Epoch 1 done in 599.1s; loss 2.1418; acc 0.7877
2026-09-09 06:58:41,771 transreid.train INFO: Epoch[2] Iteration[50/1529] Loss 3.131 Acc 0.672 ID 1.625 TRI 0.135 Align 0.271 GPD 0.165 TIR-G 0.470 TIR-L 0.341 Keep 0.057 S-Hard 0.000 LR 9.84e-05
2026-09-09 06:58:41,771 transreid.train INFO: Epoch[2] Iteration[50/1529] Loss 3.429 Acc 0.621 ID 1.778 TRI 0.157 Align 0.270 GPD 0.227 TIR-G 0.471 TIR-L 0.343 Keep 0.058 S-Hard 0.000 LR 9.84e-05
2026-09-09 06:59:01,283 transreid.train INFO: Epoch[2] Iteration[100/1529] Loss 3.316 Acc 0.638 ID 1.725 TRI 0.137 Align 0.271 GPD 0.208 TIR-G 0.470 TIR-L 0.337 Keep 0.056 S-Hard 0.000 LR 9.84e-05
2026-09-09 06:59:01,283 transreid.train INFO: Epoch[2] Iteration[100/1529] Loss 3.122 Acc 0.668 ID 1.623 TRI 0.131 Align 0.269 GPD 0.168 TIR-G 0.470 TIR-L 0.339 Keep 0.056 S-Hard 0.000 LR 9.84e-05
2026-09-09 06:59:20,817 transreid.train INFO: Epoch[2] Iteration[150/1529] Loss 3.059 Acc 0.670 ID 1.593 TRI 0.127 Align 0.270 GPD 0.160 TIR-G 0.465 TIR-L 0.335 Keep 0.054 S-Hard 0.000 LR 9.84e-05
2026-09-09 06:59:20,817 transreid.train INFO: Epoch[2] Iteration[150/1529] Loss 3.300 Acc 0.642 ID 1.722 TRI 0.137 Align 0.271 GPD 0.198 TIR-G 0.468 TIR-L 0.335 Keep 0.054 S-Hard 0.000 LR 9.84e-05
2026-09-09 06:59:40,247 transreid.train INFO: Epoch[2] Iteration[200/1529] Loss 2.975 Acc 0.682 ID 1.546 TRI 0.123 Align 0.270 GPD 0.161 TIR-G 0.463 TIR-L 0.334 Keep 0.054 S-Hard 0.000 LR 9.84e-05
2026-09-09 06:59:40,248 transreid.train INFO: Epoch[2] Iteration[200/1529] Loss 3.263 Acc 0.646 ID 1.704 TRI 0.140 Align 0.269 GPD 0.186 TIR-G 0.468 TIR-L 0.335 Keep 0.054 S-Hard 0.000 LR 9.84e-05
2026-09-09 06:59:59,661 transreid.train INFO: Epoch[2] Iteration[250/1529] Loss 2.987 Acc 0.678 ID 1.555 TRI 0.124 Align 0.271 GPD 0.163 TIR-G 0.463 TIR-L 0.333 Keep 0.053 S-Hard 0.000 LR 9.84e-05
2026-09-09 06:59:59,661 transreid.train INFO: Epoch[2] Iteration[250/1529] Loss 3.234 Acc 0.650 ID 1.687 TRI 0.142 Align 0.269 GPD 0.188 TIR-G 0.468 TIR-L 0.335 Keep 0.054 S-Hard 0.000 LR 9.84e-05
2026-09-09 07:00:19,065 transreid.train INFO: Epoch[2] Iteration[300/1529] Loss 3.024 Acc 0.671 ID 1.575 TRI 0.125 Align 0.271 GPD 0.163 TIR-G 0.464 TIR-L 0.333 Keep 0.053 S-Hard 0.000 LR 9.84e-05
2026-09-09 07:00:19,066 transreid.train INFO: Epoch[2] Iteration[300/1529] Loss 3.156 Acc 0.660 ID 1.645 TRI 0.139 Align 0.269 GPD 0.182 TIR-G 0.466 TIR-L 0.332 Keep 0.053 S-Hard 0.000 LR 9.84e-05
2026-09-09 07:00:38,552 transreid.train INFO: Epoch[2] Iteration[350/1529] Loss 3.023 Acc 0.673 ID 1.571 TRI 0.129 Align 0.270 GPD 0.170 TIR-G 0.464 TIR-L 0.332 Keep 0.053 S-Hard 0.000 LR 9.84e-05
2026-09-09 07:00:38,552 transreid.train INFO: Epoch[2] Iteration[350/1529] Loss 3.156 Acc 0.660 ID 1.644 TRI 0.141 Align 0.270 GPD 0.181 TIR-G 0.467 TIR-L 0.333 Keep 0.053 S-Hard 0.000 LR 9.84e-05
2026-09-09 07:00:58,191 transreid.train INFO: Epoch[2] Iteration[400/1529] Loss 3.125 Acc 0.663 ID 1.628 TRI 0.139 Align 0.271 GPD 0.178 TIR-G 0.466 TIR-L 0.332 Keep 0.053 S-Hard 0.000 LR 9.84e-05
2026-09-09 07:00:58,191 transreid.train INFO: Epoch[2] Iteration[400/1529] Loss 3.029 Acc 0.674 ID 1.572 TRI 0.129 Align 0.270 GPD 0.174 TIR-G 0.464 TIR-L 0.332 Keep 0.053 S-Hard 0.000 LR 9.84e-05
2026-09-09 07:01:17,586 transreid.train INFO: Epoch[2] Iteration[450/1529] Loss 3.089 Acc 0.669 ID 1.609 TRI 0.136 Align 0.272 GPD 0.176 TIR-G 0.467 TIR-L 0.333 Keep 0.053 S-Hard 0.000 LR 9.84e-05
2026-09-09 07:01:17,587 transreid.train INFO: Epoch[2] Iteration[450/1529] Loss 3.009 Acc 0.679 ID 1.562 TRI 0.128 Align 0.271 GPD 0.175 TIR-G 0.464 TIR-L 0.332 Keep 0.053 S-Hard 0.000 LR 9.84e-05
2026-09-09 07:01:37,005 transreid.train INFO: Epoch[2] Iteration[500/1529] Loss 2.991 Acc 0.682 ID 1.554 TRI 0.127 Align 0.271 GPD 0.174 TIR-G 0.464 TIR-L 0.331 Keep 0.053 S-Hard 0.000 LR 9.84e-05
2026-09-09 07:01:37,005 transreid.train INFO: Epoch[2] Iteration[500/1529] Loss 3.053 Acc 0.674 ID 1.590 TRI 0.135 Align 0.272 GPD 0.174 TIR-G 0.466 TIR-L 0.332 Keep 0.053 S-Hard 0.000 LR 9.84e-05
2026-09-09 07:01:56,546 transreid.train INFO: Epoch[2] Iteration[550/1529] Loss 3.034 Acc 0.677 ID 1.580 TRI 0.134 Align 0.272 GPD 0.173 TIR-G 0.467 TIR-L 0.332 Keep 0.053 S-Hard 0.000 LR 9.84e-05
2026-09-09 07:01:56,547 transreid.train INFO: Epoch[2] Iteration[550/1529] Loss 2.977 Acc 0.683 ID 1.548 TRI 0.127 Align 0.270 GPD 0.171 TIR-G 0.464 TIR-L 0.331 Keep 0.053 S-Hard 0.000 LR 9.84e-05
2026-09-09 07:02:16,051 transreid.train INFO: Epoch[2] Iteration[600/1529] Loss 2.954 Acc 0.686 ID 1.538 TRI 0.126 Align 0.271 GPD 0.168 TIR-G 0.463 TIR-L 0.331 Keep 0.053 S-Hard 0.000 LR 9.84e-05

/usr/local/lib/python3.12/dist-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)

2026-09-09 07:18:25,681 transreid.train INFO: Epoch 3 done in 608.6s; loss 2.1765; acc 0.7806
2026-09-09 07:18:48,057 transreid.train INFO: Epoch[4] Iteration[50/1524] Loss 2.994 Acc 0.678 ID 1.559 TRI 0.138 Align 0.260 GPD 0.171 TIR-G 0.457 TIR-L 0.332 Keep 0.056 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:18:48,057 transreid.train INFO: Epoch[4] Iteration[50/1524] Loss 3.305 Acc 0.643 ID 1.722 TRI 0.160 Align 0.266 GPD 0.189 TIR-G 0.462 TIR-L 0.338 Keep 0.057 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:19:08,089 transreid.train INFO: Epoch[4] Iteration[100/1524] Loss 3.159 Acc 0.658 ID 1.643 TRI 0.147 Align 0.272 GPD 0.180 TIR-G 0.465 TIR-L 0.337 Keep 0.055 S-Hard 0.025 LR 9.38e-05
2026-09-09 07:19:08,089 transreid.train INFO: Epoch[4] Iteration[100/1524] Loss 3.043 Acc 0.670 ID 1.585 TRI 0.140 Align 0.267 GPD 0.167 TIR-G 0.456 TIR-L 0.331 Keep 0.055 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:19:27,648 transreid.train INFO: Epoch[4] Iteration[150/1524] Loss 3.092 Acc 0.672 ID 1.610 TRI 0.138 Align 0.268 GPD 0.179 TIR-G 0.464 TIR-L 0.335 Keep 0.054 S-Hard 0.026 LR 9.38e-05
2026-09-09 07:19:27,648 transreid.train INFO: Epoch[4] Iteration[150/1524] Loss 2.986 Acc 0.674 ID 1.555 TRI 0.131 Align 0.268 GPD 0.154 TIR-G 0.457 TIR-L 0.330 Keep 0.054 S-Hard 0.023 LR 9.38e-05
2026-09-09 07:19:47,354 transreid.train INFO: Epoch[4] Iteration[200/1524] Loss 3.103 Acc 0.671 ID 1.613 TRI 0.138 Align 0.270 GPD 0.186 TIR-G 0.466 TIR-L 0.334 Keep 0.054 S-Hard 0.026 LR 9.38e-05
2026-09-09 07:19:47,355 transreid.train INFO: Epoch[4] Iteration[200/1524] Loss 3.062 Acc 0.668 ID 1.594 TRI 0.132 Align 0.271 GPD 0.167 TIR-G 0.462 TIR-L 0.332 Keep 0.054 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:20:07,158 transreid.train INFO: Epoch[4] Iteration[250/1524] Loss 3.096 Acc 0.672 ID 1.609 TRI 0.139 Align 0.268 GPD 0.179 TIR-G 0.467 TIR-L 0.334 Keep 0.054 S-Hard 0.025 LR 9.38e-05
2026-09-09 07:20:07,158 transreid.train INFO: Epoch[4] Iteration[250/1524] Loss 3.050 Acc 0.667 ID 1.589 TRI 0.128 Align 0.272 GPD 0.164 TIR-G 0.461 TIR-L 0.330 Keep 0.054 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:20:26,845 transreid.train INFO: Epoch[4] Iteration[300/1524] Loss 3.067 Acc 0.665 ID 1.599 TRI 0.129 Align 0.272 GPD 0.165 TIR-G 0.464 TIR-L 0.331 Keep 0.054 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:20:26,845 transreid.train INFO: Epoch[4] Iteration[300/1524] Loss 3.058 Acc 0.675 ID 1.590 TRI 0.136 Align 0.268 GPD 0.173 TIR-G 0.467 TIR-L 0.333 Keep 0.054 S-Hard 0.025 LR 9.38e-05
2026-09-09 07:20:46,445 transreid.train INFO: Epoch[4] Iteration[350/1524] Loss 3.108 Acc 0.663 ID 1.619 TRI 0.133 Align 0.272 GPD 0.172 TIR-G 0.467 TIR-L 0.332 Keep 0.054 S-Hard 0.025 LR 9.38e-05
2026-09-09 07:20:46,445 transreid.train INFO: Epoch[4] Iteration[350/1524] Loss 3.015 Acc 0.683 ID 1.568 TRI 0.136 Align 0.267 GPD 0.167 TIR-G 0.465 TIR-L 0.333 Keep 0.054 S-Hard 0.025 LR 9.38e-05
2026-09-09 07:21:06,152 transreid.train INFO: Epoch[4] Iteration[400/1524] Loss 3.004 Acc 0.684 ID 1.561 TRI 0.133 Align 0.267 GPD 0.168 TIR-G 0.466 TIR-L 0.333 Keep 0.053 S-Hard 0.025 LR 9.38e-05
2026-09-09 07:21:06,152 transreid.train INFO: Epoch[4] Iteration[400/1524] Loss 3.061 Acc 0.667 ID 1.594 TRI 0.131 Align 0.272 GPD 0.168 TIR-G 0.466 TIR-L 0.332 Keep 0.054 S-Hard 0.025 LR 9.38e-05
2026-09-09 07:21:25,880 transreid.train INFO: Epoch[4] Iteration[450/1524] Loss 2.988 Acc 0.686 ID 1.552 TRI 0.135 Align 0.268 GPD 0.168 TIR-G 0.465 TIR-L 0.333 Keep 0.054 S-Hard 0.025 LR 9.38e-05
2026-09-09 07:21:25,880 transreid.train INFO: Epoch[4] Iteration[450/1524] Loss 3.023 Acc 0.673 ID 1.572 TRI 0.130 Align 0.273 GPD 0.167 TIR-G 0.467 TIR-L 0.332 Keep 0.054 S-Hard 0.025 LR 9.38e-05
2026-09-09 07:21:45,681 transreid.train INFO: Epoch[4] Iteration[500/1524] Loss 2.977 Acc 0.689 ID 1.546 TRI 0.135 Align 0.268 GPD 0.167 TIR-G 0.465 TIR-L 0.332 Keep 0.053 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:21:45,681 transreid.train INFO: Epoch[4] Iteration[500/1524] Loss 3.011 Acc 0.675 ID 1.565 TRI 0.129 Align 0.272 GPD 0.167 TIR-G 0.466 TIR-L 0.332 Keep 0.054 S-Hard 0.025 LR 9.38e-05
2026-09-09 07:22:05,325 transreid.train INFO: Epoch[4] Iteration[550/1524] Loss 2.969 Acc 0.689 ID 1.543 TRI 0.134 Align 0.267 GPD 0.165 TIR-G 0.464 TIR-L 0.332 Keep 0.054 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:22:05,325 transreid.train INFO: Epoch[4] Iteration[550/1524] Loss 2.986 Acc 0.679 ID 1.552 TRI 0.128 Align 0.272 GPD 0.167 TIR-G 0.466 TIR-L 0.331 Keep 0.054 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:22:24,940 transreid.train INFO: Epoch[4] Iteration[600/1524] Loss 2.929 Acc 0.694 ID 1.523 TRI 0.132 Align 0.267 GPD 0.162 TIR-G 0.463 TIR-L 0.332 Keep 0.054 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:22:24,940 transreid.train INFO: Epoch[4] Iteration[600/1524] Loss 2.948 Acc 0.684 ID 1.532 TRI 0.127 Align 0.272 GPD 0.166 TIR-G 0.465 TIR-L 0.332 Keep 0.054 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:22:44,567 transreid.train INFO: Epoch[4] Iteration[650/1524] Loss 2.934 Acc 0.687 ID 1.525 TRI 0.126 Align 0.271 GPD 0.166 TIR-G 0.465 TIR-L 0.331 Keep 0.054 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:22:44,567 transreid.train INFO: Epoch[4] Iteration[650/1524] Loss 2.881 Acc 0.700 ID 1.497 TRI 0.130 Align 0.267 GPD 0.159 TIR-G 0.462 TIR-L 0.331 Keep 0.053 S-Hard 0.023 LR 9.38e-05
2026-09-09 07:23:04,277 transreid.train INFO: Epoch[4] Iteration[700/1524] Loss 2.848 Acc 0.704 ID 1.481 TRI 0.129 Align 0.267 GPD 0.156 TIR-G 0.460 TIR-L 0.330 Keep 0.053 S-Hard 0.023 LR 9.38e-05
2026-09-09 07:23:04,277 transreid.train INFO: Epoch[4] Iteration[700/1524] Loss 2.924 Acc 0.688 ID 1.518 TRI 0.126 Align 0.271 GPD 0.168 TIR-G 0.465 TIR-L 0.331 Keep 0.054 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:23:24,148 transreid.train INFO: Epoch[4] Iteration[750/1524] Loss 2.880 Acc 0.695 ID 1.494 TRI 0.125 Align 0.270 GPD 0.167 TIR-G 0.463 TIR-L 0.330 Keep 0.054 S-Hard 0.024 LR 9.38e-05
2026-09-09 07:23:24,148 transreid.train INFO: Epoch[4] Iteration[750/1524] Loss 2.811 Acc 0.709 ID 1.461 TRI 0.128 Align 0.268 GPD 0.154 TIR-G 0.460 TIR-L 0.330 Keep 0.053 S-Hard 0.023 LR 9.38e-05
2026-09-09 07:23:43,847 transreid.train INFO: Epoch[4] Iteration[800/1524] Loss 2.852 Acc 0.699 ID 1.480 TRI 0.124 Align 0.269 GPD 0.165 TIR-G 0.462 TIR-L 0.330 Keep 0.054 S-Hard 0.023 LR 9.38e-05
2026-09-09 07:23:43,847 transreid.train INFO: Epoch[4] Iteration[800/1524] Loss 2.779 Acc 0.713 ID 1.443 TRI 0.126 Align 0.267 GPD 0.153 TIR-G 0.459 TIR-L 0.329 Keep 0.053 S-Hard 0.022 LR 9.38e-05
2026-09-09 07:24:03,567 transreid.train INFO: Epoch[4] Iteration[850/1524] Loss 2.739 Acc 0.717 ID 1.423 TRI 0.126 Align 0.267 GPD 0.150 TIR-G 0.457 TIR-L 0.329 Keep 0.053 S-Hard 0.022 LR 9.38e-05
2026-09-09 07:24:03,567 transreid.train INFO: Epoch[4] Iteration[850/1524] Loss 2.828 Acc 0.702 ID 1.468 TRI 0.124 Align 0.268 GPD 0.164 TIR-G 0.461 TIR-L 0.330 Keep 0.054 S-Hard 0.023 LR 9.38e-05
2026-09-09 07:24:23,164 transreid.train INFO: Epoch[4] Iteration[900/1524] Loss 2.718 Acc 0.721 ID 1.411 TRI 0.126 Align 0.267 GPD 0.150 TIR-G 0.456 TIR-L 0.328 Keep 0.053 S-Hard 0.022 LR 9.38e-05
2026-09-09 07:24:23,164 transreid.train INFO: Epoch[4] Iteration[900/1524] Loss 2.803 Acc 0.705 ID 1.455 TRI 0.123 Align 0.268 GPD 0.162 TIR-G 0.460 TIR-L 0.329 Keep 0.054 S-Hard 0.023 LR 9.38e-05
2026-09-09 07:24:42,919 transreid.train INFO: Epoch[4] Iteration[950/1524] Loss 2.687 Acc 0.725 ID 1.394 TRI 0.125 Align 0.266 GPD 0.150 TIR-G 0.455 TIR-L 0.328 Keep 0.053 S-Hard 0.021 LR 9.38e-05
2026-09-09 07:24:42,919 transreid.train INFO: Epoch[4] Iteration[950/1524] Loss 2.763 Acc 0.710 ID 1.434 TRI 0.123 Align 0.268 GPD 0.158 TIR-G 0.458 TIR-L 0.328 Keep 0.053 S-Hard 0.023 LR 9.38e-05
2026-09-09 07:25:02,653 transreid.train INFO: Epoch[4] Iteration[1000/1524] Loss 2.637 Acc 0.730 ID 1.368 TRI 0.122 Align 0.265 GPD 0.148 TIR-G 0.453 TIR-L 0.327 Keep 0.053 S-Hard 0.021 LR 9.38e-05
2026-09-09 07:25:02,653 transreid.train INFO: Epoch[4] Iteration[1000/1524] Loss 2.727 Acc 0.715 ID 1.414 TRI 0.123 Align 0.268 GPD 0.157 TIR-G 0.457 TIR-L 0.328 Keep 0.053 S-Hard 0.022 LR 9.38e-05
2026-09-09 07:25:22,476 transreid.train INFO: Epoch[4] Iteration[1050/1524] Loss 2.603 Acc 0.734 ID 1.350 TRI 0.122 Align 0.265 GPD 0.145 TIR-G 0.451 TIR-L 0.326 Keep 0.053 S-Hard 0.021 LR 9.38e-05
2026-09-09 07:25:22,476 transreid.train INFO: Epoch[4] Iteration[1050/1524] Loss 2.673 Acc 0.722 ID 1.386 TRI 0.121 Align 0.267 GPD 0.153 TIR-G 0.454 TIR-L 0.326 Keep 0.053 S-Hard 0.022 LR 9.38e-05
2026-09-09 07:25:42,174 transreid.train INFO: Epoch[4] Iteration[1100/1524] Loss 2.633 Acc 0.726 ID 1.364 TRI 0.120 Align 0.267 GPD 0.151 TIR-G 0.452 TIR-L 0.325 Keep 0.053 S-Hard 0.021 LR 9.38e-05
2026-09-09 07:25:42,174 transreid.train INFO: Epoch[4] Iteration[1100/1524] Loss 2.560 Acc 0.739 ID 1.327 TRI 0.121 Align 0.265 GPD 0.143 TIR-G 0.449 TIR-L 0.325 Keep 0.053 S-Hard 0.020 LR 9.38e-05
2026-09-09 07:26:01,861 transreid.train INFO: Epoch[4] Iteration[1150/1524] Loss 2.584 Acc 0.732 ID 1.338 TRI 0.119 Align 0.266 GPD 0.148 TIR-G 0.450 TIR-L 0.324 Keep 0.053 S-Hard 0.021 LR 9.38e-05
2026-09-09 07:26:01,861 transreid.train INFO: Epoch[4] Iteration[1150/1524] Loss 2.517 Acc 0.744 ID 1.304 TRI 0.121 Align 0.264 GPD 0.141 TIR-G 0.447 TIR-L 0.324 Keep 0.052 S-Hard 0.020 LR 9.38e-05
2026-09-09 07:26:21,602 transreid.train INFO: Epoch[4] Iteration[1200/1524] Loss 2.469 Acc 0.750 ID 1.278 TRI 0.120 Align 0.263 GPD 0.137 TIR-G 0.444 TIR-L 0.323 Keep 0.052 S-Hard 0.019 LR 9.38e-05
2026-09-09 07:26:21,602 transreid.train INFO: Epoch[4] Iteration[1200/1524] Loss 2.529 Acc 0.738 ID 1.308 TRI 0.118 Align 0.265 GPD 0.145 TIR-G 0.447 TIR-L 0.323 Keep 0.053 S-Hard 0.020 LR 9.38e-05
2026-09-09 07:26:41,348 transreid.train INFO: Epoch[4] Iteration[1250/1524] Loss 2.417 Acc 0.756 ID 1.250 TRI 0.118 Align 0.262 GPD 0.133 TIR-G 0.441 TIR-L 0.321 Keep 0.052 S-Hard 0.019 LR 9.38e-05
2026-09-09 07:26:41,348 transreid.train INFO: Epoch[4] Iteration[1250/1524] Loss 2.473 Acc 0.745 ID 1.278 TRI 0.117 Align 0.264 GPD 0.141 TIR-G 0.444 TIR-L 0.321 Keep 0.052 S-Hard 0.020 LR 9.38e-05
2026-09-09 07:27:01,165 transreid.train INFO: Epoch[4] Iteration[1300/1524] Loss 2.365 Acc 0.762 ID 1.222 TRI 0.117 Align 0.262 GPD 0.130 TIR-G 0.438 TIR-L 0.319 Keep 0.052 S-Hard 0.018 LR 9.38e-05
2026-09-09 07:27:01,165 transreid.train INFO: Epoch[4] Iteration[1300/1524] Loss 2.421 Acc 0.751 ID 1.250 TRI 0.116 Align 0.263 GPD 0.137 TIR-G 0.440 TIR-L 0.320 Keep 0.052 S-Hard 0.019 LR 9.38e-05
2026-09-09 07:27:20,943 transreid.train INFO: Epoch[4] Iteration[1350/1524] Loss 2.365 Acc 0.757 ID 1.220 TRI 0.115 Align 0.262 GPD 0.133 TIR-G 0.437 TIR-L 0.318 Keep 0.052 S-Hard 0.018 LR 9.38e-05
2026-09-09 07:27:20,943 transreid.train INFO: Epoch[4] Iteration[1350/1524] Loss 2.311 Acc 0.768 ID 1.193 TRI 0.117 Align 0.260 GPD 0.126 TIR-G 0.435 TIR-L 0.317 Keep 0.052 S-Hard 0.018 LR 9.38e-05
2026-09-09 07:27:40,750 transreid.train INFO: Epoch[4] Iteration[1400/1524] Loss 2.311 Acc 0.764 ID 1.191 TRI 0.114 Align 0.261 GPD 0.129 TIR-G 0.433 TIR-L 0.316 Keep 0.052 S-Hard 0.018 LR 9.38e-05
2026-09-09 07:27:40,750 transreid.train INFO: Epoch[4] Iteration[1400/1524] Loss 2.258 Acc 0.774 ID 1.164 TRI 0.115 Align 0.259 GPD 0.123 TIR-G 0.431 TIR-L 0.316 Keep 0.052 S-Hard 0.017 LR 9.38e-05
2026-09-09 07:28:00,525 transreid.train INFO: Epoch[4] Iteration[1450/1524] Loss 2.257 Acc 0.769 ID 1.162 TRI 0.113 Align 0.259 GPD 0.125 TIR-G 0.430 TIR-L 0.314 Keep 0.052 S-Hard 0.017 LR 9.38e-05
2026-09-09 07:28:00,527 transreid.train INFO: Epoch[4] Iteration[1450/1524] Loss 2.205 Acc 0.780 ID 1.135 TRI 0.114 Align 0.257 GPD 0.120 TIR-G 0.428 TIR-L 0.314 Keep 0.051 S-Hard 0.017 LR 9.38e-05
2026-09-09 07:28:20,493 transreid.train INFO: Epoch[4] Iteration[1500/1524] Loss 2.200 Acc 0.776 ID 1.131 TRI 0.111 Align 0.257 GPD 0.122 TIR-G 0.426 TIR-L 0.312 Keep 0.051 S-Hard 0.017 LR 9.38e-05
2026-09-09 07:28:20,493 transreid.train INFO: Epoch[4] Iteration[1500/1524] Loss 2.151 Acc 0.786 ID 1.106 TRI 0.113 Align 0.256 GPD 0.116 TIR-G 0.424 TIR-L 0.311 Keep 0.051 S-Hard 0.016 LR 9.38e-05
2026-09-09 07:28:31,766 transreid.train INFO: Epoch 4 done in 606.1s; loss 2.1662; acc 0.7793
2026-09-09 07:28:53,746 transreid.train INFO: Epoch[5] Iteration[50/1528] Loss 3.479 Acc 0.641 ID 1.810 TRI 0.153 Align 0.265 GPD 0.231 TIR-G 0.479 TIR-L 0.345 Keep 0.055 S-Hard 0.029 LR 9.05e-05
2026-09-09 07:28:53,747 transreid.train INFO: Epoch[5] Iteration[50/1528] Loss 3.146 Acc 0.647 ID 1.628 TRI 0.124 Align 0.270 GPD 0.196 TIR-G 0.467 TIR-L 0.331 Keep 0.055 S-Hard 0.027 LR 9.05e-05
2026-09-09 07:29:13,634 transreid.train INFO: Epoch[5] Iteration[100/1528] Loss 3.021 Acc 0.668 ID 1.568 TRI 0.126 Align 0.268 GPD 0.173 TIR-G 0.459 TIR-L 0.328 Keep 0.055 S-Hard 0.026 LR 9.05e-05
2026-09-09 07:29:13,634 transreid.train INFO: Epoch[5] Iteration[100/1528] Loss 3.375 Acc 0.636 ID 1.758 TRI 0.150 Align 0.270 GPD 0.204 TIR-G 0.473 TIR-L 0.340 Keep 0.055 S-Hard 0.027 LR 9.05e-05
2026-09-09 07:29:33,375 transreid.train INFO: Epoch[5] Iteration[150/1528] Loss 3.307 Acc 0.636 ID 1.727 TRI 0.137 Align 0.271 GPD 0.194 TIR-G 0.472 TIR-L 0.337 Keep 0.055 S-Hard 0.027 LR 9.05e-05
2026-09-09 07:29:33,375 transreid.train INFO: Epoch[5] Iteration[150/1528] Loss 3.067 Acc 0.663 ID 1.589 TRI 0.133 Align 0.267 GPD 0.174 TIR-G 0.462 TIR-L 0.330 Keep 0.055 S-Hard 0.026 LR 9.05e-05
2026-09-09 07:29:52,960 transreid.train INFO: Epoch[5] Iteration[200/1528] Loss 3.310 Acc 0.638 ID 1.729 TRI 0.139 Align 0.269 GPD 0.193 TIR-G 0.471 TIR-L 0.335 Keep 0.054 S-Hard 0.027 LR 9.05e-05
2026-09-09 07:29:52,960 transreid.train INFO: Epoch[5] Iteration[200/1528] Loss 3.039 Acc 0.670 ID 1.579 TRI 0.130 Align 0.267 GPD 0.169 TIR-G 0.460 TIR-L 0.328 Keep 0.054 S-Hard 0.025 LR 9.05e-05
2026-09-09 07:30:12,597 transreid.train INFO: Epoch[5] Iteration[250/1528] Loss 3.036 Acc 0.674 ID 1.575 TRI 0.132 Align 0.265 GPD 0.170 TIR-G 0.461 TIR-L 0.329 Keep 0.054 S-Hard 0.025 LR 9.05e-05
2026-09-09 07:30:12,597 transreid.train INFO: Epoch[5] Iteration[250/1528] Loss 3.213 Acc 0.652 ID 1.673 TRI 0.133 Align 0.271 GPD 0.190 TIR-G 0.467 TIR-L 0.332 Keep 0.054 S-Hard 0.026 LR 9.05e-05
2026-09-09 07:30:32,303 transreid.train INFO: Epoch[5] Iteration[300/1528] Loss 3.235 Acc 0.651 ID 1.685 TRI 0.138 Align 0.268 GPD 0.189 TIR-G 0.469 TIR-L 0.333 Keep 0.053 S-Hard 0.027 LR 9.05e-05
2026-09-09 07:30:32,303 transreid.train INFO: Epoch[5] Iteration[300/1528] Loss 2.977 Acc 0.681 ID 1.546 TRI 0.129 Align 0.264 GPD 0.165 TIR-G 0.459 TIR-L 0.327 Keep 0.053 S-Hard 0.024 LR 9.05e-05
2026-09-09 07:30:52,058 transreid.train INFO: Epoch[5] Iteration[350/1528] Loss 3.157 Acc 0.661 ID 1.642 TRI 0.134 Align 0.269 GPD 0.186 TIR-G 0.467 TIR-L 0.332 Keep 0.054 S-Hard 0.026 LR 9.05e-05
2026-09-09 07:30:52,059 transreid.train INFO: Epoch[5] Iteration[350/1528] Loss 2.976 Acc 0.683 ID 1.545 TRI 0.130 Align 0.264 GPD 0.164 TIR-G 0.459 TIR-L 0.327 Keep 0.053 S-Hard 0.024 LR 9.05e-05
2026-09-09 07:31:11,803 transreid.train INFO: Epoch[5] Iteration[400/1528] Loss 3.087 Acc 0.671 ID 1.604 TRI 0.133 Align 0.269 GPD 0.181 TIR-G 0.465 TIR-L 0.331 Keep 0.053 S-Hard 0.026 LR 9.05e-05
2026-09-09 07:31:11,803 transreid.train INFO: Epoch[5] Iteration[400/1528] Loss 2.963 Acc 0.684 ID 1.538 TRI 0.129 Align 0.264 GPD 0.164 TIR-G 0.460 TIR-L 0.328 Keep 0.053 S-Hard 0.024 LR 9.05e-05
2026-09-09 07:31:31,532 transreid.train INFO: Epoch[5] Iteration[450/1528] Loss 3.026 Acc 0.678 ID 1.572 TRI 0.129 Align 0.270 GPD 0.176 TIR-G 0.464 TIR-L 0.330 Keep 0.054 S-Hard 0.025 LR 9.05e-05
2026-09-09 07:31:31,532 transreid.train INFO: Epoch[5] Iteration[450/1528] Loss 2.968 Acc 0.686 ID 1.541 TRI 0.129 Align 0.265 GPD 0.163 TIR-G 0.461 TIR-L 0.329 Keep 0.053 S-Hard 0.024 LR 9.05e-05
2026-09-09 07:31:51,254 transreid.train INFO: Epoch[5] Iteration[500/1528] Loss 2.990 Acc 0.683 ID 1.553 TRI 0.128 Align 0.269 GPD 0.172 TIR-G 0.463 TIR-L 0.330 Keep 0.054 S-Hard 0.024 LR 9.05e-05
2026-09-09 07:31:51,255 transreid.train INFO: Epoch[5] Iteration[500/1528] Loss 2.935 Acc 0.691 ID 1.523 TRI 0.128 Align 0.266 GPD 0.162 TIR-G 0.461 TIR-L 0.329 Keep 0.054 S-Hard 0.024 LR 9.05e-05
2026-09-09 07:32:11,004 transreid.train INFO: Epoch[5] Iteration[550/1528] Loss 2.915 Acc 0.694 ID 1.512 TRI 0.128 Align 0.265 GPD 0.163 TIR-G 0.461 TIR-L 0.329 Keep 0.053 S-Hard 0.024 LR 9.05e-05
2026-09-09 07:32:11,004 transreid.train INFO: Epoch[5] Iteration[550/1528] Loss 2.988 Acc 0.684 ID 1.551 TRI 0.130 Align 0.269 GPD 0.172 TIR-G 0.463 TIR-L 0.330 Keep 0.053 S-Hard 0.024 LR 9.05e-05
2026-09-09 07:32:30,848 transreid.train INFO: Epoch[5] Iteration[600/1528] Loss 2.975 Acc 0.685 ID 1.544 TRI 0.129 Align 0.269 GPD 0.175 TIR-G 0.463 TIR-L 0.330 Keep 0.053 S-Hard 0.024 LR 9.05e-05
2026-09-09 07:32:30,848 transreid.train INFO: Epoch[5] Iteration[600/1528] Loss 2.906 Acc 0.695 ID 1.508 TRI 0.128 Align 0.265 GPD 0.163 TIR-G 0.461 TIR-L 0.329 Keep 0.053 S-Hard 0.024 LR 9.05e-05
2026-09-09 07:32:50,555 transreid.train INFO: Epoch[5] Iteration[650/1528] Loss 2.876 Acc 0.700 ID 1.491 TRI 0.128 Align 0.265 GPD 0.163 TIR-G 0.459 TIR-L 0.328 Keep 0.053 S-Hard 0.023 LR 9.05e-05
2026-09-09 07:32:50,555 transreid.train INFO: Epoch[5] Iteration[650/1528] Loss 2.952 Acc 0.689 ID 1.532 TRI 0.127 Align 0.269 GPD 0.174 TIR-G 0.462 TIR-L 0.330 Keep 0.054 S-Hard 0.024 LR 9.05e-05
2026-09-09 07:33:10,266 transreid.train INFO: Epoch[5] Iteration[700/1528] Loss 2.850 Acc 0.703 ID 1.477 TRI 0.126 Align 0.264 GPD 0.164 TIR-G 0.459 TIR-L 0.328 Keep 0.054 S-Hard 0.023 LR 9.05e-05
2026-09-09 07:33:10,266 transreid.train INFO: Epoch[5] Iteration[700/1528] Loss 2.919 Acc 0.693 ID 1.515 TRI 0.127 Align 0.269 GPD 0.171 TIR-G 0.461 TIR-L 0.330 Keep 0.054 S-Hard 0.024 LR 9.05e-05
2026-09-09 07:33:29,998 transreid.train INFO: Epoch[5] Iteration[750/1528] Loss 2.882 Acc 0.699 ID 1.495 TRI 0.127 Align 0.268 GPD 0.170 TIR-G 0.460 TIR-L 0.329 Keep 0.054 S-Hard 0.023 LR 9.05e-05
2026-09-09 07:33:29,998 transreid.train INFO: Epoch[5] Iteration[750/1528] Loss 2.816 Acc 0.708 ID 1.460 TRI 0.125 Align 0.265 GPD 0.162 TIR-G 0.458 TIR-L 0.328 Keep 0.054 S-Hard 0.023 LR 9.05e-05
2026-09-09 07:33:49,728 transreid.train INFO: Epoch[5] Iteration[800/1528] Loss 2.852 Acc 0.702 ID 1.480 TRI 0.127 Align 0.268 GPD 0.168 TIR-G 0.459 TIR-L 0.328 Keep 0.054 S-Hard 0.023 LR 9.05e-05
2026-09-09 07:33:49,728 transreid.train INFO: Epoch[5] Iteration[800/1528] Loss 2.779 Acc 0.713 ID 1.441 TRI 0.123 Align 0.265 GPD 0.159 TIR-G 0.457 TIR-L 0.327 Keep 0.053 S-Hard 0.023 LR 9.05e-05
2026-09-09 07:34:09,464 transreid.train INFO: Epoch[5] Iteration[850/1528] Loss 2.758 Acc 0.716 ID 1.429 TRI 0.123 Align 0.264 GPD 0.158 TIR-G 0.456 TIR-L 0.326 Keep 0.053 S-Hard 0.022 LR 9.05e-05
2026-09-09 07:34:09,464 transreid.train INFO: Epoch[5] Iteration[850/1528] Loss 2.808 Acc 0.708 ID 1.456 TRI 0.125 Align 0.269 GPD 0.166 TIR-G 0.457 TIR-L 0.327 Keep 0.053 S-Hard 0.023 LR 9.05e-05
2026-09-09 07:34:29,115 transreid.train INFO: Epoch[5] Iteration[900/1528] Loss 2.734 Acc 0.719 ID 1.418 TRI 0.123 Align 0.264 GPD 0.156 TIR-G 0.455 TIR-L 0.326 Keep 0.053 S-Hard 0.022 LR 9.05e-05
2026-09-09 07:34:29,116 transreid.train INFO: Epoch[5] Iteration[900/1528] Loss 2.767 Acc 0.714 ID 1.435 TRI 0.124 Align 0.268 GPD 0.164 TIR-G 0.456 TIR-L 0.327 Keep 0.053 S-Hard 0.022 LR 9.05e-05
2026-09-09 07:34:48,900 transreid.train INFO: Epoch[5] Iteration[950/1528] Loss 2.728 Acc 0.718 ID 1.414 TRI 0.123 Align 0.268 GPD 0.161 TIR-G 0.454 TIR-L 0.326 Keep 0.053 S-Hard 0.022 LR 9.05e-05
2026-09-09 07:34:48,900 transreid.train INFO: Epoch[5] Iteration[950/1528] Loss 2.696 Acc 0.723 ID 1.398 TRI 0.121 Align 0.264 GPD 0.155 TIR-G 0.453 TIR-L 0.325 Keep 0.053 S-Hard 0.022 LR 9.05e-05
2026-09-09 07:35:08,669 transreid.train INFO: Epoch[5] Iteration[1000/1528] Loss 2.692 Acc 0.723 ID 1.395 TRI 0.122 Align 0.268 GPD 0.159 TIR-G 0.453 TIR-L 0.325 Keep 0.053 S-Hard 0.022 LR 9.05e-05
2026-09-09 07:35:08,669 transreid.train INFO: Epoch[5] Iteration[1000/1528] Loss 2.661 Acc 0.727 ID 1.379 TRI 0.121 Align 0.264 GPD 0.153 TIR-G 0.452 TIR-L 0.325 Keep 0.053 S-Hard 0.021 LR 9.05e-05

,stage,status,reason,epoch,next_iteration,epoch_complete,global_step,best_mAP,remaining_minutes
0,E3-TDH,completed,training_completed,25,0,True,38207,11.805238,306.6

Running final standard + horizontal-flip TTA evaluation...
2026-09-09 11:57:47,478 transreid INFO: Namespace(config_file='configs/PVUAD.yml', opts=['MODEL.DIST_TRAIN', 'False', 'MODEL.PRETRAIN_CHOICE', 'none', 'MODEL.PRETRAIN_PATH', '/kaggle/working/vit_transreid_msmt.pth', 'MODEL.STRIDE_SIZE', '[16, 16]', 'MODEL.SIE_CAMERA', 'False', 'MODEL.SIE_VIEW', 'False', 'DATASETS.ROOT_DIR', '/kaggle/working/pvuad_data', 'DATALOADER.NUM_WORKERS', '4', 'TEST.IMS_PER_BATCH', '256', 'TEST.RE_RANKING', 'False', 'TEST.TOP_K_EVAL', '0', 'TEST.WEIGHT', '/kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/pvuad_best_model.pth', 'OUTPUT_DIR', '/kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh', 'PVUAD.EXPERIMENT', 'E3-TDH', 'PVUAD.STAGE', 'final', 'PVUAD.DEV_MODE', 'False', 'PVUAD.PAIRED_VIEW_SAMPLER', 'True', 'PVUAD.STRICT_PAIRED_DATA', 'False', 'PVUAD.VFPROCA', 'True', 'PVUAD.TEST_INVARIANT_BLEND', '0.5', 'PVUAD.TIR_DISTILLATION', 'True', 'PVUAD.FEATURE_PRESERVE_WEIGHT', '0.0', 'PVUAD.SCENARIO_HARD_GPD', 'True', 'PVUAD.FINAL_FLIP_TTA', 'True'])
2026-09-09 11:57:47,479 transreid INFO: Loaded configuration file configs/PVUAD.yml
2026-09-09 11:57:47,479 transreid INFO:
MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: 'jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'wrt'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_in'
  STRIDE_SIZE: [16, 16]
  PCA_LOSS_WEIGHT: 0.01
  GPD_MOMENTUM: 0.2

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: ('WHU-MARS')
  ROOT_DIR: ('/kaggle/working/pvuad_data')
  MODALITIES: ['RGB', 'IR', 'Thermal']

DATALOADER:
  SAMPLER: 'PKM'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.008
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  WARMUP_EPOCHS: 5
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 50
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  LOSS_TYPE: "base+pca+gpd"

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  TOP_K_EVAL: 0

PVUAD:
  EXPERIMENT: 'E0'
  STAGE: 'final'
  DEV_MODE: False
  DEV_VAL_IDS: 100
  DEV_SPLIT_SEED: 2026
  DEV_QUERY_PER_PID_CAM: 1
  PAIRED_VIEW_SAMPLER: False
  SYNC_PAIRED_AUG: False
  GROUND_MAX_CAMID: 4
  STRICT_PAIRED_DATA: True
  VFPROCA: False
  VIEW_ALIGNMENT_WEIGHT: 0.5
  INVARIANT_ID_WEIGHT: 0.5
  SCENARIO_CLS_WEIGHT: 0.1
  TEST_INVARIANT_BLEND: 0.5
  LOCAL_CONSISTENCY: False
  LOCAL_CONSISTENCY_WEIGHT: 0.05
  HARD_GPD: False
  HARD_GPD_WEIGHT: 0.5
  HARD_GPD_TOPK: 10
  HARD_GPD_MARGIN: 0.10
  HARD_GPD_START_EPOCH: 10
  FINETUNE: False
  WARMSTART_MODEL_PATH: ''
  WARMSTART_PROTOTYPE_PATH: ''
  TEACHER_MODEL_PATH: ''
  HEAD_LR_MULTIPLIER: 1.0
  TIR_DISTILLATION: False
  TIR_GLOBAL_WEIGHT: 0.10
  TIR_LOCAL_WEIGHT: 0.03
  TIR_LOCAL_KEEP_RATIO: 0.50
  FEATURE_PRESERVE_WEIGHT: 0.05
  SCENARIO_HARD_GPD: False
  SCENARIO_HARD_WEIGHT: 0.15
  SCENARIO_HARD_TOPK: 5
  SCENARIO_HARD_MARGIN: 0.05
  SCENARIO_HARD_TAU: 0.05
  SCENARIO_HARD_START_EPOCH: 3
  SCENARIO_BANK_MOMENTUM: 0.20
  FINAL_FLIP_TTA: False
  TTA_METRICS_FILENAME: 'tta_metrics.csv'
  RESUME_PATH: ''
  SAVE_LAST_EVERY: 5
  SAVE_BEST: True
  METRICS_FILENAME: 'metrics_history.csv'
  RUN_MANIFEST: ''
  SESSION_DEADLINE_UNIX: 0.0
  STOP_RESERVE_MINUTES: 10.0
  CHECKPOINT_EVERY_MINUTES: 30.0
  TIME_CHECK_EVERY_STEPS: 10
  MIN_EVAL_REMAINING_MINUTES: 35.0
  STATUS_FILENAME: 'session_status.json'
  STRICT_RESUME_CONFIG: True

OUTPUT_DIR: './logs/PVUAD'

2026-09-09 11:57:47,480 transreid INFO: Running with config:
DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 4
  SAMPLER: PKM
DATASETS:
  MODALITIES: ('RGB', 'IR', 'Thermal')
  NAMES: WHU-MARS
  ROOT_DIR: /kaggle/working/pvuad_data
INPUT:
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  PROB: 0.5
  RE_PROB: 0.5
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MODEL:
  ATT_DROP_RATE: 0.0
  COS_LAYER: False
  DEVICE: cuda
  DEVICE_ID: 0
  DEVIDE_LENGTH: 4
  DIST_TRAIN: False
  DROP_OUT: 0.0
  DROP_PATH: 0.1
  GPD_MOMENTUM: 0.2
  ID_LOSS_TYPE: softmax
  ID_LOSS_WEIGHT: 1.0
  IF_LABELSMOOTH: off
  IF_WITH_CENTER: no
  JPM: False
  LAST_STRIDE: 1
  METRIC_LOSS_TYPE: wrt
  NAME: transformer
  NECK: bnneck
  NO_MARGIN: True
  PCA_LOSS_WEIGHT: 0.01
  PRETRAIN_CHOICE: none
  PRETRAIN_PATH: /kaggle/working/vit_transreid_msmt.pth
  RE_ARRANGE: True
  SHIFT_NUM: 5
  SHUFFLE_GROUP: 2
  SIE_CAMERA: False
  SIE_COE: 3.0
  SIE_VIEW: False
  STRIDE_SIZE: [16, 16]
  TRANSFORMER_TYPE: vit_base_in
  TRIPLET_LOSS_WEIGHT: 1.0
OUTPUT_DIR: /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh
PVUAD:
  CHECKPOINT_EVERY_MINUTES: 30.0
  DEV_MODE: False
  DEV_QUERY_PER_PID_CAM: 1
  DEV_SPLIT_SEED: 2026
  DEV_VAL_IDS: 100
  EXPERIMENT: E3-TDH
  FEATURE_PRESERVE_WEIGHT: 0.0
  FINAL_FLIP_TTA: True
  FINETUNE: False
  GROUND_MAX_CAMID: 4
  HARD_GPD: False
  HARD_GPD_MARGIN: 0.1
  HARD_GPD_START_EPOCH: 10
  HARD_GPD_TOPK: 10
  HARD_GPD_WEIGHT: 0.5
  HEAD_LR_MULTIPLIER: 1.0
  INVARIANT_ID_WEIGHT: 0.5
  LOCAL_CONSISTENCY: False
  LOCAL_CONSISTENCY_WEIGHT: 0.05
  METRICS_FILENAME: metrics_history.csv
  MIN_EVAL_REMAINING_MINUTES: 35.0
  PAIRED_VIEW_SAMPLER: True
  RESUME_PATH:
  RUN_MANIFEST:
  SAVE_BEST: True
  SAVE_LAST_EVERY: 5
  SCENARIO_BANK_MOMENTUM: 0.2
  SCENARIO_CLS_WEIGHT: 0.1
  SCENARIO_HARD_GPD: True
  SCENARIO_HARD_MARGIN: 0.05
  SCENARIO_HARD_START_EPOCH: 3
  SCENARIO_HARD_TAU: 0.05
  SCENARIO_HARD_TOPK: 5
  SCENARIO_HARD_WEIGHT: 0.15
  SESSION_DEADLINE_UNIX: 0.0
  STAGE: final
  STATUS_FILENAME: session_status.json
  STOP_RESERVE_MINUTES: 10.0
  STRICT_PAIRED_DATA: False
  STRICT_RESUME_CONFIG: True
  SYNC_PAIRED_AUG: False
  TEACHER_MODEL_PATH:
  TEST_INVARIANT_BLEND: 0.5
  TIME_CHECK_EVERY_STEPS: 10
  TIR_DISTILLATION: True
  TIR_GLOBAL_WEIGHT: 0.1
  TIR_LOCAL_KEEP_RATIO: 0.5
  TIR_LOCAL_WEIGHT: 0.03
  TTA_METRICS_FILENAME: tta_metrics.csv
  VFPROCA: True
  VIEW_ALIGNMENT_WEIGHT: 0.5
  WARMSTART_MODEL_PATH:
  WARMSTART_PROTOTYPE_PATH:
SOLVER:
  BASE_LR: 0.008
  BIAS_LR_FACTOR: 2
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 5
  COSINE_MARGIN: 0.5
  COSINE_SCALE: 30
  EVAL_PERIOD: 10
  GAMMA: 0.1
  IMS_PER_BATCH: 64
  LARGE_FC_LR: False
  LOG_PERIOD: 50
  LOSS_TYPE: base+pca+gpd
  MARGIN: 0.3
  MAX_EPOCHS: 120
  MOMENTUM: 0.9
  OPTIMIZER_NAME: SGD
  SEED: 1234
  STEPS: (40, 70)
  WARMUP_EPOCHS: 5
  WARMUP_FACTOR: 0.01
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
TEST:
  DIST_MAT: dist_mat.npy
  EVAL: True
  FEAT_NORM: yes
  IMS_PER_BATCH: 256
  NECK_FEAT: before
  RE_RANKING: False
  TOP_K_EVAL: 0
  WEIGHT: /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/pvuad_best_model.pth
=> WHU-MARS loaded
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   500 |    92133 |         7
  query    |   500 |     6405 |         7
  gallery  |   500 |    93609 |         7
  ----------------------------------------
PairedViewPKM: 500 IDs (216 dual-view, 284 single-view), 37,148 paired sample slots/epoch, 16 PID x 4 instances per GPU
using Transformer_type: vit_base_in as a backbone
using stride: [16, 16], and patch number is num_y16 * num_x8
===========building transformer===========
Loading pretrained model from /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/pvuad_best_model.pth (loaded=170, skipped=3)
2026-09-09 11:57:51,357 transreid.test INFO: Enter inferencing
2026-09-09 12:05:28,925 transreid.test INFO: => Split mode 1: query 2135, total query 2135
2026-09-09 12:05:28,974 transreid.test INFO: => Split mode 2: query 2135, total query 4270
2026-09-09 12:05:29,021 transreid.test INFO: => Split mode 3: query 2135, total query 6405
2026-09-09 12:05:29,182 transreid.test INFO: The test feature is normalized
2026-09-09 12:05:29,334 transreid.test INFO: => Computing DistMat in q-chunks (chunk=4000)
2026-09-09 12:06:29,168 transreid.test INFO: Starting modality-pair specific evaluation. Query mods: [np.int64(1), np.int64(2), np.int64(3)], Gallery mods: [np.int64(1), np.int64(2), np.int64(3)]
2026-09-09 12:06:34,638 transreid.test INFO:   Pair (Q:1, G:1) -> mAP: 29.47%, Rank-1: 43.28%
2026-09-09 12:06:40,073 transreid.test INFO:   Pair (Q:1, G:2) -> mAP: 17.61%, Rank-1: 26.93%
2026-09-09 12:06:45,727 transreid.test INFO:   Pair (Q:1, G:3) -> mAP: 5.41%, Rank-1: 6.93%
2026-09-09 12:06:51,367 transreid.test INFO:   Pair (Q:2, G:1) -> mAP: 17.60%, Rank-1: 25.62%
2026-09-09 12:06:56,993 transreid.test INFO:   Pair (Q:2, G:2) -> mAP: 18.97%, Rank-1: 29.93%
2026-09-09 12:07:02,628 transreid.test INFO:   Pair (Q:2, G:3) -> mAP: 4.92%, Rank-1: 6.37%
2026-09-09 12:07:08,305 transreid.test INFO:   Pair (Q:3, G:1) -> mAP: 5.75%, Rank-1: 7.26%
2026-09-09 12:07:13,967 transreid.test INFO:   Pair (Q:3, G:2) -> mAP: 5.02%, Rank-1: 6.60%
2026-09-09 12:07:19,565 transreid.test INFO:   Pair (Q:3, G:3) -> mAP: 13.57%, Rank-1: 20.47%
2026-09-09 12:07:19,708 transreid.test INFO: Validation Results
2026-09-09 12:07:19,708 transreid.test INFO: mAP: 11.81%
2026-09-09 12:07:19,709 transreid.test INFO: CMC curve, Rank-1  :30.85%
2026-09-09 12:07:19,709 transreid.test INFO: CMC curve, Rank-5  :47.34%
2026-09-09 12:07:19,709 transreid.test INFO: CMC curve, Rank-10 :56.10%
2026-09-09 12:07:19,709 transreid.test INFO: Running horizontal-flip feature averaging
2026-09-09 12:22:19,097 transreid.test INFO: => Split mode 1: query 2135, total query 2135
2026-09-09 12:22:19,147 transreid.test INFO: => Split mode 2: query 2135, total query 4270
2026-09-09 12:22:19,195 transreid.test INFO: => Split mode 3: query 2135, total query 6405
2026-09-09 12:22:19,356 transreid.test INFO: The test feature is normalized
2026-09-09 12:22:19,506 transreid.test INFO: => Computing DistMat in q-chunks (chunk=4000)
2026-09-09 12:23:18,662 transreid.test INFO: Starting modality-pair specific evaluation. Query mods: [np.int64(1), np.int64(2), np.int64(3)], Gallery mods: [np.int64(1), np.int64(2), np.int64(3)]
2026-09-09 12:23:24,107 transreid.test INFO:   Pair (Q:1, G:1) -> mAP: 29.55%, Rank-1: 43.14%
2026-09-09 12:23:29,414 transreid.test INFO:   Pair (Q:1, G:2) -> mAP: 17.75%, Rank-1: 27.82%
2026-09-09 12:23:34,738 transreid.test INFO:   Pair (Q:1, G:3) -> mAP: 5.47%, Rank-1: 7.40%
2026-09-09 12:23:40,007 transreid.test INFO:   Pair (Q:2, G:1) -> mAP: 17.68%, Rank-1: 25.15%
2026-09-09 12:23:45,380 transreid.test INFO:   Pair (Q:2, G:2) -> mAP: 19.07%, Rank-1: 29.60%
2026-09-09 12:23:50,711 transreid.test INFO:   Pair (Q:2, G:3) -> mAP: 4.96%, Rank-1: 6.56%
2026-09-09 12:23:56,045 transreid.test INFO:   Pair (Q:3, G:1) -> mAP: 5.81%, Rank-1: 7.54%
2026-09-09 12:24:01,414 transreid.test INFO:   Pair (Q:3, G:2) -> mAP: 5.07%, Rank-1: 6.46%
2026-09-09 12:24:06,711 transreid.test INFO:   Pair (Q:3, G:3) -> mAP: 13.68%, Rank-1: 20.47%
2026-09-09 12:24:06,847 transreid.test INFO: Flip-TTA mAP: 11.88%
2026-09-09 12:24:06,847 transreid.test INFO: Flip-TTA CMC, Rank-1  :30.79%
2026-09-09 12:24:06,847 transreid.test INFO: Flip-TTA CMC, Rank-5  :47.59%
2026-09-09 12:24:06,847 transreid.test INFO: Flip-TTA CMC, Rank-10 :56.11%

## 6. Tổng hợp và đóng gói

`pvuad_e2_e3_transreid_init_trainable_reports.zip` chứa log/CSV/JSON nhẹ, bao gồm cả `transreid_trainable_init_audit.json` để xác nhận initialization/gradient.

Checkpoint model vẫn nằm riêng trong `pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/...`.

In [7]:
def best_metrics(run_dir, label):
    path = Path(run_dir) / "metrics_history.csv"
    if not path.is_file():
        return None
    frame = pd.read_csv(path)
    required = {"experiment", "stage", "epoch", "mAP", "Rank-1", "Rank-5", "Rank-10"}
    if frame.empty or not required.issubset(frame.columns):
        return None
    frame = frame.drop_duplicates(
        subset=["experiment", "stage", "epoch"], keep="last"
    )
    frame.to_csv(path, index=False)
    row = frame.loc[frame["mAP"].idxmax()]
    return {
        "method": label,
        "epoch": int(row["epoch"]),
        "mAP": float(row["mAP"]),
        "Rank-1": float(row["Rank-1"]),
        "Rank-5": float(row["Rank-5"]),
        "Rank-10": float(row["Rank-10"]),
    }


state = read_json(PIPELINE_STATE_PATH)
print("Pipeline status:", state.get("status"))
print("Active stage   :", state.get("active_stage"))
print("Next action    :", state.get("next_action"))
init_audit_path = PIPELINE_ROOT / "transreid_trainable_init_audit.json"
if init_audit_path.is_file():
    print("TransReID initialization audit:")
    display(pd.DataFrame([read_json(init_audit_path)]))

comparison = [{
    "method": "UAD paper",
    "epoch": np.nan,
    "mAP": 11.000,
    "Rank-1": 29.500,
    "Rank-5": 46.300,
    "Rank-10": 54.800,
}]
e2_best = best_metrics(E2_RUN_DIR, "E2 TransReID-init")
e3_best = best_metrics(E3_RUN_DIR, "E3-TDH TransReID-init")
if e2_best:
    comparison.append(e2_best)
if e3_best:
    comparison.append(e3_best)

tta_path = E3_RUN_DIR / "tta_metrics.csv"
if tta_path.is_file():
    tta = pd.read_csv(tta_path)
    if not tta.empty:
        row = tta.iloc[-1]
        comparison.append({
            "method": "E3-TDH TransReID-init flip TTA",
            "epoch": E3_EPOCHS,
            "mAP": float(row["mAP"]),
            "Rank-1": float(row["Rank-1"]),
            "Rank-5": float(row["Rank-5"]),
            "Rank-10": float(row["Rank-10"]),
        })

comparison_frame = pd.DataFrame(comparison)
comparison_frame.to_csv(PIPELINE_ROOT / "combined_results.csv", index=False)
display(comparison_frame.round(3))

REPORT_ZIP = Path("/kaggle/working") / "pvuad_e2_e3_transreid_init_trainable_reports.zip"
if REPORT_ZIP.exists():
    REPORT_ZIP.unlink()
report_suffixes = {".csv", ".json", ".txt", ".log", ".yml", ".yaml"}
with zipfile.ZipFile(REPORT_ZIP, "w", compression=zipfile.ZIP_DEFLATED) as archive:
    for path in sorted(PIPELINE_ROOT.rglob("*")):
        if path.is_file() and path.suffix.lower() in report_suffixes:
            archive.write(path, arcname=str(path.relative_to(PIPELINE_ROOT)))

print("\nReport ZIP:", REPORT_ZIP)
print("Pipeline state:", PIPELINE_STATE_PATH)
for stage_name, run_dir in (("E2", E2_RUN_DIR), ("E3", E3_RUN_DIR)):
    for filename in (
        "pvuad_best_model.pth", "pvuad_last_model.pth",
        "pvuad_last_checkpoint.pth", "e2_teacher_model_fp16.pth",
    ):
        path = run_dir / filename
        if path.is_file():
            print(
                f"{stage_name:2s} {filename:30s} "
                f"{path.stat().st_size / 2**20:,.1f} MiB — {path}"
            )

if state.get("status") in {"e2_paused", "e3_paused", "e2_completed_e3_pending", "e3_complete_tta_pending"}:
    print(
        "\nDỪNG AN TOÀN: vì lượt chạy đã được khởi động bằng Save & Run All, "
        "Kaggle sẽ tự lưu Output của version này. Sau đó tạo session mới, "
        "gắn Output đó làm Input và tiếp tục bằng Save & Run All."
    )
elif state.get("status") == "completed":
    print("\nHOÀN TẤT E2 -> E3 + TTA. Không cần chạy thêm session.")

Pipeline status: completed
Active stage   : DONE
Next action    : None
TransReID initialization audit:

,checkpoint,loaded_tensor_count,target_tensor_count,mismatch_count,resized_pos_embed,source_sie_loaded,source_jpm_local_branches_loaded,global_jpm_branch_used_for_target_final_block,global_branch_mapped_tensor_count,embedding_dim,...,feature_shape,init_qkv_max_abs,global_final_qkv_max_abs,qkv_grad_norm,patch_grad_norm,backbone_all_trainable,source_sie_used,source_jpm_local_branches_used,source_jpm_global_final_branch_used,target_stride
0,/kaggle/working/vit_transreid_msmt.pth,152,152,0,"{'source_shape': [1, 211, 768], 'target_shape'...",False,False,True,14,768,...,"[3, 768]",0.0,0.0,0.004051,0.019206,True,False,False,True,"[16, 16]"

                           method  epoch     mAP  Rank-1  Rank-5  Rank-10
0                       UAD paper    NaN  11.000  29.500  46.300   54.800
1               E2 TransReID-init   60.0  11.665  30.773  47.291   55.816
2           E3-TDH TransReID-init   25.0  11.805  30.851  47.338   56.097
3  E3-TDH TransReID-init flip TTA   25.0  11.877  30.788  47.588   56.112

Report ZIP: /kaggle/working/pvuad_e2_e3_transreid_init_trainable_reports.zip
Pipeline state: /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/pipeline_state.json
E3 pvuad_best_model.pth           334.7 MiB — /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/pvuad_best_model.pth
E3 pvuad_last_model.pth           334.7 MiB — /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/pvuad_last_model.pth
E3 pvuad_last_checkpoint.pth      676.8 MiB — /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/pvuad_last_checkpoint.pth
E3 e2_teacher_model_fp16.pth      167.4 MiB — /kaggle/working/pvuad_runs/e2_e3_transreid_init_trainable768_b24_v1/e3_tdh/e2_teacher_model_fp16.pth

HOÀN TẤT E2 -> E3 + TTA. Không cần chạy thêm session.

## Cách chạy qua nhiều phiên Kaggle

1. **Phiên đầu:** chọn **GPU T4 ×2**, attach `whu-mars`. Bật Internet để notebook tải `vit_transreid_msmt.pth`, hoặc attach checkpoint đó như một Kaggle Dataset.
2. **Không attach output E2/E3 cũ để resume** trong phiên đầu. Đây là pipeline tag mới.
3. Chạy bằng **Save Version → Save & Run All**. Trước E2 phải thấy dòng `TRANSREID_TRAINABLE_INIT_SMOKE_OK`.
4. Nếu notebook dừng sạch với `e2_paused`: attach **Output của đúng version vừa chạy** vào phiên kế tiếp rồi Save & Run All.
5. Khi E2 hoàn tất, notebook cố ý dừng ở `e2_completed_e3_pending`; attach output đó sang session mới để E3 bắt đầu.
6. E3 cũng có thể `e3_paused` và resume tương tự.
7. Khi thấy `completed`, lấy report ZIP và checkpoint E3 tốt nhất.

### Dấu hiệu run đúng

Ở fresh E2 log phải thể hiện:
- `MODEL.PRETRAIN_CHOICE = transreid`;
- feature vẫn **768-D**;
- target stride `[16,16]`;
- `source_sie_used=False`, `source_jpm_local_branches_used=False`, nhưng global `b1` được map vào block cuối;
- backbone **TRAINABLE**, không có `extractor_frozen=True`.

Ở resume/E3/TTA, `PRETRAIN_CHOICE=none` là **đúng** vì model lúc đó phải được phục hồi từ checkpoint WHU-MARS, không transplant source weight lần nữa.